// Generated by App Framework. Do not hand-edit.
export const pdsNativeTokens = {
  color: {
    action: "#0077a8",
    border: "#d7e0e6",
    brandDeep: "#123443",
    canvas: "#f6f8fa",
    surface: "#ffffff",
    textMuted: "#5e6b75",
    textStrong: "#1f2a33"
  },
  radius: {
    panel: 18,
    control: 12
  },
  spacing: {
    screen: 20,
    section: 16
  }
} as const;
