use std::collections::BTreeMap;

use anyhow::{Context, Result};
use serde::Serialize;

use crate::{
    app_workspace::AppWorkspace,
    utils::{artifacts, console},
};

#[derive(Debug, Clone, Serialize)]
pub struct ConfigContract {
    pub version: u32,
    pub description: &'static str,
    pub shapes: BTreeMap<&'static str, ConfigShape>,
}

#[derive(Debug, Clone, Serialize)]
pub struct ConfigShape {
    pub name: &'static str,
    pub path_pattern: &'static str,
    pub shape: &'static str,
    pub purpose: &'static str,
    pub fields: Vec<ConfigField>,
    pub lints: Vec<&'static str>,
}

#[derive(Debug, Clone, Serialize)]
pub struct ConfigField {
    pub name: &'static str,
    pub value_type: &'static str,
    pub required: bool,
    pub default: Option<&'static str>,
    pub allowed_values: Vec<&'static str>,
    pub purpose: &'static str,
}

pub fn contract() -> ConfigContract {
    let mut shapes = BTreeMap::new();

    for shape in [
        data_source_shape(),
        data_source_environment_shape(),
        property_fragment_shape(),
        entity_facet_patch_shape(),
        property_facet_patch_shape(),
        schema_shape(),
        sync_descriptor_shape(),
        sync_object_map_shape(),
        sync_object_provenance_shape(),
        sync_object_echo_loop_shape(),
        sync_governance_shape(),
        enum_type_shape(),
        enum_item_shape(),
        relationship_shape(),
        relationship_endpoint_shape(),
        relationship_storage_shape(),
        relationship_junction_shape(),
        entity_type_shape(),
        data_access_execution_shape(),
        property_shape(),
        foreign_key_shape(),
        nav_by_fk_shape(),
        many_to_many_shape(),
        nested_entity_shape(),
        custom_method_shape(),
        custom_method_arg_shape(),
        provider_routine_shape(),
        provider_routine_names_shape(),
        provider_routine_name_shape(),
        seed_group_shape(),
        api_test_shape(),
    ] {
        shapes.insert(shape.name, shape);
    }

    ConfigContract {
        version: 1,
        description: ".appfw/model is product application source. These shapes are the canonical contract used by validation before generation.",
        shapes,
    }
}

pub fn emit(workspace: &AppWorkspace) -> Result<()> {
    let target_dir = &workspace.report_root;

    let contract = contract();
    let json_path = target_dir.join("config_contract.json");
    let markdown_path = target_dir.join("config_contract.md");
    let source_docs_path = workspace.config_root.join("_specs/CONFIG_CONTRACT.md");
    artifacts::safe_write(&json_path, serde_json::to_string_pretty(&contract)? + "\n")
        .with_context(|| format!("could not write {}", json_path.display()))?;
    console::write(&json_path);

    let markdown = markdown(&contract);
    artifacts::safe_write(&markdown_path, &markdown)
        .with_context(|| format!("could not write {}", markdown_path.display()))?;
    console::write(&markdown_path);

    artifacts::safe_write(&source_docs_path, markdown)
        .with_context(|| format!("could not write {}", source_docs_path.display()))?;
    console::write(&source_docs_path);

    Ok(())
}

fn markdown(contract: &ConfigContract) -> String {
    let mut out = String::new();
    out.push_str("# app_gen Config Contract\n\n");
    out.push_str(contract.description);
    out.push_str("\n\n");
    out.push_str("Generated by `app_gen` from `src/config_contract.rs`.\n\n");

    for shape in contract.shapes.values() {
        out.push_str(&format!("## {}\n\n", shape.name));
        out.push_str(&format!("- Path: `{}`\n", shape.path_pattern));
        out.push_str(&format!("- Shape: `{}`\n", shape.shape));
        out.push_str(&format!("- Purpose: {}\n\n", shape.purpose));
        out.push_str("| Field | Type | Required | Default | Allowed | Purpose |\n");
        out.push_str("| --- | --- | --- | --- | --- | --- |\n");
        for field in &shape.fields {
            let default = field.default.unwrap_or("");
            let allowed = if field.allowed_values.is_empty() {
                String::new()
            } else {
                field.allowed_values.join(", ")
            };
            out.push_str(&format!(
                "| `{}` | `{}` | {} | {} | {} | {} |\n",
                field.name, field.value_type, field.required, default, allowed, field.purpose
            ));
        }
        if !shape.lints.is_empty() {
            out.push_str("\nLints:\n");
            for lint in &shape.lints {
                out.push_str(&format!("- `{lint}`\n"));
            }
        }
        out.push('\n');
    }

    while out.ends_with('\n') {
        out.pop();
    }
    out.push('\n');
    out
}

fn data_source_shape() -> ConfigShape {
    ConfigShape {
        name: "data_source",
        path_pattern: ".appfw/model/data_sources/_res.yaml",
        shape: "array<object>",
        purpose: "Declares database providers, graph read providers, and per-environment connection metadata.",
        fields: vec![
            field(
                "name",
                "string",
                true,
                None,
                &[],
                "Unique data source name.",
            ),
            field(
                "data_source_type",
                "enum",
                true,
                None,
                &[
                    "MsSqlServer",
                    "FabricSqlAnalytics",
                    "PostgreSQL",
                    "MongoDB",
                    "Snowflake",
                    "Neo4j",
                    "ServiceNow",
                    "Workday",
                    "Icims",
                    "Salesforce",
                    "Anaplan",
                    "OracleFinancials",
                ],
                "Provider used by schemas or governed read-model capabilities. FabricSqlAnalytics is a read-only Microsoft Fabric SQL analytics endpoint; Neo4j is graph-read only and must not host generated CRUD schemas. ServiceNow, Workday, Icims, Salesforce, Anaplan, and OracleFinancials are external API provider identities for SaaS connector contracts and must not host generated CRUD schemas.",
            ),
            field(
                "is_system_schema_host",
                "boolean",
                false,
                Some("false"),
                &[],
                "Legacy compatibility flag for products that persist system metadata. Omit for the default code-only system schema.",
            ),
            field(
                "description",
                "string",
                false,
                None,
                &[],
                "Human-readable note.",
            ),
            field(
                "meta",
                "json",
                false,
                None,
                &["classification", "data_classification"],
                "Governance metadata. Regulated data sources must declare a known data classification.",
            ),
            field(
                "environments",
                "array<data_source_environment>",
                true,
                None,
                &[],
                "Connection settings by environment.",
            ),
        ],
        lints: vec![
            "duplicate_data_source",
            "duplicate_system_schema_host",
            "missing_data_classification",
            "invalid_data_classification",
        ],
    }
}

fn data_source_environment_shape() -> ConfigShape {
    ConfigShape {
        name: "data_source_environment",
        path_pattern: ".appfw/model/data_sources/_res.yaml $.environments[]",
        shape: "object",
        purpose: "Declares one runtime environment for a data source, including the explicit local/managed transport security posture.",
        fields: vec![
            field("name", "string", true, None, &[], "Environment name selected by ENV_NAME."),
            field(
                "db_host",
                "string",
                true,
                None,
                &["MongoDB: plain host, mongodb:// seed-list URI, mongodb+srv:// Atlas SRV URI"],
                "Database host, provider endpoint, or provider-specific connection URI. MongoDB may use a credential-free seed-list or Atlas SRV URI here; keep credentials in secret-backed service account fields.",
            ),
            field("db_name", "string", true, None, &[], "Database name."),
            field("db_port", "string|number", true, None, &[], "Database port."),
            field(
                "security_profile",
                "enum",
                true,
                None,
                &["local_dev", "managed"],
                "Connection policy profile. `local_dev` is only valid for ENV_NAME=local or ENV_NAME=compose.",
            ),
            field(
                "tls_mode",
                "enum",
                true,
                None,
                &["disabled", "prefer", "require", "verify_ca", "verify_full"],
                "Transport security mode. Non-local environments must use TLS.",
            ),
            field(
                "auth_mode",
                "enum",
                false,
                Some("provider default"),
                appfw_mssql_auth::ALL_MODE_IDS,
                appfw_mssql_auth::config_contract_auth_mode_docs(),
            ),
            field(
                "entra_tenant_id",
                "string",
                false,
                None,
                &[],
                "Optional Microsoft Entra tenant id; normally resolved from secrets for FabricSqlAnalytics client-credentials auth.",
            ),
            field(
                "entra_token_scope",
                "string",
                false,
                Some("https://database.windows.net/.default"),
                &[],
                "Optional Microsoft Entra OAuth v2 token scope for FabricSqlAnalytics client-credentials authentication. Values must end with `.default`.",
            ),
            field(
                "service_account_name",
                "string",
                false,
                None,
                &[],
                "Optional static username or Entra client id; normally resolved from secrets at runtime.",
            ),
            field(
                "service_account_password",
                "string",
                false,
                None,
                &[],
                "Optional static password, Entra client secret, or injected access token; normally resolved from secrets at runtime.",
            ),
        ],
        lints: vec![
            "duplicate_environment",
            "invalid_connection_security",
            "invalid_mongodb_connection_uri",
        ],
    }
}

fn property_fragment_shape() -> ConfigShape {
    let mut shape = property_shape();
    shape.name = "property_fragment";
    shape.path_pattern = ".appfw/model/_fragments/*.yaml";
    shape.shape = "object";
    shape.purpose =
        "Declares reusable property defaults that entity properties opt into with `fragment`.";
    for field in &mut shape.fields {
        if field.name == "name" {
            field.required = false;
            field.default = Some("provided by entity property");
            field.purpose = "Optional fragment-local property name.";
        }
    }
    shape.lints = vec![
        "duplicate_fragment",
        "missing_data_type",
        "missing_enum_type",
    ];
    shape
}

fn entity_facet_patch_shape() -> ConfigShape {
    let mut shape = entity_type_shape();
    shape.name = "entity_facet_patch";
    shape.path_pattern = ".appfw/model/_facets/*.yaml object with props, or array item";
    shape.shape = "object";
    shape.purpose = "Declares a reusable entity patch applied by a named entity facet.";
    for field in &mut shape.fields {
        field.required = false;
    }
    shape.lints = vec![
        "invalid_facet_shape",
        "invalid_standard_method",
        "duplicate_custom_method",
    ];
    shape
}

fn property_facet_patch_shape() -> ConfigShape {
    let mut shape = property_shape();
    shape.name = "property_facet_patch";
    shape.path_pattern = ".appfw/model/_facets/*.yaml object without props";
    shape.shape = "object";
    shape.purpose = "Declares a reusable property patch applied by a named property facet.";
    shape.lints = vec![
        "invalid_facet_shape",
        "missing_data_type",
        "missing_enum_type",
        "missing_fragment",
    ];
    shape
}

fn schema_shape() -> ConfigShape {
    ConfigShape {
        name: "schema",
        path_pattern: ".appfw/model/schemas/<schema>/_res.yaml",
        shape: "object",
        purpose: "Declares one generated schema and its backing data source.",
        fields: vec![
            field("id", "uuid", true, None, &[], "Stable schema id."),
            field(
                "name",
                "string",
                true,
                None,
                &[],
                "Schema name. Must match the directory.",
            ),
            field(
                "description",
                "string",
                true,
                None,
                &[],
                "Human-readable description.",
            ),
            field(
                "data_source_name",
                "string",
                true,
                None,
                &[],
                "Name from data_source config.",
            ),
            field(
                "meta",
                "json",
                false,
                None,
                &["classification", "data_classification", "projection_of"],
                "Governance metadata. Regulated schemas inherit data-source classification unless this overrides it. SaaS/materialized projections may use `meta.projection_of` to name the external source schema.",
            ),
        ],
        lints: vec![
            "schema_name_mismatch",
            "missing_data_source",
            "duplicate_schema",
            "missing_data_classification",
            "invalid_data_classification",
        ],
    }
}

fn sync_descriptor_shape() -> ConfigShape {
    ConfigShape {
        name: "sync_descriptor",
        path_pattern: ".appfw/model/sync/*.yaml",
        shape: "object",
        purpose: "Declares a model-owned SaaS sync worker contract from a named external source projection into an app-owned target projection schema.",
        fields: vec![
            field(
                "name",
                "string",
                true,
                None,
                &[],
                "Stable sync descriptor name. Must match the file stem.",
            ),
            field(
                "source_schema",
                "string",
                true,
                None,
                &[],
                "External SaaS source schema/projection name. This is contract metadata until SaaS schema-pack parsing lands.",
            ),
            field(
                "target_schema",
                "string",
                true,
                None,
                &[],
                "App-owned projection schema written by the sync worker.",
            ),
            field(
                "mode",
                "enum",
                true,
                None,
                &["incremental_watermark", "cdc_event"],
                "Sync mode. `incremental_watermark` emits polling checkpoints; `cdc_event` emits fail-closed Kafka CDC plans with offset checkpoints.",
            ),
            field(
                "schedule",
                "string",
                true,
                None,
                &[],
                "Schedule expression owned by generated sync worker deployment.",
            ),
            field(
                "freshness_slo",
                "string",
                true,
                None,
                &[],
                "ISO-8601 duration such as `PT10M` for sync lag reporting.",
            ),
            field(
                "objects",
                "array<sync_object_map>",
                true,
                None,
                &[],
                "Object mappings from source SaaS objects to target app entities.",
            ),
            field(
                "governance",
                "sync_governance",
                true,
                None,
                &[],
                "Classification, retention, deletion, and source-drift policy for materialized SaaS data.",
            ),
        ],
        lints: vec![
            "invalid_sync_descriptor_yaml",
            "sync_descriptor_name_mismatch",
            "duplicate_sync_descriptor",
            "missing_sync_objects",
            "sync_descriptor_unknown_target_schema",
            "sync_descriptor_target_schema_external_read_only",
        ],
    }
}

fn sync_object_map_shape() -> ConfigShape {
    ConfigShape {
        name: "sync_object_map",
        path_pattern: ".appfw/model/sync/*.yaml $.objects[]",
        shape: "object",
        purpose: "Maps one SaaS source object into one projection entity for generated sync worker planning.",
        fields: vec![
            field("source", "string", true, None, &[], "Source SaaS object name owned by the provider registry."),
            field("target", "string", true, None, &[], "Target app entity name in the projection schema."),
            field("key", "string", true, None, &[], "Stable source key field used for idempotent upserts."),
            field("watermark", "string", true, None, &[], "Source field used for incremental watermark polling or CDC replay/offset tracking."),
            field(
                "provenance",
                "sync_object_provenance",
                true,
                None,
                &[],
                "Per-record lineage contract for the source projection, key, watermark, and optional origin marker.",
            ),
            field(
                "echo_loop",
                "sync_object_echo_loop",
                true,
                None,
                &[],
                "Self-origin rejection contract that prevents app-emitted SaaS records from re-materializing into the projection.",
            ),
        ],
        lints: vec![
            "missing_sync_object_source",
            "missing_sync_object_target",
            "missing_sync_object_key",
            "missing_sync_object_watermark",
            "missing_sync_object_provenance",
            "missing_sync_object_echo_loop",
            "sync_source_key_field_mismatch",
            "sync_source_watermark_field_mismatch",
            "invalid_sync_echo_loop_policy",
        ],
    }
}

fn sync_object_provenance_shape() -> ConfigShape {
    ConfigShape {
        name: "sync_object_provenance",
        path_pattern: ".appfw/model/sync/*.yaml $.objects[].provenance",
        shape: "object",
        purpose: "Declares per-record source lineage for a materialized SaaS object.",
        fields: vec![
            field(
                "projection_of",
                "string",
                true,
                None,
                &[],
                "Stable source projection name such as `salesforce_crm_v1.Account`.",
            ),
            field(
                "source_key_field",
                "string",
                true,
                None,
                &[],
                "Source key field. Must match the object map `key`.",
            ),
            field(
                "source_watermark_field",
                "string",
                true,
                None,
                &[],
                "Source watermark field. Must match the object map `watermark`.",
            ),
            field(
                "source_origin_field",
                "string",
                false,
                None,
                &[],
                "Source field carrying the origin marker when the SaaS API supports echo-loop filtering.",
            ),
        ],
        lints: vec![
            "missing_sync_projection_of",
            "missing_sync_source_key_field",
            "missing_sync_source_watermark_field",
            "sync_source_key_field_mismatch",
            "sync_source_watermark_field_mismatch",
        ],
    }
}

fn sync_object_echo_loop_shape() -> ConfigShape {
    ConfigShape {
        name: "sync_object_echo_loop",
        path_pattern: ".appfw/model/sync/*.yaml $.objects[].echo_loop",
        shape: "object",
        purpose: "Declares how generated sync workers detect records emitted by this app and reject them before materialization.",
        fields: vec![
            field(
                "policy",
                "enum",
                true,
                None,
                &["reject_self_origin"],
                "Echo-loop policy. The first supported policy is fail-closed self-origin rejection.",
            ),
            field(
                "local_origin",
                "string",
                true,
                None,
                &[],
                "Stable origin marker written by this app when it writes back to the SaaS system.",
            ),
            field(
                "source_origin_field",
                "string",
                true,
                None,
                &[],
                "Source field carrying the origin marker.",
            ),
        ],
        lints: vec![
            "missing_sync_echo_loop_policy",
            "missing_sync_echo_loop_local_origin",
            "missing_sync_echo_loop_source_origin_field",
            "invalid_sync_echo_loop_policy",
        ],
    }
}

fn sync_governance_shape() -> ConfigShape {
    ConfigShape {
        name: "sync_governance",
        path_pattern: ".appfw/model/sync/*.yaml $.governance",
        shape: "object",
        purpose: "Declares governance controls required before SaaS data can be materialized into an app-owned projection.",
        fields: vec![
            field(
                "classification",
                "enum",
                true,
                None,
                &[
                    "public",
                    "internal",
                    "confidential",
                    "restricted",
                    "secret",
                    "sensitive",
                    "phi",
                    "ephi",
                ],
                "Data classification for materialized sync data.",
            ),
            field(
                "retention",
                "string",
                false,
                None,
                &[],
                "Retention period such as `P2Y`; required for regulated classifications.",
            ),
            field(
                "deletion",
                "enum",
                true,
                None,
                &["tombstone", "hard_delete", "ignore"],
                "How source deletes are reflected in the target projection.",
            ),
            field(
                "source_drift",
                "enum",
                true,
                None,
                &["fail_closed", "warn", "ignore"],
                "How generated sync infrastructure reacts when provider/schema evidence drifts.",
            ),
        ],
        lints: vec![
            "missing_data_classification",
            "invalid_data_classification",
            "missing_retention_policy",
            "missing_deletion_policy",
            "invalid_deletion_policy",
            "missing_source_drift_policy",
            "invalid_source_drift_policy",
        ],
    }
}

fn enum_type_shape() -> ConfigShape {
    ConfigShape {
        name: "enum_type",
        path_pattern: ".appfw/model/schemas/<schema>/gql_enum_types/*.yaml",
        shape: "array<object>",
        purpose: "Declares GraphQL enum types.",
        fields: vec![
            field("name", "string", true, None, &[], "Enum type name."),
            field("items", "array<enum_item>", true, None, &[], "Enum values."),
        ],
        lints: vec!["duplicate_enum_type", "empty_enum_items"],
    }
}

fn enum_item_shape() -> ConfigShape {
    ConfigShape {
        name: "enum_item",
        path_pattern: ".appfw/model/schemas/<schema>/gql_enum_types/*.yaml $.items[]",
        shape: "object",
        purpose: "Declares one enum value.",
        fields: vec![
            field("value", "string", true, None, &[], "Enum value."),
            field("caption", "string", false, None, &[], "Display caption."),
        ],
        lints: vec!["duplicate_enum_item"],
    }
}

fn relationship_shape() -> ConfigShape {
    ConfigShape {
        name: "relationship",
        path_pattern: ".appfw/model/schemas/<schema>/relationships/*.yaml",
        shape: "array<object>",
        purpose: "Declares canonical schema-level relationships. app_gen projects these into directional relationship fields on entity types.",
        fields: vec![
            field("name", "string", true, None, &[], "Unique relationship name within the schema."),
            field(
                "kind",
                "enum",
                true,
                None,
                &["OneToOne", "OneToMany", "ManyToMany"],
                "Relationship cardinality.",
            ),
            field(
                "left",
                "relationship_endpoint",
                false,
                None,
                &[],
                "Endpoint used by OneToOne and ManyToMany relationships.",
            ),
            field(
                "right",
                "relationship_endpoint",
                false,
                None,
                &[],
                "Endpoint used by OneToOne and ManyToMany relationships.",
            ),
            field(
                "one",
                "relationship_endpoint",
                false,
                None,
                &[],
                "One-side endpoint used by OneToMany relationships.",
            ),
            field(
                "many",
                "relationship_endpoint",
                false,
                None,
                &[],
                "Many-side endpoint used by OneToMany relationships.",
            ),
            field(
                "storage",
                "relationship_storage",
                false,
                None,
                &[],
                "Foreign-key storage metadata for OneToOne and OneToMany relationships.",
            ),
            field(
                "junction",
                "relationship_junction",
                false,
                None,
                &[],
                "Junction metadata for ManyToMany relationships.",
            ),
        ],
        lints: vec![
            "duplicate_relationship",
            "missing_relationship_endpoint_entity",
            "relationship_field_conflicts_with_native_property",
            "relationship_storage_target_mismatch",
        ],
    }
}

fn relationship_endpoint_shape() -> ConfigShape {
    ConfigShape {
        name: "relationship_endpoint",
        path_pattern: "relationship endpoint object",
        shape: "object",
        purpose: "Names one side of a schema-level relationship and the directional field generated on that entity.",
        fields: vec![
            field(
                "schema",
                "string",
                false,
                Some("current schema"),
                &[],
                "Endpoint schema.",
            ),
            field("entity", "string", true, None, &[], "Endpoint entity type."),
            field(
                "field",
                "string",
                true,
                None,
                &[],
                "Directional relationship field generated on this entity.",
            ),
            field("caption", "string", false, None, &[], "Display caption."),
        ],
        lints: vec![],
    }
}

fn relationship_storage_shape() -> ConfigShape {
    ConfigShape {
        name: "relationship_storage",
        path_pattern: "relationship.storage",
        shape: "object",
        purpose: "Declares the physical storage backing a OneToOne or OneToMany relationship.",
        fields: vec![
            field(
                "type",
                "enum",
                true,
                None,
                &["ForeignKey"],
                "Relationship storage kind.",
            ),
            field(
                "owner_schema",
                "string",
                false,
                Some("current schema"),
                &[],
                "Schema of the FK-owning entity.",
            ),
            field("owner", "string", true, None, &[], "FK-owning entity."),
            field(
                "field",
                "string",
                true,
                None,
                &[],
                "Scalar foreign-key property on the owner entity.",
            ),
        ],
        lints: vec![],
    }
}

fn relationship_junction_shape() -> ConfigShape {
    ConfigShape {
        name: "relationship_junction",
        path_pattern: "relationship.junction",
        shape: "object",
        purpose: "Declares the junction backing a ManyToMany relationship.",
        fields: vec![
            field(
                "schema",
                "string",
                false,
                Some("current schema"),
                &[],
                "Junction schema.",
            ),
            field(
                "entity",
                "string",
                true,
                None,
                &[],
                "Junction entity/table name.",
            ),
            field(
                "left_key",
                "string",
                true,
                None,
                &[],
                "Junction column pointing at the left endpoint.",
            ),
            field(
                "right_key",
                "string",
                true,
                None,
                &[],
                "Junction column pointing at the right endpoint.",
            ),
        ],
        lints: vec![],
    }
}

fn entity_type_shape() -> ConfigShape {
    ConfigShape {
        name: "entity_type",
        path_pattern: ".appfw/model/schemas/<schema>/entity_types/*.yaml",
        shape: "array<object>",
        purpose: "Declares generated domain/entity types.",
        fields: vec![
            field("id", "uuid", true, None, &[], "Stable entity id."),
            field(
                "name",
                "string",
                true,
                None,
                &[],
                "Source name for generated inflections.",
            ),
            field("caption", "string", false, None, &[], "Display caption."),
            field(
                "pascal_1",
                "string",
                false,
                Some("inflected from name"),
                &[],
                "Singular type name.",
            ),
            field(
                "pascal_n",
                "string",
                false,
                Some("inflected from name"),
                &[],
                "Plural type name.",
            ),
            field(
                "snake_1",
                "string",
                false,
                Some("inflected from name"),
                &[],
                "Singular code identifier.",
            ),
            field(
                "snake_n",
                "string",
                false,
                Some("inflected from name"),
                &[],
                "Plural code identifier.",
            ),
            field(
                "caption_1",
                "string",
                false,
                Some("inflected from name"),
                &[],
                "Singular caption.",
            ),
            field(
                "caption_n",
                "string",
                false,
                Some("inflected from name"),
                &[],
                "Plural caption.",
            ),
            field(
                "is_table",
                "boolean",
                false,
                Some("false"),
                &[],
                "Whether storage/table code is generated.",
            ),
            field(
                "is_union",
                "boolean",
                false,
                Some("false"),
                &[],
                "Whether this type is a union/base type.",
            ),
            field(
                "base_type",
                "string",
                false,
                None,
                &[],
                "Base union entity type.",
            ),
            field(
                "facets",
                "array<string>",
                false,
                Some("[]"),
                &["audited", "concurrency", "soft-deleted"],
                "`audited` enables per-entity append-only audit events; `concurrency` adds optimistic locking; `soft-deleted` adds soft delete metadata.",
            ),
            field(
                "indexes",
                "array<string>",
                false,
                Some("[]"),
                &[],
                "Property names to index.",
            ),
            field(
                "constraints",
                "array<object>",
                false,
                Some("[]"),
                &[],
                "Reserved constraint metadata.",
            ),
            field(
                "meta",
                "object",
                false,
                None,
                &["classification", "data_classification", "projection_of"],
                "Additional metadata. Regulated entities inherit schema/data-source classification unless this overrides it. SaaS/materialized projection entities may use `meta.projection_of` to name the source object.",
            ),
            field(
                "execution",
                "data_access_execution",
                false,
                Some("provider defaults"),
                &[],
                "Generated data-access execution policy for standard CRUD/query SQL.",
            ),
            field(
                "standard_methods",
                "array<enum>",
                false,
                Some("all methods for tables"),
                &["FindById", "GetAll", "Query", "Create", "Update", "Delete"],
                "Generated CRUD/query methods.",
            ),
            field(
                "custom_methods",
                "array<custom_method>",
                false,
                None,
                &[],
                "Custom generated method declarations.",
            ),
            field(
                "props",
                "array<property>",
                true,
                None,
                &[],
                "Entity properties.",
            ),
        ],
        lints: vec![
            "duplicate_entity_type",
            "duplicate_entity_id",
            "invalid_standard_method",
            "missing_base_type",
            "missing_index_property",
            "audited_facet_on_non_table",
            "audited_entity_missing_key",
            "missing_data_classification",
            "invalid_data_classification",
        ],
    }
}

fn data_access_execution_shape() -> ConfigShape {
    ConfigShape {
        name: "data_access_execution",
        path_pattern: "entity_type.execution",
        shape: "object",
        purpose: "Generated data-access execution policy for standard CRUD/query SQL.",
        fields: vec![field(
            "prepared_statements",
            "boolean",
            false,
            Some("false"),
            &[],
            "Use provider-owned prepared/cached statement execution for generated read/query SQL where supported.",
        )],
        lints: vec![],
    }
}

fn property_shape() -> ConfigShape {
    ConfigShape {
        name: "property",
        path_pattern: ".appfw/model/schemas/<schema>/entity_types/*.yaml $.props[]",
        shape: "object",
        purpose: "Declares one entity property. Fragments may provide defaults.",
        fields: vec![
            field(
                "id",
                "string",
                false,
                Some("stable hash"),
                &[],
                "Stable property id.",
            ),
            field("name", "string", true, None, &[], "Property name."),
            field(
                "caption",
                "string",
                false,
                Some("inflected from name"),
                &[],
                "Display caption.",
            ),
            field(
                "is_key",
                "boolean",
                false,
                Some("false"),
                &[],
                "Primary key marker.",
            ),
            field(
                "is_caption",
                "boolean",
                false,
                Some("false"),
                &[],
                "Record caption marker.",
            ),
            field(
                "is_required",
                "boolean",
                false,
                Some("false"),
                &[],
                "Required value marker.",
            ),
            field(
                "is_read_only",
                "boolean",
                false,
                Some("false"),
                &[],
                "Read-only marker.",
            ),
            field(
                "is_concurrency_control",
                "boolean",
                false,
                Some("false"),
                &[],
                "Optimistic concurrency marker.",
            ),
            field(
                "data_type",
                "enum",
                false,
                Some("from fragment"),
                data_types(),
                "Property data type. Product-authored entity config should use scalar, enum, object, or JSON data types; navigation fields are generated from schema-level relationships. ManyToMany is a relationship kind/junction strategy, not a product-authored entity property type.",
            ),
            field(
                "computed",
                "enum",
                false,
                Some("None"),
                &[
                    "Concatenate",
                    "Format",
                    "Word",
                    "Inflection",
                    "DateTimeNow",
                    "None",
                ],
                "Computed behavior.",
            ),
            field("default_value", "json", false, None, &[], "Default value."),
            field(
                "foreign_key",
                "foreign_key",
                false,
                None,
                &[],
                "Foreign-key target for scalar storage properties. Navigation is declared in schema-level relationships.",
            ),
            field(
                "nav_by_fk_property",
                "nav_by_fk_property",
                false,
                None,
                &[],
                "Generated navigation relationship via a foreign key. Do not hand-author in product entity config; define a schema-level relationship instead.",
            ),
            field(
                "many_to_many_property",
                "many_to_many_property",
                false,
                None,
                &[],
                "Generated junction metadata for to-many navigation fields. Do not hand-author in product entity config; define a schema-level relationship instead.",
            ),
            field(
                "nested_entity_type",
                "nested_entity_type",
                false,
                None,
                &[],
                "Nested object type.",
            ),
            field(
                "enum_type_name",
                "string",
                false,
                None,
                &[],
                "Enum type backing Enum/EnumArray.",
            ),
            field(
                "meta",
                "json",
                false,
                None,
                &[
                    "classification",
                    "data_classification",
                    "audit.redact",
                    "audit.classification",
                    "source_field",
                ],
                "Additional metadata. Use `meta.audit.redact: true` to replace property values in audit before/after/diff payloads. SaaS/materialized projection properties may use `meta.source_field` to name the external source field. Regulated properties inherit entity/schema/data-source classification unless this overrides it.",
            ),
            field(
                "fragment",
                "string",
                false,
                None,
                &[],
                "Fragment file stem from .appfw/model/_fragments.",
            ),
            field(
                "type_variant",
                "boolean",
                false,
                Some("false"),
                &[],
                "Union variant discriminator shortcut.",
            ),
        ],
        lints: vec![
            "missing_fragment",
            "missing_data_type",
            "missing_enum_type",
            "invalid_nav_data_type",
            "invalid_many_to_many_data_type",
            "relationship_property_requires_schema_relationship",
            "missing_data_classification",
            "invalid_data_classification",
        ],
    }
}

fn foreign_key_shape() -> ConfigShape {
    relation_shape("foreign_key", "Property scalar foreign-key metadata.")
}

fn nested_entity_shape() -> ConfigShape {
    relation_shape("nested_entity_type", "Property nested entity metadata.")
}

fn relation_shape(name: &'static str, purpose: &'static str) -> ConfigShape {
    ConfigShape {
        name,
        path_pattern: "inline property object",
        shape: "object",
        purpose,
        fields: vec![
            field(
                "schema_name",
                "string",
                false,
                Some("current schema"),
                &[],
                "Referenced schema.",
            ),
            field(
                "type_name",
                "string",
                true,
                None,
                &[],
                "Referenced entity type.",
            ),
        ],
        lints: vec![],
    }
}

fn nav_by_fk_shape() -> ConfigShape {
    ConfigShape {
        name: "nav_by_fk_property",
        path_pattern: "inline property object",
        shape: "object",
        purpose: "Navigation relationship resolved through a scalar FK property.",
        fields: vec![
            field(
                "schema_name",
                "string",
                false,
                Some("current schema"),
                &[],
                "Entity schema.",
            ),
            field(
                "type_name",
                "string",
                false,
                Some("current entity"),
                &[],
                "Entity type containing prop_name.",
            ),
            field(
                "prop_name",
                "string",
                true,
                None,
                &[],
                "Foreign-key property name.",
            ),
            field(
                "filter",
                "json",
                false,
                None,
                &[],
                "Optional navigation filter.",
            ),
            field(
                "resolved",
                "foreign_key",
                false,
                Some("generated"),
                &[],
                "Generated relationship cache.",
            ),
        ],
        lints: vec!["missing_navigation_target", "missing_navigation_property"],
    }
}

fn many_to_many_shape() -> ConfigShape {
    ConfigShape {
        name: "many_to_many_property",
        path_pattern: "inline property object",
        shape: "object",
        purpose: "Many-to-many relationship through a junction table/entity.",
        fields: vec![
            field(
                "junction_table",
                "string",
                true,
                None,
                &[],
                "Junction entity/table name.",
            ),
            field(
                "junction_schema",
                "string",
                false,
                Some("current schema"),
                &[],
                "Junction schema.",
            ),
            field(
                "local_key",
                "string",
                true,
                None,
                &[],
                "Junction column pointing to local entity.",
            ),
            field(
                "foreign_key",
                "string",
                true,
                None,
                &[],
                "Junction column pointing to target entity.",
            ),
            field(
                "target_schema",
                "string",
                true,
                None,
                &[],
                "Target entity schema.",
            ),
            field(
                "target_type",
                "string",
                true,
                None,
                &[],
                "Target entity type.",
            ),
        ],
        lints: vec!["missing_many_to_many_target", "missing_junction_property"],
    }
}

fn custom_method_shape() -> ConfigShape {
    ConfigShape {
        name: "custom_method",
        path_pattern: "entity_type.custom_methods[]",
        shape: "object",
        purpose: "Custom generated method declaration.",
        fields: vec![
            field("name", "string", true, None, &[], "Method name."),
            field(
                "kind",
                "enum",
                true,
                None,
                &["Query", "Mutation", "Command"],
                "Method kind.",
            ),
            field(
                "args",
                "array<custom_method_arg>",
                true,
                Some("[]"),
                &[],
                "Method arguments.",
            ),
            field(
                "return_type",
                "string",
                true,
                None,
                &[],
                "Rust return type.",
            ),
            field(
                "mcp_enabled",
                "boolean",
                false,
                Some("false"),
                &[],
                "Expose this app-defined method through MCP operation discovery. Mutations still require write-safety certification before they can be called.",
            ),
            field(
                "provider_routine",
                "provider_routine",
                false,
                None,
                &[],
                "Optional generated provider-routine binding. Use for vetted database functions/procedures invoked through the provider boundary, not for ad hoc SQL.",
            ),
        ],
        lints: vec![
            "duplicate_custom_method",
            "duplicate_custom_method_arg",
            "invalid_provider_routine",
            "unsafe_provider_routine_identifier",
        ],
    }
}

fn custom_method_arg_shape() -> ConfigShape {
    ConfigShape {
        name: "custom_method_arg",
        path_pattern: "custom_method.args[]",
        shape: "object",
        purpose: "Custom method argument declaration.",
        fields: vec![
            field("name", "string", true, None, &[], "Argument name."),
            field("arg_type", "string", true, None, &[], "Rust argument type."),
        ],
        lints: vec![],
    }
}

fn provider_routine_shape() -> ConfigShape {
    ConfigShape {
        name: "provider_routine",
        path_pattern: "custom_method.provider_routine",
        shape: "object",
        purpose: "Binds a custom method to a vetted provider-native routine without exposing SQL in product handlers.",
        fields: vec![
            field(
                "kind",
                "enum",
                true,
                None,
                &["Function", "Procedure"],
                "Provider routine kind. Queries must use Function; procedures are intended for mutations/commands.",
            ),
            field(
                "returns",
                "enum",
                true,
                None,
                &["None", "One", "Many"],
                "Generated result shape. Functions and procedures can return one DTO, many DTOs, or no payload when the provider routine supports that shape.",
            ),
            field(
                "data_source",
                "string",
                false,
                Some("entity schema data source"),
                &[],
                "Optional data source name expected at runtime.",
            ),
            field(
                "schema",
                "string",
                false,
                None,
                &[],
                "Portable routine schema/catalog namespace inherited by supported providers unless overridden.",
            ),
            field(
                "name",
                "string",
                false,
                None,
                &[],
                "Portable routine name inherited by supported providers unless overridden.",
            ),
            field(
                "routines",
                "provider_routine_names",
                false,
                Some("portable schema/name target"),
                &[],
                "Optional provider-specific routine overrides for naming drift. Use only when a provider cannot use the portable schema/name target.",
            ),
        ],
        lints: vec![
            "missing_provider_routine",
            "invalid_provider_routine_kind",
        ],
    }
}

fn provider_routine_names_shape() -> ConfigShape {
    ConfigShape {
        name: "provider_routine_names",
        path_pattern: "provider_routine.routines",
        shape: "object",
        purpose: "Provider-specific routine map for PostgreSQL, MS SQL Server, and Snowflake.",
        fields: vec![
            field(
                "postgres",
                "provider_routine_name",
                false,
                None,
                &[],
                "PostgreSQL function/procedure name.",
            ),
            field(
                "mssql",
                "provider_routine_name",
                false,
                None,
                &[],
                "MS SQL Server stored procedure/function name.",
            ),
            field(
                "snowflake",
                "provider_routine_name",
                false,
                None,
                &[],
                "Snowflake stored procedure/function name.",
            ),
        ],
        lints: vec!["unknown_provider_routine", "missing_provider_routine"],
    }
}

fn provider_routine_name_shape() -> ConfigShape {
    ConfigShape {
        name: "provider_routine_name",
        path_pattern: "provider_routine.routines.<provider>",
        shape: "object",
        purpose: "Safe provider routine identifier.",
        fields: vec![
            field(
                "schema",
                "string",
                false,
                None,
                &[],
                "Optional provider schema/catalog namespace. Must be a simple ASCII identifier.",
            ),
            field(
                "name",
                "string",
                true,
                None,
                &[],
                "Routine name. Must be a simple ASCII identifier.",
            ),
        ],
        lints: vec!["unsafe_provider_routine_identifier"],
    }
}

fn seed_group_shape() -> ConfigShape {
    ConfigShape {
        name: "seed_group",
        path_pattern: ".appfw/model/schemas/<schema>/seeds/*.yaml",
        shape: "array<object>",
        purpose: "Seed data grouped by entity or junction table.",
        fields: vec![
            field(
                "entity_type",
                "string",
                true,
                None,
                &[],
                "Entity or junction name.",
            ),
            field(
                "schema",
                "string",
                false,
                Some("current schema"),
                &[],
                "Entity schema.",
            ),
            field(
                "columns",
                "array<string>",
                true,
                None,
                &[],
                "Stored columns emitted in seeds.",
            ),
            field("records", "array<object>", true, None, &[], "Seed records."),
        ],
        lints: vec![
            "missing_seed_entity",
            "invalid_seed_column",
            "seed_record_key_not_in_columns",
        ],
    }
}

fn api_test_shape() -> ConfigShape {
    ConfigShape {
        name: "api_test",
        path_pattern: ".appfw/model/schemas/<schema>/tests/*.yaml",
        shape: "array<object>",
        purpose: "Generated API test declarations.",
        fields: vec![
            field("name", "string", true, None, &[], "Test name."),
            field(
                "description",
                "string",
                false,
                None,
                &[],
                "Human-readable description.",
            ),
            field(
                "auth_token",
                "string",
                false,
                None,
                &[],
                "Named auth token.",
            ),
            field(
                "graphql",
                "object",
                false,
                None,
                &[],
                "GraphQL operation declaration.",
            ),
            field(
                "expect",
                "object",
                false,
                None,
                &[],
                "Expected data or error.",
            ),
            field(
                "result_object_name",
                "string",
                false,
                None,
                &[],
                "Named result binding.",
            ),
        ],
        lints: vec!["missing_test_schema", "invalid_graphql_operation_type"],
    }
}

fn field(
    name: &'static str,
    value_type: &'static str,
    required: bool,
    default: Option<&'static str>,
    allowed_values: &[&'static str],
    purpose: &'static str,
) -> ConfigField {
    ConfigField {
        name,
        value_type,
        required,
        default,
        allowed_values: allowed_values.to_vec(),
        purpose,
    }
}

fn data_types() -> &'static [&'static str] {
    &[
        "Uuid",
        "UuidArray",
        "ObjectId",
        "ObjectIdArray",
        "Boolean",
        "String",
        "StringArray",
        "Date",
        "DateTime",
        "Time",
        "Int8",
        "Int8Array",
        "Int16",
        "Int16Array",
        "Int32",
        "Int32Array",
        "Int64",
        "Int64Array",
        "Float32",
        "Float64",
        "Enum",
        "EnumArray",
        "Object",
        "ObjectArray",
        "Json",
        "JsonArray",
        "NavToOne",
        "NavToMany",
        "ManyToMany",
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn contract_includes_reusable_config_shapes() {
        let contract = contract();

        for shape_name in [
            "property_fragment",
            "entity_facet_patch",
            "property_facet_patch",
        ] {
            assert!(
                contract.shapes.contains_key(shape_name),
                "missing config contract shape `{shape_name}`"
            );
        }
    }

    #[test]
    fn property_fragment_name_is_optional() {
        let contract = contract();
        let required = contract
            .shapes
            .get("property_fragment")
            .and_then(|shape| shape.fields.iter().find(|field| field.name == "name"))
            .map(|field| field.required);

        assert_eq!(required, Some(false));
    }

    #[test]
    fn contract_documents_classification_metadata() {
        let contract = contract();

        for shape_name in ["data_source", "schema", "entity_type", "property"] {
            let meta = contract
                .shapes
                .get(shape_name)
                .and_then(|shape| shape.fields.iter().find(|field| field.name == "meta"))
                .unwrap_or_else(|| panic!("missing meta field for {shape_name}"));

            assert!(
                meta.allowed_values.contains(&"classification"),
                "missing classification metadata key for {shape_name}"
            );
        }

        let property_meta = contract
            .shapes
            .get("property")
            .and_then(|shape| shape.fields.iter().find(|field| field.name == "meta"))
            .expect("property meta field");
        assert!(
            property_meta
                .allowed_values
                .contains(&"audit.classification"),
            "property audit classification metadata should remain documented"
        );
    }

    #[test]
    fn contract_documents_saas_projection_and_echo_loop_metadata() {
        let contract = contract();

        for shape_name in ["sync_object_provenance", "sync_object_echo_loop"] {
            assert!(
                contract.shapes.contains_key(shape_name),
                "missing config contract shape `{shape_name}`"
            );
        }

        let entity_meta = contract
            .shapes
            .get("entity_type")
            .and_then(|shape| shape.fields.iter().find(|field| field.name == "meta"))
            .expect("entity meta field");
        assert!(entity_meta.allowed_values.contains(&"projection_of"));

        let property_meta = contract
            .shapes
            .get("property")
            .and_then(|shape| shape.fields.iter().find(|field| field.name == "meta"))
            .expect("property meta field");
        assert!(property_meta.allowed_values.contains(&"source_field"));
    }
}
