[package]
name = "appfw-provider-postgres"
version = "0.2.0"
edition = "2021"
description = "PostgreSQL provider implementation support for App Framework."
publish = ["pds-app-framework-crates"]

[dependencies]
appfw_runtime = { package = "appfw-runtime", version = "0.2.0", path = "../appfw_runtime", registry = "pds-app-framework-crates", default-features = false }
chrono = { version = "0.4", features = ["serde"] }
deadpool-postgres = "0.12"
postgres-types = { version = "0.2", features = ["derive", "with-chrono-0_4", "with-serde_json-1", "with-uuid-1"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "logging", "tls12"] }
rustls-native-certs = "0.8"
rustls-pki-types = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio-postgres = "0.7"
tokio-postgres-rustls = "0.13"
uuid = { version = "1", features = ["serde", "v4"] }
webpki-roots = "1"
