[package]
name = "appfw-provider-anaplan"
version = "0.1.1"
edition = "2021"
description = "Anaplan Integration API provider implementation skeleton for App Framework."
publish = ["pds-app-framework-crates"]

[dependencies]
appfw-saas-core = { version = "0.1.1", path = "../appfw_saas_core", registry = "pds-app-framework-crates" }
serde_json = "1.0"
