//
// Generated by app_gen for crm.
//   - From tests yaml
//

#[cfg(test)]
mod tests {

    use anyhow::Result;
    use serde_json::json;

    use crate::harness::TestContext;

    #[tokio::test]
    async fn test_addresses_scenario() -> Result<()> {
        let mut ctx = TestContext::from_env()?;

        step_find_address(&mut ctx).await?;

        step_find_contact_address(&mut ctx).await?;

        Ok(())
    }

    async fn step_find_address(ctx: &mut TestContext) -> Result<()> {
        // Description: find seeded account address as admin
        println!("*** Test description: find seeded account address as admin ***");

        let req = r#"
      query($id: String!){
        findAddress(id: $id){
            id,name,address_type,city,state,country,is_primary,account { id,name }

        }
      }
    "#;

        let variables = Some(json!({
        "id": "add00000-0000-4000-8000-100000000001"
        }));

        let gql_result = ctx
            .execute_graphql("pdsh_admin", "crm", req, variables)
            .await?;
        println!("find_address GraphQL result: {:?}", gql_result);

        ctx.expect_data(
      "find_address",
      &gql_result,
      "findAddress",
      json!({"id":"add00000-0000-4000-8000-100000000001","name":"Acme Dental Billing","address_type":"Billing","city":"San Francisco","state":"CA","country":"USA","is_primary":true}),
      None,
    )?;

        Ok(())
    }

    async fn step_find_contact_address(ctx: &mut TestContext) -> Result<()> {
        // Description: find seeded contact address as admin
        println!("*** Test description: find seeded contact address as admin ***");

        let req = r#"
      query($id: String!){
        findAddress(id: $id){
            id,name,address_type,city,state,country,contact { id,first_name,last_name }

        }
      }
    "#;

        let variables = Some(json!({
        "id": "add00000-0000-4000-8000-100000000003"
        }));

        let gql_result = ctx
            .execute_graphql("pdsh_admin", "crm", req, variables)
            .await?;
        println!("find_contact_address GraphQL result: {:?}", gql_result);

        ctx.expect_data(
      "find_contact_address",
      &gql_result,
      "findAddress",
      json!({"id":"add00000-0000-4000-8000-100000000003","name":"Maya Johnson Mailing","address_type":"Mailing","city":"Portland","state":"OR"}),
      None,
    )?;

        Ok(())
    }
}
