//
// Generated by app_gen for crm.
//   - From tests yaml
//

#[cfg(test)]
mod tests {

    use anyhow::Result;
    use serde_json::json;

    use crate::harness::TestContext;

    #[tokio::test]
    async fn test_business_units_scenario() -> Result<()> {
        let mut ctx = TestContext::from_env()?;

        step_find_business_unit(&mut ctx).await?;

        Ok(())
    }

    async fn step_find_business_unit(ctx: &mut TestContext) -> Result<()> {
        // Description: find seeded business unit with territories and queues
        println!("*** Test description: find seeded business unit with territories and queues ***");

        let req = r#"
      query($id: String!){
        findBusinessUnit(id: $id){
            id,name,code,region,is_active,territories { id,name },queues { id,name }

        }
      }
    "#;

        let variables = Some(json!({
        "id": "b0510000-0000-4000-8000-100000000001"
        }));

        let gql_result = ctx
            .execute_graphql("pdsh_admin", "crm", req, variables)
            .await?;
        println!("find_business_unit GraphQL result: {:?}", gql_result);

        ctx.expect_data(
      "find_business_unit",
      &gql_result,
      "findBusinessUnit",
      json!({"id":"b0510000-0000-4000-8000-100000000001","name":"West Commercial","code":"WEST-COM","region":"West","is_active":true}),
      None,
    )?;

        Ok(())
    }
}
