//
// Generated by app_gen for crm.
//   - From tests yaml
//

#[cfg(test)]
mod tests {

    use anyhow::Result;
    use serde_json::json;

    use crate::harness::TestContext;

    #[tokio::test]
    async fn test_lead_statuses_scenario() -> Result<()> {
        let mut ctx = TestContext::from_env()?;

        step_find_lead_status(&mut ctx).await?;

        Ok(())
    }

    async fn step_find_lead_status(ctx: &mut TestContext) -> Result<()> {
        // Description: find seeded lead status by id as admin
        println!("*** Test description: find seeded lead status by id as admin ***");

        let req = r#"
      query($id: String!){
        findLeadStatus(id: $id){
            id,name,is_converted,sort_order

        }
      }
    "#;

        let variables = Some(json!({
        "id": "1eadcc00-0000-4000-8000-100000000001"
        }));

        let gql_result = ctx
            .execute_graphql("pdsh_admin", "crm", req, variables)
            .await?;
        println!("find_lead_status GraphQL result: {:?}", gql_result);

        ctx.expect_data(
      "find_lead_status",
      &gql_result,
      "findLeadStatus",
      json!({"id":"1eadcc00-0000-4000-8000-100000000001","name":"New","is_converted":false,"sort_order":10}),
      None,
    )?;

        Ok(())
    }
}
