//
// Generated by app_gen for crm.
//   - From tests yaml
//

#[cfg(test)]
mod tests {

    use anyhow::Result;
    use serde_json::json;

    use crate::harness::TestContext;

    #[tokio::test]
    async fn test_leads_scenario() -> Result<()> {
        let mut ctx = TestContext::from_env()?;

        step_create_lead(&mut ctx).await?;

        step_find_lead(&mut ctx).await?;

        Ok(())
    }

    async fn step_create_lead(ctx: &mut TestContext) -> Result<()> {
        // Description: create lead with multiple FKs as admin
        println!("*** Test description: create lead with multiple FKs as admin ***");

        let req = r#"
      mutation($input: InputLead!){
        createLead(input: $input){
            id,first_name,last_name,company,email,is_converted,status_id,source_id,industry_id,version

        }
      }
    "#;

        let variables = Some(json!({
        "input": {"first_name":"Avery","last_name":"Lopez","company":"Test Lead Co.","email":"avery.lopez@example.com","phone":"555-0210","title":"Director of IT","is_converted":false,"status_id":"1eadcc00-0000-4000-8000-100000000001","source_id":"1eadcc01-0000-4000-8000-100000000001","industry_id":"10100070-0000-4000-8000-100000000002","version":0}
        }));

        let gql_result = ctx
            .execute_graphql("pdsh_admin", "crm", req, variables)
            .await?;
        println!("create_lead GraphQL result: {:?}", gql_result);

        ctx.expect_data(
      "create_lead",
      &gql_result,
      "createLead",
      json!({"first_name":"Avery","last_name":"Lopez","company":"Test Lead Co.","status_id":"1eadcc00-0000-4000-8000-100000000001","source_id":"1eadcc01-0000-4000-8000-100000000001","industry_id":"10100070-0000-4000-8000-100000000002"}),
      Some("create_lead_result"),
    )?;

        Ok(())
    }

    async fn step_find_lead(ctx: &mut TestContext) -> Result<()> {
        // Description: find lead with NavToOne status and source
        println!("*** Test description: find lead with NavToOne status and source ***");

        let req = r#"
      query($id: String!){
        findLead(id: $id){
            id,first_name,last_name,status { id,name },source { id,name },industry { id,name },version

        }
      }
    "#;

        let variables = Some(json!({
        "id": ctx.result_value("create_lead_result.id")?
        }));

        let gql_result = ctx
            .execute_graphql("pdsh_admin", "crm", req, variables)
            .await?;
        println!("find_lead GraphQL result: {:?}", gql_result);

        ctx.expect_data(
            "find_lead",
            &gql_result,
            "findLead",
            json!({"first_name":"Avery","last_name":"Lopez"}),
            Some("find_lead_result"),
        )?;

        Ok(())
    }
}
