//
// Generated by app_gen for crm.
//   - From tests yaml
//

#[cfg(test)]
mod tests {

    use anyhow::Result;
    use serde_json::json;

    use crate::harness::TestContext;

    #[tokio::test]
    async fn test_opportunities_scenario() -> Result<()> {
        let mut ctx = TestContext::from_env()?;

        step_find_opportunity(&mut ctx).await?;

        Ok(())
    }

    async fn step_find_opportunity(ctx: &mut TestContext) -> Result<()> {
        // Description: find seeded opportunity by id as admin
        println!("*** Test description: find seeded opportunity by id as admin ***");

        let req = r#"
      query($id: String!){
        findOpportunity(id: $id){
            id,name,account_id,stage_id,account { id,name },stage { id,name }

        }
      }
    "#;

        let variables = Some(json!({
        "id": "099c0000-0000-4000-8000-100000000001"
        }));

        let gql_result = ctx
            .execute_graphql("pdsh_admin", "crm", req, variables)
            .await?;
        println!("find_opportunity GraphQL result: {:?}", gql_result);

        ctx.expect_data(
      "find_opportunity",
      &gql_result,
      "findOpportunity",
      json!({"id":"099c0000-0000-4000-8000-100000000001","name":"Acme Dental - Enterprise Suite","account_id":"a0c00000-0000-4000-8000-100000000001","stage_id":"0998a900-0000-4000-8000-100000000003"}),
      None,
    )?;

        Ok(())
    }
}
