//
// Generated by app_gen for crm.
//   - From tests yaml
//

#[cfg(test)]
mod tests {

    use anyhow::Result;
    use serde_json::json;

    use crate::harness::TestContext;

    #[tokio::test]
    async fn test_pricebooks_scenario() -> Result<()> {
        let mut ctx = TestContext::from_env()?;

        step_find_pricebook(&mut ctx).await?;

        Ok(())
    }

    async fn step_find_pricebook(ctx: &mut TestContext) -> Result<()> {
        // Description: find seeded pricebook by id as admin
        println!("*** Test description: find seeded pricebook by id as admin ***");

        let req = r#"
      query($id: String!){
        findPricebook(id: $id){
            id,name,is_active,is_standard

        }
      }
    "#;

        let variables = Some(json!({
        "id": "97000b00-0000-4000-8000-100000000001"
        }));

        let gql_result = ctx
            .execute_graphql("pdsh_admin", "crm", req, variables)
            .await?;
        println!("find_pricebook GraphQL result: {:?}", gql_result);

        ctx.expect_data(
      "find_pricebook",
      &gql_result,
      "findPricebook",
      json!({"id":"97000b00-0000-4000-8000-100000000001","name":"Standard Price Book","is_active":true,"is_standard":true}),
      None,
    )?;

        Ok(())
    }
}
