//
// Generated by app_gen for crm.
//   - From tests yaml
//

#[cfg(test)]
mod tests {

    use anyhow::Result;
    use serde_json::json;

    use crate::harness::TestContext;

    #[tokio::test]
    async fn test_products_scenario() -> Result<()> {
        let mut ctx = TestContext::from_env()?;

        step_find_product(&mut ctx).await?;

        Ok(())
    }

    async fn step_find_product(ctx: &mut TestContext) -> Result<()> {
        // Description: find seeded product by id as admin
        println!("*** Test description: find seeded product by id as admin ***");

        let req = r#"
      query($id: String!){
        findProduct(id: $id){
            id,name,product_code,is_active,pricebook_id,pricebook { id,name }

        }
      }
    "#;

        let variables = Some(json!({
        "id": "9700d000-0000-4000-8000-100000000001"
        }));

        let gql_result = ctx
            .execute_graphql("pdsh_admin", "crm", req, variables)
            .await?;
        println!("find_product GraphQL result: {:?}", gql_result);

        ctx.expect_data(
      "find_product",
      &gql_result,
      "findProduct",
      json!({"id":"9700d000-0000-4000-8000-100000000001","name":"Enterprise Suite","product_code":"ENT-001","is_active":true,"pricebook_id":"97000b00-0000-4000-8000-100000000001"}),
      None,
    )?;

        Ok(())
    }
}
