--
--    Generated by app_gen.
--    by app_gen/_templates/database/postgresql/create_tables_sql/_mod.j2
--    Defines storage tables for entity_types.
--

DO $$
BEGIN






    IF EXISTS(SELECT TRUE FROM pg_type where typnamespace = (select oid from pg_catalog.pg_namespace where nspname = 'crm') AND typname = 'accounts')
    THEN
        RAISE NOTICE 'ALTERING table accounts';

        ALTER TABLE crm.accounts ADD COLUMN IF NOT EXISTS "name" varchar;

        ALTER TABLE crm.accounts ADD COLUMN IF NOT EXISTS "website" varchar;

        ALTER TABLE crm.accounts ADD COLUMN IF NOT EXISTS "phone" varchar;

        ALTER TABLE crm.accounts ADD COLUMN IF NOT EXISTS "email" varchar;

        ALTER TABLE crm.accounts ADD COLUMN IF NOT EXISTS "billing_street" varchar;

        ALTER TABLE crm.accounts ADD COLUMN IF NOT EXISTS "billing_city" varchar;

        ALTER TABLE crm.accounts ADD COLUMN IF NOT EXISTS "billing_state" varchar;

        ALTER TABLE crm.accounts ADD COLUMN IF NOT EXISTS "billing_postal_code" varchar;

        ALTER TABLE crm.accounts ADD COLUMN IF NOT EXISTS "billing_country" varchar;

        ALTER TABLE crm.accounts ADD COLUMN IF NOT EXISTS "annual_revenue" double precision;

        ALTER TABLE crm.accounts ADD COLUMN IF NOT EXISTS "number_of_employees" integer;

        ALTER TABLE crm.accounts ADD COLUMN IF NOT EXISTS "description" varchar;

        ALTER TABLE crm.accounts ADD COLUMN IF NOT EXISTS "industry_id" uuid;

        ALTER TABLE crm.accounts ADD COLUMN IF NOT EXISTS "version" bigint;

    ELSE
        RAISE NOTICE 'CREATING, table accounts';
        CREATE TABLE crm.accounts
        (
            "id" uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY
            ,"name" varchar
            ,"website" varchar
            ,"phone" varchar
            ,"email" varchar
            ,"billing_street" varchar
            ,"billing_city" varchar
            ,"billing_state" varchar
            ,"billing_postal_code" varchar
            ,"billing_country" varchar
            ,"annual_revenue" double precision
            ,"number_of_employees" integer
            ,"description" varchar
            ,"industry_id" uuid
            ,"version" bigint
        );
    END IF;

    IF EXISTS(SELECT TRUE FROM pg_type where typnamespace = (select oid from pg_catalog.pg_namespace where nspname = 'crm') AND typname = 'activities')
    THEN
        RAISE NOTICE 'ALTERING table activities';

        ALTER TABLE crm.activities ADD COLUMN IF NOT EXISTS "subject" varchar;

        ALTER TABLE crm.activities ADD COLUMN IF NOT EXISTS "description" varchar;

        ALTER TABLE crm.activities ADD COLUMN IF NOT EXISTS "activity_date" date;

        ALTER TABLE crm.activities ADD COLUMN IF NOT EXISTS "due_date" date;

        ALTER TABLE crm.activities ADD COLUMN IF NOT EXISTS "is_closed" boolean;

        ALTER TABLE crm.activities ADD COLUMN IF NOT EXISTS "priority" varchar;

        ALTER TABLE crm.activities ADD COLUMN IF NOT EXISTS "status" varchar;

        ALTER TABLE crm.activities ADD COLUMN IF NOT EXISTS "type_id" uuid;

        ALTER TABLE crm.activities ADD COLUMN IF NOT EXISTS "account_id" uuid;

        ALTER TABLE crm.activities ADD COLUMN IF NOT EXISTS "contact_id" uuid;

        ALTER TABLE crm.activities ADD COLUMN IF NOT EXISTS "opportunity_id" uuid;

        ALTER TABLE crm.activities ADD COLUMN IF NOT EXISTS "lead_id" uuid;

        ALTER TABLE crm.activities ADD COLUMN IF NOT EXISTS "version" bigint;

    ELSE
        RAISE NOTICE 'CREATING, table activities';
        CREATE TABLE crm.activities
        (
            "id" uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY
            ,"subject" varchar
            ,"description" varchar
            ,"activity_date" date
            ,"due_date" date
            ,"is_closed" boolean
            ,"priority" varchar
            ,"status" varchar
            ,"type_id" uuid
            ,"account_id" uuid
            ,"contact_id" uuid
            ,"opportunity_id" uuid
            ,"lead_id" uuid
            ,"version" bigint
        );
    END IF;

    IF EXISTS(SELECT TRUE FROM pg_type where typnamespace = (select oid from pg_catalog.pg_namespace where nspname = 'crm') AND typname = 'activity_types')
    THEN
        RAISE NOTICE 'ALTERING table activity_types';

        ALTER TABLE crm.activity_types ADD COLUMN IF NOT EXISTS "name" varchar;

        ALTER TABLE crm.activity_types ADD COLUMN IF NOT EXISTS "sort_order" smallint;

        ALTER TABLE crm.activity_types ADD COLUMN IF NOT EXISTS "version" bigint;

    ELSE
        RAISE NOTICE 'CREATING, table activity_types';
        CREATE TABLE crm.activity_types
        (
            "id" uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY
            ,"name" varchar
            ,"sort_order" smallint
            ,"version" bigint
        );
    END IF;

    IF EXISTS(SELECT TRUE FROM pg_type where typnamespace = (select oid from pg_catalog.pg_namespace where nspname = 'crm') AND typname = 'contacts')
    THEN
        RAISE NOTICE 'ALTERING table contacts';

        ALTER TABLE crm.contacts ADD COLUMN IF NOT EXISTS "first_name" varchar;

        ALTER TABLE crm.contacts ADD COLUMN IF NOT EXISTS "last_name" varchar;

        ALTER TABLE crm.contacts ADD COLUMN IF NOT EXISTS "email" varchar;

        ALTER TABLE crm.contacts ADD COLUMN IF NOT EXISTS "phone" varchar;

        ALTER TABLE crm.contacts ADD COLUMN IF NOT EXISTS "mobile" varchar;

        ALTER TABLE crm.contacts ADD COLUMN IF NOT EXISTS "title" varchar;

        ALTER TABLE crm.contacts ADD COLUMN IF NOT EXISTS "department" varchar;

        ALTER TABLE crm.contacts ADD COLUMN IF NOT EXISTS "mailing_street" varchar;

        ALTER TABLE crm.contacts ADD COLUMN IF NOT EXISTS "mailing_city" varchar;

        ALTER TABLE crm.contacts ADD COLUMN IF NOT EXISTS "mailing_state" varchar;

        ALTER TABLE crm.contacts ADD COLUMN IF NOT EXISTS "mailing_postal_code" varchar;

        ALTER TABLE crm.contacts ADD COLUMN IF NOT EXISTS "mailing_country" varchar;

        ALTER TABLE crm.contacts ADD COLUMN IF NOT EXISTS "account_id" uuid;

        ALTER TABLE crm.contacts ADD COLUMN IF NOT EXISTS "version" bigint;

    ELSE
        RAISE NOTICE 'CREATING, table contacts';
        CREATE TABLE crm.contacts
        (
            "id" uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY
            ,"first_name" varchar
            ,"last_name" varchar
            ,"email" varchar
            ,"phone" varchar
            ,"mobile" varchar
            ,"title" varchar
            ,"department" varchar
            ,"mailing_street" varchar
            ,"mailing_city" varchar
            ,"mailing_state" varchar
            ,"mailing_postal_code" varchar
            ,"mailing_country" varchar
            ,"account_id" uuid
            ,"version" bigint
        );
    END IF;

    IF EXISTS(SELECT TRUE FROM pg_type where typnamespace = (select oid from pg_catalog.pg_namespace where nspname = 'crm') AND typname = 'industries')
    THEN
        RAISE NOTICE 'ALTERING table industries';

        ALTER TABLE crm.industries ADD COLUMN IF NOT EXISTS "name" varchar;

        ALTER TABLE crm.industries ADD COLUMN IF NOT EXISTS "description" varchar;

        ALTER TABLE crm.industries ADD COLUMN IF NOT EXISTS "sort_order" smallint;

        ALTER TABLE crm.industries ADD COLUMN IF NOT EXISTS "version" bigint;

    ELSE
        RAISE NOTICE 'CREATING, table industries';
        CREATE TABLE crm.industries
        (
            "id" uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY
            ,"name" varchar
            ,"description" varchar
            ,"sort_order" smallint
            ,"version" bigint
        );
    END IF;

    IF EXISTS(SELECT TRUE FROM pg_type where typnamespace = (select oid from pg_catalog.pg_namespace where nspname = 'crm') AND typname = 'leads')
    THEN
        RAISE NOTICE 'ALTERING table leads';

        ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS "first_name" varchar;

        ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS "last_name" varchar;

        ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS "email" varchar;

        ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS "phone" varchar;

        ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS "company" varchar;

        ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS "title" varchar;

        ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS "website" varchar;

        ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS "description" varchar;

        ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS "annual_revenue" double precision;

        ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS "number_of_employees" integer;

        ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS "is_converted" boolean;

        ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS "converted_account_id" uuid;

        ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS "status_id" uuid;

        ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS "source_id" uuid;

        ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS "industry_id" uuid;

        ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS "version" bigint;

    ELSE
        RAISE NOTICE 'CREATING, table leads';
        CREATE TABLE crm.leads
        (
            "id" uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY
            ,"first_name" varchar
            ,"last_name" varchar
            ,"email" varchar
            ,"phone" varchar
            ,"company" varchar
            ,"title" varchar
            ,"website" varchar
            ,"description" varchar
            ,"annual_revenue" double precision
            ,"number_of_employees" integer
            ,"is_converted" boolean
            ,"converted_account_id" uuid
            ,"status_id" uuid
            ,"source_id" uuid
            ,"industry_id" uuid
            ,"version" bigint
        );
    END IF;

    IF EXISTS(SELECT TRUE FROM pg_type where typnamespace = (select oid from pg_catalog.pg_namespace where nspname = 'crm') AND typname = 'lead_sources')
    THEN
        RAISE NOTICE 'ALTERING table lead_sources';

        ALTER TABLE crm.lead_sources ADD COLUMN IF NOT EXISTS "name" varchar;

        ALTER TABLE crm.lead_sources ADD COLUMN IF NOT EXISTS "sort_order" smallint;

        ALTER TABLE crm.lead_sources ADD COLUMN IF NOT EXISTS "version" bigint;

    ELSE
        RAISE NOTICE 'CREATING, table lead_sources';
        CREATE TABLE crm.lead_sources
        (
            "id" uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY
            ,"name" varchar
            ,"sort_order" smallint
            ,"version" bigint
        );
    END IF;

    IF EXISTS(SELECT TRUE FROM pg_type where typnamespace = (select oid from pg_catalog.pg_namespace where nspname = 'crm') AND typname = 'lead_statuses')
    THEN
        RAISE NOTICE 'ALTERING table lead_statuses';

        ALTER TABLE crm.lead_statuses ADD COLUMN IF NOT EXISTS "name" varchar;

        ALTER TABLE crm.lead_statuses ADD COLUMN IF NOT EXISTS "is_converted" boolean;

        ALTER TABLE crm.lead_statuses ADD COLUMN IF NOT EXISTS "sort_order" smallint;

        ALTER TABLE crm.lead_statuses ADD COLUMN IF NOT EXISTS "version" bigint;

    ELSE
        RAISE NOTICE 'CREATING, table lead_statuses';
        CREATE TABLE crm.lead_statuses
        (
            "id" uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY
            ,"name" varchar
            ,"is_converted" boolean
            ,"sort_order" smallint
            ,"version" bigint
        );
    END IF;

    IF EXISTS(SELECT TRUE FROM pg_type where typnamespace = (select oid from pg_catalog.pg_namespace where nspname = 'crm') AND typname = 'opportunities')
    THEN
        RAISE NOTICE 'ALTERING table opportunities';

        ALTER TABLE crm.opportunities ADD COLUMN IF NOT EXISTS "name" varchar;

        ALTER TABLE crm.opportunities ADD COLUMN IF NOT EXISTS "amount" double precision;

        ALTER TABLE crm.opportunities ADD COLUMN IF NOT EXISTS "close_date" date;

        ALTER TABLE crm.opportunities ADD COLUMN IF NOT EXISTS "description" varchar;

        ALTER TABLE crm.opportunities ADD COLUMN IF NOT EXISTS "next_step" varchar;

        ALTER TABLE crm.opportunities ADD COLUMN IF NOT EXISTS "lead_source" varchar;

        ALTER TABLE crm.opportunities ADD COLUMN IF NOT EXISTS "account_id" uuid;

        ALTER TABLE crm.opportunities ADD COLUMN IF NOT EXISTS "stage_id" uuid;

        ALTER TABLE crm.opportunities ADD COLUMN IF NOT EXISTS "version" bigint;

    ELSE
        RAISE NOTICE 'CREATING, table opportunities';
        CREATE TABLE crm.opportunities
        (
            "id" uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY
            ,"name" varchar
            ,"amount" double precision
            ,"close_date" date
            ,"description" varchar
            ,"next_step" varchar
            ,"lead_source" varchar
            ,"account_id" uuid
            ,"stage_id" uuid
            ,"version" bigint
        );
    END IF;

    IF EXISTS(SELECT TRUE FROM pg_type where typnamespace = (select oid from pg_catalog.pg_namespace where nspname = 'crm') AND typname = 'opportunity_stages')
    THEN
        RAISE NOTICE 'ALTERING table opportunity_stages';

        ALTER TABLE crm.opportunity_stages ADD COLUMN IF NOT EXISTS "name" varchar;

        ALTER TABLE crm.opportunity_stages ADD COLUMN IF NOT EXISTS "probability" real;

        ALTER TABLE crm.opportunity_stages ADD COLUMN IF NOT EXISTS "is_closed" boolean;

        ALTER TABLE crm.opportunity_stages ADD COLUMN IF NOT EXISTS "is_won" boolean;

        ALTER TABLE crm.opportunity_stages ADD COLUMN IF NOT EXISTS "sort_order" smallint;

        ALTER TABLE crm.opportunity_stages ADD COLUMN IF NOT EXISTS "version" bigint;

    ELSE
        RAISE NOTICE 'CREATING, table opportunity_stages';
        CREATE TABLE crm.opportunity_stages
        (
            "id" uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY
            ,"name" varchar
            ,"probability" real
            ,"is_closed" boolean
            ,"is_won" boolean
            ,"sort_order" smallint
            ,"version" bigint
        );
    END IF;

    IF EXISTS(SELECT TRUE FROM pg_type where typnamespace = (select oid from pg_catalog.pg_namespace where nspname = 'crm') AND typname = 'pricebooks')
    THEN
        RAISE NOTICE 'ALTERING table pricebooks';

        ALTER TABLE crm.pricebooks ADD COLUMN IF NOT EXISTS "name" varchar;

        ALTER TABLE crm.pricebooks ADD COLUMN IF NOT EXISTS "description" varchar;

        ALTER TABLE crm.pricebooks ADD COLUMN IF NOT EXISTS "is_active" boolean;

        ALTER TABLE crm.pricebooks ADD COLUMN IF NOT EXISTS "is_standard" boolean;

        ALTER TABLE crm.pricebooks ADD COLUMN IF NOT EXISTS "version" bigint;

    ELSE
        RAISE NOTICE 'CREATING, table pricebooks';
        CREATE TABLE crm.pricebooks
        (
            "id" uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY
            ,"name" varchar
            ,"description" varchar
            ,"is_active" boolean
            ,"is_standard" boolean
            ,"version" bigint
        );
    END IF;

    IF EXISTS(SELECT TRUE FROM pg_type where typnamespace = (select oid from pg_catalog.pg_namespace where nspname = 'crm') AND typname = 'products')
    THEN
        RAISE NOTICE 'ALTERING table products';

        ALTER TABLE crm.products ADD COLUMN IF NOT EXISTS "name" varchar;

        ALTER TABLE crm.products ADD COLUMN IF NOT EXISTS "product_code" varchar;

        ALTER TABLE crm.products ADD COLUMN IF NOT EXISTS "description" varchar;

        ALTER TABLE crm.products ADD COLUMN IF NOT EXISTS "list_price" double precision;

        ALTER TABLE crm.products ADD COLUMN IF NOT EXISTS "is_active" boolean;

        ALTER TABLE crm.products ADD COLUMN IF NOT EXISTS "family" varchar;

        ALTER TABLE crm.products ADD COLUMN IF NOT EXISTS "pricebook_id" uuid;

        ALTER TABLE crm.products ADD COLUMN IF NOT EXISTS "version" bigint;

    ELSE
        RAISE NOTICE 'CREATING, table products';
        CREATE TABLE crm.products
        (
            "id" uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY
            ,"name" varchar
            ,"product_code" varchar
            ,"description" varchar
            ,"list_price" double precision
            ,"is_active" boolean
            ,"family" varchar
            ,"pricebook_id" uuid
            ,"version" bigint
        );
    END IF;

    IF EXISTS(SELECT TRUE FROM pg_type where typnamespace = (select oid from pg_catalog.pg_namespace where nspname = 'crm') AND typname = 'quotes')
    THEN
        RAISE NOTICE 'ALTERING table quotes';

        ALTER TABLE crm.quotes ADD COLUMN IF NOT EXISTS "name" varchar;

        ALTER TABLE crm.quotes ADD COLUMN IF NOT EXISTS "quote_number" varchar;

        ALTER TABLE crm.quotes ADD COLUMN IF NOT EXISTS "expiration_date" date;

        ALTER TABLE crm.quotes ADD COLUMN IF NOT EXISTS "description" varchar;

        ALTER TABLE crm.quotes ADD COLUMN IF NOT EXISTS "subtotal" double precision;

        ALTER TABLE crm.quotes ADD COLUMN IF NOT EXISTS "discount" double precision;

        ALTER TABLE crm.quotes ADD COLUMN IF NOT EXISTS "tax" double precision;

        ALTER TABLE crm.quotes ADD COLUMN IF NOT EXISTS "total_price" double precision;

        ALTER TABLE crm.quotes ADD COLUMN IF NOT EXISTS "opportunity_id" uuid;

        ALTER TABLE crm.quotes ADD COLUMN IF NOT EXISTS "account_id" uuid;

        ALTER TABLE crm.quotes ADD COLUMN IF NOT EXISTS "status_id" uuid;

        ALTER TABLE crm.quotes ADD COLUMN IF NOT EXISTS "version" bigint;

    ELSE
        RAISE NOTICE 'CREATING, table quotes';
        CREATE TABLE crm.quotes
        (
            "id" uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY
            ,"name" varchar
            ,"quote_number" varchar
            ,"expiration_date" date
            ,"description" varchar
            ,"subtotal" double precision
            ,"discount" double precision
            ,"tax" double precision
            ,"total_price" double precision
            ,"opportunity_id" uuid
            ,"account_id" uuid
            ,"status_id" uuid
            ,"version" bigint
        );
    END IF;

    IF EXISTS(SELECT TRUE FROM pg_type where typnamespace = (select oid from pg_catalog.pg_namespace where nspname = 'crm') AND typname = 'quote_line_items')
    THEN
        RAISE NOTICE 'ALTERING table quote_line_items';

        ALTER TABLE crm.quote_line_items ADD COLUMN IF NOT EXISTS "quantity" double precision;

        ALTER TABLE crm.quote_line_items ADD COLUMN IF NOT EXISTS "unit_price" double precision;

        ALTER TABLE crm.quote_line_items ADD COLUMN IF NOT EXISTS "discount" double precision;

        ALTER TABLE crm.quote_line_items ADD COLUMN IF NOT EXISTS "total_price" double precision;

        ALTER TABLE crm.quote_line_items ADD COLUMN IF NOT EXISTS "description" varchar;

        ALTER TABLE crm.quote_line_items ADD COLUMN IF NOT EXISTS "sort_order" smallint;

        ALTER TABLE crm.quote_line_items ADD COLUMN IF NOT EXISTS "quote_id" uuid;

        ALTER TABLE crm.quote_line_items ADD COLUMN IF NOT EXISTS "product_id" uuid;

        ALTER TABLE crm.quote_line_items ADD COLUMN IF NOT EXISTS "version" bigint;

    ELSE
        RAISE NOTICE 'CREATING, table quote_line_items';
        CREATE TABLE crm.quote_line_items
        (
            "id" uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY
            ,"quantity" double precision
            ,"unit_price" double precision
            ,"discount" double precision
            ,"total_price" double precision
            ,"description" varchar
            ,"sort_order" smallint
            ,"quote_id" uuid
            ,"product_id" uuid
            ,"version" bigint
        );
    END IF;

    IF EXISTS(SELECT TRUE FROM pg_type where typnamespace = (select oid from pg_catalog.pg_namespace where nspname = 'crm') AND typname = 'quote_statuses')
    THEN
        RAISE NOTICE 'ALTERING table quote_statuses';

        ALTER TABLE crm.quote_statuses ADD COLUMN IF NOT EXISTS "name" varchar;

        ALTER TABLE crm.quote_statuses ADD COLUMN IF NOT EXISTS "sort_order" smallint;

        ALTER TABLE crm.quote_statuses ADD COLUMN IF NOT EXISTS "version" bigint;

    ELSE
        RAISE NOTICE 'CREATING, table quote_statuses';
        CREATE TABLE crm.quote_statuses
        (
            "id" uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY
            ,"name" varchar
            ,"sort_order" smallint
            ,"version" bigint
        );
    END IF;







    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'accounts'
        AND indexname = 'idx_accounts_name'
    ) THEN
        RAISE NOTICE 'Creating index idx_accounts_name';
        CREATE INDEX idx_accounts_name
        ON crm.accounts ("name");
    ELSE
        RAISE NOTICE 'Index idx_accounts_name already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'accounts'
        AND indexname = 'idx_accounts_industry_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_accounts_industry_id';
        CREATE INDEX idx_accounts_industry_id
        ON crm.accounts ("industry_id");
    ELSE
        RAISE NOTICE 'Index idx_accounts_industry_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'activities'
        AND indexname = 'idx_activities_account_id_contact_id_opportunity_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_activities_account_id_contact_id_opportunity_id';
        CREATE INDEX idx_activities_account_id_contact_id_opportunity_id
        ON crm.activities ("account_id", "contact_id", "opportunity_id");
    ELSE
        RAISE NOTICE 'Index idx_activities_account_id_contact_id_opportunity_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'activities'
        AND indexname = 'idx_activities_type_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_activities_type_id';
        CREATE INDEX idx_activities_type_id
        ON crm.activities ("type_id");
    ELSE
        RAISE NOTICE 'Index idx_activities_type_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'activities'
        AND indexname = 'idx_activities_account_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_activities_account_id';
        CREATE INDEX idx_activities_account_id
        ON crm.activities ("account_id");
    ELSE
        RAISE NOTICE 'Index idx_activities_account_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'activities'
        AND indexname = 'idx_activities_contact_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_activities_contact_id';
        CREATE INDEX idx_activities_contact_id
        ON crm.activities ("contact_id");
    ELSE
        RAISE NOTICE 'Index idx_activities_contact_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'activities'
        AND indexname = 'idx_activities_opportunity_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_activities_opportunity_id';
        CREATE INDEX idx_activities_opportunity_id
        ON crm.activities ("opportunity_id");
    ELSE
        RAISE NOTICE 'Index idx_activities_opportunity_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'activities'
        AND indexname = 'idx_activities_lead_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_activities_lead_id';
        CREATE INDEX idx_activities_lead_id
        ON crm.activities ("lead_id");
    ELSE
        RAISE NOTICE 'Index idx_activities_lead_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'activity_types'
        AND indexname = 'idx_activity_types_name'
    ) THEN
        RAISE NOTICE 'Creating index idx_activity_types_name';
        CREATE INDEX idx_activity_types_name
        ON crm.activity_types ("name");
    ELSE
        RAISE NOTICE 'Index idx_activity_types_name already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'contacts'
        AND indexname = 'idx_contacts_account_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_contacts_account_id';
        CREATE INDEX idx_contacts_account_id
        ON crm.contacts ("account_id");
    ELSE
        RAISE NOTICE 'Index idx_contacts_account_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'contacts'
        AND indexname = 'idx_contacts_account_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_contacts_account_id';
        CREATE INDEX idx_contacts_account_id
        ON crm.contacts ("account_id");
    ELSE
        RAISE NOTICE 'Index idx_contacts_account_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'industries'
        AND indexname = 'idx_industries_name'
    ) THEN
        RAISE NOTICE 'Creating index idx_industries_name';
        CREATE INDEX idx_industries_name
        ON crm.industries ("name");
    ELSE
        RAISE NOTICE 'Index idx_industries_name already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'leads'
        AND indexname = 'idx_leads_email'
    ) THEN
        RAISE NOTICE 'Creating index idx_leads_email';
        CREATE INDEX idx_leads_email
        ON crm.leads ("email");
    ELSE
        RAISE NOTICE 'Index idx_leads_email already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'leads'
        AND indexname = 'idx_leads_converted_account_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_leads_converted_account_id';
        CREATE INDEX idx_leads_converted_account_id
        ON crm.leads ("converted_account_id");
    ELSE
        RAISE NOTICE 'Index idx_leads_converted_account_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'leads'
        AND indexname = 'idx_leads_status_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_leads_status_id';
        CREATE INDEX idx_leads_status_id
        ON crm.leads ("status_id");
    ELSE
        RAISE NOTICE 'Index idx_leads_status_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'leads'
        AND indexname = 'idx_leads_source_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_leads_source_id';
        CREATE INDEX idx_leads_source_id
        ON crm.leads ("source_id");
    ELSE
        RAISE NOTICE 'Index idx_leads_source_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'leads'
        AND indexname = 'idx_leads_industry_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_leads_industry_id';
        CREATE INDEX idx_leads_industry_id
        ON crm.leads ("industry_id");
    ELSE
        RAISE NOTICE 'Index idx_leads_industry_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'lead_sources'
        AND indexname = 'idx_lead_sources_name'
    ) THEN
        RAISE NOTICE 'Creating index idx_lead_sources_name';
        CREATE INDEX idx_lead_sources_name
        ON crm.lead_sources ("name");
    ELSE
        RAISE NOTICE 'Index idx_lead_sources_name already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'lead_statuses'
        AND indexname = 'idx_lead_statuses_name'
    ) THEN
        RAISE NOTICE 'Creating index idx_lead_statuses_name';
        CREATE INDEX idx_lead_statuses_name
        ON crm.lead_statuses ("name");
    ELSE
        RAISE NOTICE 'Index idx_lead_statuses_name already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'opportunities'
        AND indexname = 'idx_opportunities_name_account_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_opportunities_name_account_id';
        CREATE INDEX idx_opportunities_name_account_id
        ON crm.opportunities ("name", "account_id");
    ELSE
        RAISE NOTICE 'Index idx_opportunities_name_account_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'opportunities'
        AND indexname = 'idx_opportunities_account_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_opportunities_account_id';
        CREATE INDEX idx_opportunities_account_id
        ON crm.opportunities ("account_id");
    ELSE
        RAISE NOTICE 'Index idx_opportunities_account_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'opportunities'
        AND indexname = 'idx_opportunities_stage_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_opportunities_stage_id';
        CREATE INDEX idx_opportunities_stage_id
        ON crm.opportunities ("stage_id");
    ELSE
        RAISE NOTICE 'Index idx_opportunities_stage_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'opportunity_stages'
        AND indexname = 'idx_opportunity_stages_name'
    ) THEN
        RAISE NOTICE 'Creating index idx_opportunity_stages_name';
        CREATE INDEX idx_opportunity_stages_name
        ON crm.opportunity_stages ("name");
    ELSE
        RAISE NOTICE 'Index idx_opportunity_stages_name already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'pricebooks'
        AND indexname = 'idx_pricebooks_name'
    ) THEN
        RAISE NOTICE 'Creating index idx_pricebooks_name';
        CREATE INDEX idx_pricebooks_name
        ON crm.pricebooks ("name");
    ELSE
        RAISE NOTICE 'Index idx_pricebooks_name already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'products'
        AND indexname = 'idx_products_name'
    ) THEN
        RAISE NOTICE 'Creating index idx_products_name';
        CREATE INDEX idx_products_name
        ON crm.products ("name");
    ELSE
        RAISE NOTICE 'Index idx_products_name already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'products'
        AND indexname = 'idx_products_pricebook_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_products_pricebook_id';
        CREATE INDEX idx_products_pricebook_id
        ON crm.products ("pricebook_id");
    ELSE
        RAISE NOTICE 'Index idx_products_pricebook_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'quotes'
        AND indexname = 'idx_quotes_opportunity_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_quotes_opportunity_id';
        CREATE INDEX idx_quotes_opportunity_id
        ON crm.quotes ("opportunity_id");
    ELSE
        RAISE NOTICE 'Index idx_quotes_opportunity_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'quotes'
        AND indexname = 'idx_quotes_opportunity_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_quotes_opportunity_id';
        CREATE INDEX idx_quotes_opportunity_id
        ON crm.quotes ("opportunity_id");
    ELSE
        RAISE NOTICE 'Index idx_quotes_opportunity_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'quotes'
        AND indexname = 'idx_quotes_account_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_quotes_account_id';
        CREATE INDEX idx_quotes_account_id
        ON crm.quotes ("account_id");
    ELSE
        RAISE NOTICE 'Index idx_quotes_account_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'quotes'
        AND indexname = 'idx_quotes_status_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_quotes_status_id';
        CREATE INDEX idx_quotes_status_id
        ON crm.quotes ("status_id");
    ELSE
        RAISE NOTICE 'Index idx_quotes_status_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'quote_line_items'
        AND indexname = 'idx_quote_line_items_quote_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_quote_line_items_quote_id';
        CREATE INDEX idx_quote_line_items_quote_id
        ON crm.quote_line_items ("quote_id");
    ELSE
        RAISE NOTICE 'Index idx_quote_line_items_quote_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'quote_line_items'
        AND indexname = 'idx_quote_line_items_quote_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_quote_line_items_quote_id';
        CREATE INDEX idx_quote_line_items_quote_id
        ON crm.quote_line_items ("quote_id");
    ELSE
        RAISE NOTICE 'Index idx_quote_line_items_quote_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'quote_line_items'
        AND indexname = 'idx_quote_line_items_product_id'
    ) THEN
        RAISE NOTICE 'Creating index idx_quote_line_items_product_id';
        CREATE INDEX idx_quote_line_items_product_id
        ON crm.quote_line_items ("product_id");
    ELSE
        RAISE NOTICE 'Index idx_quote_line_items_product_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'crm'
        AND tablename = 'quote_statuses'
        AND indexname = 'idx_quote_statuses_name'
    ) THEN
        RAISE NOTICE 'Creating index idx_quote_statuses_name';
        CREATE INDEX idx_quote_statuses_name
        ON crm.quote_statuses ("name");
    ELSE
        RAISE NOTICE 'Index idx_quote_statuses_name already exists';
    END IF;




    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_schema = 'crm'
        AND table_name = 'accounts'
        AND constraint_name = 'fk_accounts_industry_id'
        AND constraint_type = 'FOREIGN KEY'
    ) THEN
        RAISE NOTICE 'Creating foreign key constraint fk_accounts_industry_id';
        ALTER TABLE crm.accounts
        ADD CONSTRAINT fk_accounts_industry_id
        FOREIGN KEY ("industry_id")
        REFERENCES crm.industries("id")
        ON DELETE RESTRICT ON UPDATE CASCADE;
    ELSE
        RAISE NOTICE 'Foreign key constraint fk_accounts_industry_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_schema = 'crm'
        AND table_name = 'activities'
        AND constraint_name = 'fk_activities_type_id'
        AND constraint_type = 'FOREIGN KEY'
    ) THEN
        RAISE NOTICE 'Creating foreign key constraint fk_activities_type_id';
        ALTER TABLE crm.activities
        ADD CONSTRAINT fk_activities_type_id
        FOREIGN KEY ("type_id")
        REFERENCES crm.activity_types("id")
        ON DELETE RESTRICT ON UPDATE CASCADE;
    ELSE
        RAISE NOTICE 'Foreign key constraint fk_activities_type_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_schema = 'crm'
        AND table_name = 'activities'
        AND constraint_name = 'fk_activities_account_id'
        AND constraint_type = 'FOREIGN KEY'
    ) THEN
        RAISE NOTICE 'Creating foreign key constraint fk_activities_account_id';
        ALTER TABLE crm.activities
        ADD CONSTRAINT fk_activities_account_id
        FOREIGN KEY ("account_id")
        REFERENCES crm.accounts("id")
        ON DELETE RESTRICT ON UPDATE CASCADE;
    ELSE
        RAISE NOTICE 'Foreign key constraint fk_activities_account_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_schema = 'crm'
        AND table_name = 'activities'
        AND constraint_name = 'fk_activities_contact_id'
        AND constraint_type = 'FOREIGN KEY'
    ) THEN
        RAISE NOTICE 'Creating foreign key constraint fk_activities_contact_id';
        ALTER TABLE crm.activities
        ADD CONSTRAINT fk_activities_contact_id
        FOREIGN KEY ("contact_id")
        REFERENCES crm.contacts("id")
        ON DELETE RESTRICT ON UPDATE CASCADE;
    ELSE
        RAISE NOTICE 'Foreign key constraint fk_activities_contact_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_schema = 'crm'
        AND table_name = 'activities'
        AND constraint_name = 'fk_activities_opportunity_id'
        AND constraint_type = 'FOREIGN KEY'
    ) THEN
        RAISE NOTICE 'Creating foreign key constraint fk_activities_opportunity_id';
        ALTER TABLE crm.activities
        ADD CONSTRAINT fk_activities_opportunity_id
        FOREIGN KEY ("opportunity_id")
        REFERENCES crm.opportunities("id")
        ON DELETE RESTRICT ON UPDATE CASCADE;
    ELSE
        RAISE NOTICE 'Foreign key constraint fk_activities_opportunity_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_schema = 'crm'
        AND table_name = 'activities'
        AND constraint_name = 'fk_activities_lead_id'
        AND constraint_type = 'FOREIGN KEY'
    ) THEN
        RAISE NOTICE 'Creating foreign key constraint fk_activities_lead_id';
        ALTER TABLE crm.activities
        ADD CONSTRAINT fk_activities_lead_id
        FOREIGN KEY ("lead_id")
        REFERENCES crm.leads("id")
        ON DELETE RESTRICT ON UPDATE CASCADE;
    ELSE
        RAISE NOTICE 'Foreign key constraint fk_activities_lead_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_schema = 'crm'
        AND table_name = 'contacts'
        AND constraint_name = 'fk_contacts_account_id'
        AND constraint_type = 'FOREIGN KEY'
    ) THEN
        RAISE NOTICE 'Creating foreign key constraint fk_contacts_account_id';
        ALTER TABLE crm.contacts
        ADD CONSTRAINT fk_contacts_account_id
        FOREIGN KEY ("account_id")
        REFERENCES crm.accounts("id")
        ON DELETE RESTRICT ON UPDATE CASCADE;
    ELSE
        RAISE NOTICE 'Foreign key constraint fk_contacts_account_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_schema = 'crm'
        AND table_name = 'leads'
        AND constraint_name = 'fk_leads_converted_account_id'
        AND constraint_type = 'FOREIGN KEY'
    ) THEN
        RAISE NOTICE 'Creating foreign key constraint fk_leads_converted_account_id';
        ALTER TABLE crm.leads
        ADD CONSTRAINT fk_leads_converted_account_id
        FOREIGN KEY ("converted_account_id")
        REFERENCES crm.accounts("id")
        ON DELETE RESTRICT ON UPDATE CASCADE;
    ELSE
        RAISE NOTICE 'Foreign key constraint fk_leads_converted_account_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_schema = 'crm'
        AND table_name = 'leads'
        AND constraint_name = 'fk_leads_status_id'
        AND constraint_type = 'FOREIGN KEY'
    ) THEN
        RAISE NOTICE 'Creating foreign key constraint fk_leads_status_id';
        ALTER TABLE crm.leads
        ADD CONSTRAINT fk_leads_status_id
        FOREIGN KEY ("status_id")
        REFERENCES crm.lead_statuses("id")
        ON DELETE RESTRICT ON UPDATE CASCADE;
    ELSE
        RAISE NOTICE 'Foreign key constraint fk_leads_status_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_schema = 'crm'
        AND table_name = 'leads'
        AND constraint_name = 'fk_leads_source_id'
        AND constraint_type = 'FOREIGN KEY'
    ) THEN
        RAISE NOTICE 'Creating foreign key constraint fk_leads_source_id';
        ALTER TABLE crm.leads
        ADD CONSTRAINT fk_leads_source_id
        FOREIGN KEY ("source_id")
        REFERENCES crm.lead_sources("id")
        ON DELETE RESTRICT ON UPDATE CASCADE;
    ELSE
        RAISE NOTICE 'Foreign key constraint fk_leads_source_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_schema = 'crm'
        AND table_name = 'leads'
        AND constraint_name = 'fk_leads_industry_id'
        AND constraint_type = 'FOREIGN KEY'
    ) THEN
        RAISE NOTICE 'Creating foreign key constraint fk_leads_industry_id';
        ALTER TABLE crm.leads
        ADD CONSTRAINT fk_leads_industry_id
        FOREIGN KEY ("industry_id")
        REFERENCES crm.industries("id")
        ON DELETE RESTRICT ON UPDATE CASCADE;
    ELSE
        RAISE NOTICE 'Foreign key constraint fk_leads_industry_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_schema = 'crm'
        AND table_name = 'opportunities'
        AND constraint_name = 'fk_opportunities_account_id'
        AND constraint_type = 'FOREIGN KEY'
    ) THEN
        RAISE NOTICE 'Creating foreign key constraint fk_opportunities_account_id';
        ALTER TABLE crm.opportunities
        ADD CONSTRAINT fk_opportunities_account_id
        FOREIGN KEY ("account_id")
        REFERENCES crm.accounts("id")
        ON DELETE RESTRICT ON UPDATE CASCADE;
    ELSE
        RAISE NOTICE 'Foreign key constraint fk_opportunities_account_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_schema = 'crm'
        AND table_name = 'opportunities'
        AND constraint_name = 'fk_opportunities_stage_id'
        AND constraint_type = 'FOREIGN KEY'
    ) THEN
        RAISE NOTICE 'Creating foreign key constraint fk_opportunities_stage_id';
        ALTER TABLE crm.opportunities
        ADD CONSTRAINT fk_opportunities_stage_id
        FOREIGN KEY ("stage_id")
        REFERENCES crm.opportunity_stages("id")
        ON DELETE RESTRICT ON UPDATE CASCADE;
    ELSE
        RAISE NOTICE 'Foreign key constraint fk_opportunities_stage_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_schema = 'crm'
        AND table_name = 'products'
        AND constraint_name = 'fk_products_pricebook_id'
        AND constraint_type = 'FOREIGN KEY'
    ) THEN
        RAISE NOTICE 'Creating foreign key constraint fk_products_pricebook_id';
        ALTER TABLE crm.products
        ADD CONSTRAINT fk_products_pricebook_id
        FOREIGN KEY ("pricebook_id")
        REFERENCES crm.pricebooks("id")
        ON DELETE RESTRICT ON UPDATE CASCADE;
    ELSE
        RAISE NOTICE 'Foreign key constraint fk_products_pricebook_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_schema = 'crm'
        AND table_name = 'quotes'
        AND constraint_name = 'fk_quotes_opportunity_id'
        AND constraint_type = 'FOREIGN KEY'
    ) THEN
        RAISE NOTICE 'Creating foreign key constraint fk_quotes_opportunity_id';
        ALTER TABLE crm.quotes
        ADD CONSTRAINT fk_quotes_opportunity_id
        FOREIGN KEY ("opportunity_id")
        REFERENCES crm.opportunities("id")
        ON DELETE RESTRICT ON UPDATE CASCADE;
    ELSE
        RAISE NOTICE 'Foreign key constraint fk_quotes_opportunity_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_schema = 'crm'
        AND table_name = 'quotes'
        AND constraint_name = 'fk_quotes_account_id'
        AND constraint_type = 'FOREIGN KEY'
    ) THEN
        RAISE NOTICE 'Creating foreign key constraint fk_quotes_account_id';
        ALTER TABLE crm.quotes
        ADD CONSTRAINT fk_quotes_account_id
        FOREIGN KEY ("account_id")
        REFERENCES crm.accounts("id")
        ON DELETE RESTRICT ON UPDATE CASCADE;
    ELSE
        RAISE NOTICE 'Foreign key constraint fk_quotes_account_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_schema = 'crm'
        AND table_name = 'quotes'
        AND constraint_name = 'fk_quotes_status_id'
        AND constraint_type = 'FOREIGN KEY'
    ) THEN
        RAISE NOTICE 'Creating foreign key constraint fk_quotes_status_id';
        ALTER TABLE crm.quotes
        ADD CONSTRAINT fk_quotes_status_id
        FOREIGN KEY ("status_id")
        REFERENCES crm.quote_statuses("id")
        ON DELETE RESTRICT ON UPDATE CASCADE;
    ELSE
        RAISE NOTICE 'Foreign key constraint fk_quotes_status_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_schema = 'crm'
        AND table_name = 'quote_line_items'
        AND constraint_name = 'fk_quote_line_items_quote_id'
        AND constraint_type = 'FOREIGN KEY'
    ) THEN
        RAISE NOTICE 'Creating foreign key constraint fk_quote_line_items_quote_id';
        ALTER TABLE crm.quote_line_items
        ADD CONSTRAINT fk_quote_line_items_quote_id
        FOREIGN KEY ("quote_id")
        REFERENCES crm.quotes("id")
        ON DELETE RESTRICT ON UPDATE CASCADE;
    ELSE
        RAISE NOTICE 'Foreign key constraint fk_quote_line_items_quote_id already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_schema = 'crm'
        AND table_name = 'quote_line_items'
        AND constraint_name = 'fk_quote_line_items_product_id'
        AND constraint_type = 'FOREIGN KEY'
    ) THEN
        RAISE NOTICE 'Creating foreign key constraint fk_quote_line_items_product_id';
        ALTER TABLE crm.quote_line_items
        ADD CONSTRAINT fk_quote_line_items_product_id
        FOREIGN KEY ("product_id")
        REFERENCES crm.products("id")
        ON DELETE RESTRICT ON UPDATE CASCADE;
    ELSE
        RAISE NOTICE 'Foreign key constraint fk_quote_line_items_product_id already exists';
    END IF;







    -- Creating junction table for ManyToMany relationship: Contact <-> Opportunity

    IF NOT EXISTS(SELECT TRUE FROM pg_type where typnamespace = (select oid from pg_catalog.pg_namespace where nspname = 'crm') AND typname = 'opportunity_contacts')
    THEN
        RAISE NOTICE 'CREATING junction table OpportunityContact';
        CREATE TABLE crm.opportunity_contacts
        (
            "id" uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
            "contact_id" uuid NOT NULL,
            "opportunity_id" uuid NOT NULL,
            "created_at" timestamp DEFAULT NOW(),
            UNIQUE("contact_id", "opportunity_id")
        );

        CREATE INDEX idx_opportunity_contacts_contact_id ON crm.opportunity_contacts ("contact_id");
        CREATE INDEX idx_opportunity_contacts_opportunity_id ON crm.opportunity_contacts ("opportunity_id");

        ALTER TABLE crm.opportunity_contacts
        ADD CONSTRAINT fk_opportunity_contacts_contact_id
        FOREIGN KEY ("contact_id")
        REFERENCES crm.contacts("id")
        ON DELETE CASCADE ON UPDATE CASCADE;

        ALTER TABLE crm.opportunity_contacts
        ADD CONSTRAINT fk_opportunity_contacts_opportunity_id
        FOREIGN KEY ("opportunity_id")
        REFERENCES crm.opportunities("id")
        ON DELETE CASCADE ON UPDATE CASCADE;
    ELSE
        RAISE NOTICE 'Junction table OpportunityContact already exists';
    END IF;

    -- Creating junction table for ManyToMany relationship: Opportunity <-> Contact

    IF NOT EXISTS(SELECT TRUE FROM pg_type where typnamespace = (select oid from pg_catalog.pg_namespace where nspname = 'crm') AND typname = 'opportunity_contacts')
    THEN
        RAISE NOTICE 'CREATING junction table OpportunityContact';
        CREATE TABLE crm.opportunity_contacts
        (
            "id" uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
            "opportunity_id" uuid NOT NULL,
            "contact_id" uuid NOT NULL,
            "created_at" timestamp DEFAULT NOW(),
            UNIQUE("opportunity_id", "contact_id")
        );

        CREATE INDEX idx_opportunity_contacts_opportunity_id ON crm.opportunity_contacts ("opportunity_id");
        CREATE INDEX idx_opportunity_contacts_contact_id ON crm.opportunity_contacts ("contact_id");

        ALTER TABLE crm.opportunity_contacts
        ADD CONSTRAINT fk_opportunity_contacts_opportunity_id
        FOREIGN KEY ("opportunity_id")
        REFERENCES crm.opportunities("id")
        ON DELETE CASCADE ON UPDATE CASCADE;

        ALTER TABLE crm.opportunity_contacts
        ADD CONSTRAINT fk_opportunity_contacts_contact_id
        FOREIGN KEY ("contact_id")
        REFERENCES crm.contacts("id")
        ON DELETE CASCADE ON UPDATE CASCADE;
    ELSE
        RAISE NOTICE 'Junction table OpportunityContact already exists';
    END IF;


END $$;
