// Generated by App Framework. Do not hand-edit.
import { AppfwEntityScreen } from "../../src/generated/AppfwEntityScreen";

export default function ProductEntityRoute() {
  return <AppfwEntityScreen entityName="Product" />;
}
