// Generated by App Framework. Do not hand-edit.
import { AppfwEntityScreen } from "../../src/generated/AppfwEntityScreen";

export default function QueueItemEntityRoute() {
  return <AppfwEntityScreen entityName="QueueItem" />;
}
