// Generated by App Framework. Do not hand-edit.
import { AppfwEntityScreen } from "../../src/generated/AppfwEntityScreen";

export default function QueueEntityRoute() {
  return <AppfwEntityScreen entityName="Queue" />;
}
