--
--    Generated by app_gen.
--    by app_gen/_templates/database/postgresql/seed_sql/_mod.j2
--    Seed data for crm schema (PostgreSQL dialect)
--

DO $$
BEGIN




-- ----------------------------------------------------------------------------
-- ActivityType
-- ----------------------------------------------------------------------------


INSERT INTO crm.activity_types (
  id, name, sort_order
)
VALUES (
  'ac71ec00-0000-4000-8000-100000000001',

  'Email',

  10


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.activity_types (
  id, name, sort_order
)
VALUES (
  'ac71ec00-0000-4000-8000-100000000002',

  'Call',

  20


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.activity_types (
  id, name, sort_order
)
VALUES (
  'ac71ec00-0000-4000-8000-100000000003',

  'Meeting',

  30


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.activity_types (
  id, name, sort_order
)
VALUES (
  'ac71ec00-0000-4000-8000-100000000004',

  'Task',

  40


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.activity_types (
  id, name, sort_order
)
VALUES (
  'ac71ec00-0000-4000-8000-100000000005',

  'Note',

  50


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- Industry
-- ----------------------------------------------------------------------------


INSERT INTO crm.industries (
  id, name, sort_order
)
VALUES (
  '10100070-0000-4000-8000-100000000001',

  'Healthcare',

  10


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.industries (
  id, name, sort_order
)
VALUES (
  '10100070-0000-4000-8000-100000000002',

  'Technology',

  20


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.industries (
  id, name, sort_order
)
VALUES (
  '10100070-0000-4000-8000-100000000003',

  'Financial Services',

  30


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.industries (
  id, name, sort_order
)
VALUES (
  '10100070-0000-4000-8000-100000000004',

  'Manufacturing',

  40


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.industries (
  id, name, sort_order
)
VALUES (
  '10100070-0000-4000-8000-100000000005',

  'Retail',

  50


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- LeadSource
-- ----------------------------------------------------------------------------


INSERT INTO crm.lead_sources (
  id, name, sort_order
)
VALUES (
  '1eadcc01-0000-4000-8000-100000000001',

  'Web',

  10


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.lead_sources (
  id, name, sort_order
)
VALUES (
  '1eadcc01-0000-4000-8000-100000000002',

  'Phone Inquiry',

  20


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.lead_sources (
  id, name, sort_order
)
VALUES (
  '1eadcc01-0000-4000-8000-100000000003',

  'Partner Referral',

  30


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.lead_sources (
  id, name, sort_order
)
VALUES (
  '1eadcc01-0000-4000-8000-100000000004',

  'Trade Show',

  40


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.lead_sources (
  id, name, sort_order
)
VALUES (
  '1eadcc01-0000-4000-8000-100000000005',

  'Employee Referral',

  50


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- LeadStatus
-- ----------------------------------------------------------------------------


INSERT INTO crm.lead_statuses (
  id, name, is_converted, sort_order
)
VALUES (
  '1eadcc00-0000-4000-8000-100000000001',

  'New',

  false,

  10


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.lead_statuses (
  id, name, is_converted, sort_order
)
VALUES (
  '1eadcc00-0000-4000-8000-100000000002',

  'Contacted',

  false,

  20


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.lead_statuses (
  id, name, is_converted, sort_order
)
VALUES (
  '1eadcc00-0000-4000-8000-100000000003',

  'Qualified',

  false,

  30


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.lead_statuses (
  id, name, is_converted, sort_order
)
VALUES (
  '1eadcc00-0000-4000-8000-100000000004',

  'Unqualified',

  false,

  40


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.lead_statuses (
  id, name, is_converted, sort_order
)
VALUES (
  '1eadcc00-0000-4000-8000-100000000005',

  'Converted',

  true,

  50


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- OpportunityStage
-- ----------------------------------------------------------------------------


INSERT INTO crm.opportunity_stages (
  id, name, probability, is_closed, is_won, sort_order
)
VALUES (
  '0998a900-0000-4000-8000-100000000001',

  'Prospecting',

  0.1,

  false,

  false,

  10


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunity_stages (
  id, name, probability, is_closed, is_won, sort_order
)
VALUES (
  '0998a900-0000-4000-8000-100000000002',

  'Qualification',

  0.2,

  false,

  false,

  20


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunity_stages (
  id, name, probability, is_closed, is_won, sort_order
)
VALUES (
  '0998a900-0000-4000-8000-100000000003',

  'Proposal',

  0.5,

  false,

  false,

  30


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunity_stages (
  id, name, probability, is_closed, is_won, sort_order
)
VALUES (
  '0998a900-0000-4000-8000-100000000004',

  'Closed Won',

  1,

  true,

  true,

  40


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunity_stages (
  id, name, probability, is_closed, is_won, sort_order
)
VALUES (
  '0998a900-0000-4000-8000-100000000005',

  'Closed Lost',

  0,

  true,

  false,

  50


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- Pricebook
-- ----------------------------------------------------------------------------


INSERT INTO crm.pricebooks (
  id, name, description, is_active, is_standard
)
VALUES (
  '97000b00-0000-4000-8000-100000000001',

  'Standard Price Book',

  'Default price book for all products',

  true,

  true


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.pricebooks (
  id, name, description, is_active, is_standard
)
VALUES (
  '97000b00-0000-4000-8000-100000000002',

  'Partner Price Book',

  'Discounted pricing for channel partners',

  true,

  false


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- QuoteStatus
-- ----------------------------------------------------------------------------


INSERT INTO crm.quote_statuses (
  id, name, sort_order
)
VALUES (
  '9407ec00-0000-4000-8000-100000000001',

  'Draft',

  10


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_statuses (
  id, name, sort_order
)
VALUES (
  '9407ec00-0000-4000-8000-100000000002',

  'Needs Review',

  20


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_statuses (
  id, name, sort_order
)
VALUES (
  '9407ec00-0000-4000-8000-100000000003',

  'Delivered',

  30


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_statuses (
  id, name, sort_order
)
VALUES (
  '9407ec00-0000-4000-8000-100000000004',

  'Accepted',

  40


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_statuses (
  id, name, sort_order
)
VALUES (
  '9407ec00-0000-4000-8000-100000000005',

  'Rejected',

  50


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- Account
-- ----------------------------------------------------------------------------


INSERT INTO crm.accounts (
  id, name, website, phone, email, billing_city, billing_state, billing_country, annual_revenue, number_of_employees, industry_id
)
VALUES (
  'a0c00000-0000-4000-8000-100000000001',

  'Acme Dental Group',

  'https://acmedental.com',

  '555-0100',

  'info@acmedental.com',

  'Austin',

  'TX',

  'US',

  12000000,

  85,

  '10100070-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.accounts (
  id, name, website, phone, email, billing_city, billing_state, billing_country, annual_revenue, number_of_employees, industry_id
)
VALUES (
  'a0c00000-0000-4000-8000-100000000002',

  'TechBridge Solutions',

  'https://techbridge.io',

  '555-0200',

  'hello@techbridge.io',

  'San Francisco',

  'CA',

  'US',

  45000000,

  220,

  '10100070-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.accounts (
  id, name, website, phone, email, billing_city, billing_state, billing_country, annual_revenue, number_of_employees, industry_id
)
VALUES (
  'a0c00000-0000-4000-8000-100000000003',

  'CapStone Financial',

  'https://capstone-fin.com',

  '555-0300',

  'contact@capstone-fin.com',

  'New York',

  'NY',

  'US',

  90000000,

  450,

  '10100070-0000-4000-8000-100000000003'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.accounts (
  id, name, website, phone, email, billing_city, billing_state, billing_country, annual_revenue, number_of_employees, industry_id
)
VALUES (
  'a0c00000-0000-4000-8000-100000000004',

  'MediSystems Inc',

  'https://medisystems.com',

  '555-0400',

  'info@medisystems.com',

  'Chicago',

  'IL',

  'US',

  22000000,

  130,

  '10100070-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.accounts (
  id, name, website, phone, email, billing_city, billing_state, billing_country, annual_revenue, number_of_employees, industry_id
)
VALUES (
  'a0c00000-0000-4000-8000-100000000005',

  'RetailPlus Corp',

  'https://retailplus.com',

  '555-0500',

  'sales@retailplus.com',

  'Dallas',

  'TX',

  'US',

  18000000,

  110,

  '10100070-0000-4000-8000-100000000005'


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- Product
-- ----------------------------------------------------------------------------


INSERT INTO crm.products (
  id, name, product_code, description, list_price, is_active, family, pricebook_id
)
VALUES (
  '9700d000-0000-4000-8000-100000000001',

  'Enterprise Suite',

  'ENT-001',

  'Full-featured enterprise platform license',

  75000,

  true,

  'Software',

  '97000b00-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.products (
  id, name, product_code, description, list_price, is_active, family, pricebook_id
)
VALUES (
  '9700d000-0000-4000-8000-100000000002',

  'Professional Edition',

  'PRO-001',

  'Mid-market platform license',

  25000,

  true,

  'Software',

  '97000b00-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.products (
  id, name, product_code, description, list_price, is_active, family, pricebook_id
)
VALUES (
  '9700d000-0000-4000-8000-100000000003',

  'Implementation Services',

  'SVC-001',

  'Professional services for deployment',

  15000,

  true,

  'Services',

  '97000b00-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.products (
  id, name, product_code, description, list_price, is_active, family, pricebook_id
)
VALUES (
  '9700d000-0000-4000-8000-100000000004',

  'Annual Support',

  'SUP-001',

  'Yearly support and maintenance contract',

  7500,

  true,

  'Support',

  '97000b00-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.products (
  id, name, product_code, description, list_price, is_active, family, pricebook_id
)
VALUES (
  '9700d000-0000-4000-8000-100000000005',

  'Training Package',

  'TRN-001',

  'User and admin training bundle',

  5000,

  true,

  'Services',

  '97000b00-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- Contact
-- ----------------------------------------------------------------------------


INSERT INTO crm.contacts (
  id, first_name, last_name, email, phone, title, department, account_id
)
VALUES (
  'c0c00000-0000-4000-8000-100000000001',

  'Sarah',

  'Mitchell',

  's.mitchell@acmedental.com',

  '555-0101',

  'VP Operations',

  'Operations',

  'a0c00000-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.contacts (
  id, first_name, last_name, email, phone, title, department, account_id
)
VALUES (
  'c0c00000-0000-4000-8000-100000000002',

  'James',

  'Okafor',

  'j.okafor@techbridge.io',

  '555-0201',

  'CTO',

  'Engineering',

  'a0c00000-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.contacts (
  id, first_name, last_name, email, phone, title, department, account_id
)
VALUES (
  'c0c00000-0000-4000-8000-100000000003',

  'Lisa',

  'Chen',

  'l.chen@capstone-fin.com',

  '555-0301',

  'CFO',

  'Finance',

  'a0c00000-0000-4000-8000-100000000003'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.contacts (
  id, first_name, last_name, email, phone, title, department, account_id
)
VALUES (
  'c0c00000-0000-4000-8000-100000000004',

  'David',

  'Torres',

  'd.torres@medisystems.com',

  '555-0401',

  'Director of IT',

  'Information Technology',

  'a0c00000-0000-4000-8000-100000000004'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.contacts (
  id, first_name, last_name, email, phone, title, department, account_id
)
VALUES (
  'c0c00000-0000-4000-8000-100000000005',

  'Priya',

  'Sharma',

  'p.sharma@retailplus.com',

  '555-0501',

  'VP Purchasing',

  'Procurement',

  'a0c00000-0000-4000-8000-100000000005'


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- Lead
-- ----------------------------------------------------------------------------


INSERT INTO crm.leads (
  id, first_name, last_name, email, phone, company, title, is_converted, status_id, source_id, industry_id
)
VALUES (
  '1eadc000-0000-4000-8000-100000000001',

  'Michael',

  'Nguyen',

  'm.nguyen@sunrise-dental.com',

  '555-1001',

  'Sunrise Dental',

  'Office Manager',

  false,

  '1eadcc00-0000-4000-8000-100000000001',

  '1eadcc01-0000-4000-8000-100000000001',

  '10100070-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.leads (
  id, first_name, last_name, email, phone, company, title, is_converted, status_id, source_id, industry_id
)
VALUES (
  '1eadc000-0000-4000-8000-100000000002',

  'Amanda',

  'Brooks',

  'a.brooks@vistaclinic.com',

  '555-1002',

  'Vista Clinic Group',

  'Practice Administrator',

  false,

  '1eadcc00-0000-4000-8000-100000000002',

  '1eadcc01-0000-4000-8000-100000000003',

  '10100070-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.leads (
  id, first_name, last_name, email, phone, company, title, is_converted, status_id, source_id, industry_id
)
VALUES (
  '1eadc000-0000-4000-8000-100000000003',

  'Robert',

  'Kim',

  'r.kim@nextech.co',

  '555-1003',

  'NexTech Co',

  'IT Director',

  false,

  '1eadcc00-0000-4000-8000-100000000003',

  '1eadcc01-0000-4000-8000-100000000004',

  '10100070-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.leads (
  id, first_name, last_name, email, phone, company, title, is_converted, status_id, source_id, industry_id
)
VALUES (
  '1eadc000-0000-4000-8000-100000000004',

  'Elena',

  'Vasquez',

  'e.vasquez@meridian-health.org',

  '555-1004',

  'Meridian Health',

  'COO',

  false,

  '1eadcc00-0000-4000-8000-100000000001',

  '1eadcc01-0000-4000-8000-100000000002',

  '10100070-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.leads (
  id, first_name, last_name, email, phone, company, title, is_converted, status_id, source_id, industry_id
)
VALUES (
  '1eadc000-0000-4000-8000-100000000005',

  'Thomas',

  'Adeyemi',

  't.adeyemi@freshmarket.com',

  '555-1005',

  'Fresh Market Chain',

  'VP Technology',

  false,

  '1eadcc00-0000-4000-8000-100000000002',

  '1eadcc01-0000-4000-8000-100000000005',

  '10100070-0000-4000-8000-100000000005'


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- Opportunity
-- ----------------------------------------------------------------------------


INSERT INTO crm.opportunities (
  id, name, amount, close_date, lead_source, account_id, stage_id
)
VALUES (
  '099c0000-0000-4000-8000-100000000001',

  'Acme Dental - Enterprise Suite',

  97500,

  '2026-06-30',

  'Partner Referral',

  'a0c00000-0000-4000-8000-100000000001',

  '0998a900-0000-4000-8000-100000000003'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunities (
  id, name, amount, close_date, lead_source, account_id, stage_id
)
VALUES (
  '099c0000-0000-4000-8000-100000000002',

  'TechBridge - Platform Expansion',

  145000,

  '2026-07-31',

  'Web',

  'a0c00000-0000-4000-8000-100000000002',

  '0998a900-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunities (
  id, name, amount, close_date, lead_source, account_id, stage_id
)
VALUES (
  '099c0000-0000-4000-8000-100000000003',

  'CapStone - Analytics Module',

  32500,

  '2026-05-31',

  'Trade Show',

  'a0c00000-0000-4000-8000-100000000003',

  '0998a900-0000-4000-8000-100000000004'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunities (
  id, name, amount, close_date, lead_source, account_id, stage_id
)
VALUES (
  '099c0000-0000-4000-8000-100000000004',

  'MediSystems - Pro Edition',

  47500,

  '2026-08-31',

  'Phone Inquiry',

  'a0c00000-0000-4000-8000-100000000004',

  '0998a900-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunities (
  id, name, amount, close_date, lead_source, account_id, stage_id
)
VALUES (
  '099c0000-0000-4000-8000-100000000005',

  'RetailPlus - Services Bundle',

  27500,

  '2026-09-30',

  'Employee Referral',

  'a0c00000-0000-4000-8000-100000000005',

  '0998a900-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- Activity
-- ----------------------------------------------------------------------------


INSERT INTO crm.activities (
  id, subject, description, activity_date, is_closed, priority, status, type_id, account_id, contact_id, opportunity_id
)
VALUES (
  'ac710007-0000-4000-8000-100000000001',

  'Discovery Call - Acme Dental',

  'Initial discovery call to understand requirements',

  '2026-05-01',

  true,

  'High',

  'Completed',

  'ac71ec00-0000-4000-8000-100000000002',

  'a0c00000-0000-4000-8000-100000000001',

  'c0c00000-0000-4000-8000-100000000001',

  '099c0000-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.activities (
  id, subject, description, activity_date, is_closed, priority, status, type_id, account_id, contact_id, opportunity_id
)
VALUES (
  'ac710007-0000-4000-8000-100000000002',

  'Demo - TechBridge Platform',

  'Full product demonstration for expansion proposal',

  '2026-05-10',

  true,

  'High',

  'Completed',

  'ac71ec00-0000-4000-8000-100000000003',

  'a0c00000-0000-4000-8000-100000000002',

  'c0c00000-0000-4000-8000-100000000002',

  '099c0000-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.activities (
  id, subject, description, activity_date, is_closed, priority, status, type_id, account_id, contact_id, opportunity_id
)
VALUES (
  'ac710007-0000-4000-8000-100000000003',

  'Follow-up Email - CapStone Analytics',

  'Sent ROI analysis and case studies',

  '2026-05-12',

  true,

  'Normal',

  'Completed',

  'ac71ec00-0000-4000-8000-100000000001',

  'a0c00000-0000-4000-8000-100000000003',

  'c0c00000-0000-4000-8000-100000000003',

  '099c0000-0000-4000-8000-100000000003'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.activities (
  id, subject, description, activity_date, is_closed, priority, status, type_id, account_id, contact_id, opportunity_id
)
VALUES (
  'ac710007-0000-4000-8000-100000000004',

  'Intro Call - MediSystems',

  'First contact, qualify needs and budget',

  '2026-05-19',

  false,

  'Normal',

  'Planned',

  'ac71ec00-0000-4000-8000-100000000002',

  'a0c00000-0000-4000-8000-100000000004',

  'c0c00000-0000-4000-8000-100000000004',

  '099c0000-0000-4000-8000-100000000004'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.activities (
  id, subject, description, activity_date, is_closed, priority, status, type_id, account_id, contact_id, opportunity_id
)
VALUES (
  'ac710007-0000-4000-8000-100000000005',

  'Proposal Review Meeting - RetailPlus',

  'Walk through the services bundle proposal',

  '2026-05-28',

  false,

  'Normal',

  'Planned',

  'ac71ec00-0000-4000-8000-100000000003',

  'a0c00000-0000-4000-8000-100000000005',

  'c0c00000-0000-4000-8000-100000000005',

  '099c0000-0000-4000-8000-100000000005'


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- OpportunityContact
-- ----------------------------------------------------------------------------


INSERT INTO crm.opportunity_contacts (
  id, opportunity_id, contact_id
)
VALUES (
  '0c0c0000-0000-4000-8000-100000000001',

  '099c0000-0000-4000-8000-100000000001',

  'c0c00000-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunity_contacts (
  id, opportunity_id, contact_id
)
VALUES (
  '0c0c0000-0000-4000-8000-100000000002',

  '099c0000-0000-4000-8000-100000000002',

  'c0c00000-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunity_contacts (
  id, opportunity_id, contact_id
)
VALUES (
  '0c0c0000-0000-4000-8000-100000000003',

  '099c0000-0000-4000-8000-100000000003',

  'c0c00000-0000-4000-8000-100000000003'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunity_contacts (
  id, opportunity_id, contact_id
)
VALUES (
  '0c0c0000-0000-4000-8000-100000000004',

  '099c0000-0000-4000-8000-100000000004',

  'c0c00000-0000-4000-8000-100000000004'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunity_contacts (
  id, opportunity_id, contact_id
)
VALUES (
  '0c0c0000-0000-4000-8000-100000000005',

  '099c0000-0000-4000-8000-100000000005',

  'c0c00000-0000-4000-8000-100000000005'


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- Quote
-- ----------------------------------------------------------------------------


INSERT INTO crm.quotes (
  id, name, quote_number, expiration_date, subtotal, total_price, opportunity_id, account_id, status_id
)
VALUES (
  '9407e000-0000-4000-8000-100000000001',

  'Q-2026-001 Acme Enterprise',

  'Q-2026-001',

  '2026-07-31',

  97500,

  97500,

  '099c0000-0000-4000-8000-100000000001',

  'a0c00000-0000-4000-8000-100000000001',

  '9407ec00-0000-4000-8000-100000000003'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quotes (
  id, name, quote_number, expiration_date, subtotal, total_price, opportunity_id, account_id, status_id
)
VALUES (
  '9407e000-0000-4000-8000-100000000002',

  'Q-2026-002 TechBridge Platform',

  'Q-2026-002',

  '2026-08-31',

  145000,

  145000,

  '099c0000-0000-4000-8000-100000000002',

  'a0c00000-0000-4000-8000-100000000002',

  '9407ec00-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quotes (
  id, name, quote_number, expiration_date, subtotal, total_price, opportunity_id, account_id, status_id
)
VALUES (
  '9407e000-0000-4000-8000-100000000003',

  'Q-2026-003 CapStone Analytics',

  'Q-2026-003',

  '2026-06-15',

  32500,

  32500,

  '099c0000-0000-4000-8000-100000000003',

  'a0c00000-0000-4000-8000-100000000003',

  '9407ec00-0000-4000-8000-100000000004'


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- QuoteLineItem
-- ----------------------------------------------------------------------------


INSERT INTO crm.quote_line_items (
  id, quantity, unit_price, total_price, sort_order, quote_id, product_id
)
VALUES (
  '9407e110-0000-4000-8000-100000000001',

  1,

  75000,

  75000,

  1,

  '9407e000-0000-4000-8000-100000000001',

  '9700d000-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_line_items (
  id, quantity, unit_price, total_price, sort_order, quote_id, product_id
)
VALUES (
  '9407e110-0000-4000-8000-100000000002',

  1,

  15000,

  15000,

  2,

  '9407e000-0000-4000-8000-100000000001',

  '9700d000-0000-4000-8000-100000000003'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_line_items (
  id, quantity, unit_price, total_price, sort_order, quote_id, product_id
)
VALUES (
  '9407e110-0000-4000-8000-100000000003',

  1,

  7500,

  7500,

  3,

  '9407e000-0000-4000-8000-100000000001',

  '9700d000-0000-4000-8000-100000000004'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_line_items (
  id, quantity, unit_price, total_price, sort_order, quote_id, product_id
)
VALUES (
  '9407e110-0000-4000-8000-100000000004',

  5,

  25000,

  125000,

  1,

  '9407e000-0000-4000-8000-100000000002',

  '9700d000-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_line_items (
  id, quantity, unit_price, total_price, sort_order, quote_id, product_id
)
VALUES (
  '9407e110-0000-4000-8000-100000000005',

  1,

  20000,

  20000,

  2,

  '9407e000-0000-4000-8000-100000000002',

  '9700d000-0000-4000-8000-100000000003'


)
ON CONFLICT (id) DO NOTHING;




END $$;
