--
--    Generated by app_gen.
--    by app_gen/_templates/database/mssql/seed_sql/_mod.j2
--    Seed data for crm schema (T-SQL dialect)
--




-- ----------------------------------------------------------------------------
-- ActivityType
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[activity_types] WHERE [id] = N'ac71ec00-0000-4000-8000-100000000001')
    INSERT INTO [crm].[activity_types] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'ac71ec00-0000-4000-8000-100000000001',
        N'Email',
        10

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[activity_types] WHERE [id] = N'ac71ec00-0000-4000-8000-100000000002')
    INSERT INTO [crm].[activity_types] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'ac71ec00-0000-4000-8000-100000000002',
        N'Call',
        20

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[activity_types] WHERE [id] = N'ac71ec00-0000-4000-8000-100000000003')
    INSERT INTO [crm].[activity_types] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'ac71ec00-0000-4000-8000-100000000003',
        N'Meeting',
        30

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[activity_types] WHERE [id] = N'ac71ec00-0000-4000-8000-100000000004')
    INSERT INTO [crm].[activity_types] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'ac71ec00-0000-4000-8000-100000000004',
        N'Task',
        40

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[activity_types] WHERE [id] = N'ac71ec00-0000-4000-8000-100000000005')
    INSERT INTO [crm].[activity_types] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'ac71ec00-0000-4000-8000-100000000005',
        N'Note',
        50

    );





-- ----------------------------------------------------------------------------
-- Industry
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[industries] WHERE [id] = N'10100070-0000-4000-8000-100000000001')
    INSERT INTO [crm].[industries] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'10100070-0000-4000-8000-100000000001',
        N'Healthcare',
        10

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[industries] WHERE [id] = N'10100070-0000-4000-8000-100000000002')
    INSERT INTO [crm].[industries] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'10100070-0000-4000-8000-100000000002',
        N'Technology',
        20

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[industries] WHERE [id] = N'10100070-0000-4000-8000-100000000003')
    INSERT INTO [crm].[industries] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'10100070-0000-4000-8000-100000000003',
        N'Financial Services',
        30

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[industries] WHERE [id] = N'10100070-0000-4000-8000-100000000004')
    INSERT INTO [crm].[industries] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'10100070-0000-4000-8000-100000000004',
        N'Manufacturing',
        40

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[industries] WHERE [id] = N'10100070-0000-4000-8000-100000000005')
    INSERT INTO [crm].[industries] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'10100070-0000-4000-8000-100000000005',
        N'Retail',
        50

    );





-- ----------------------------------------------------------------------------
-- LeadSource
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[lead_sources] WHERE [id] = N'1eadcc01-0000-4000-8000-100000000001')
    INSERT INTO [crm].[lead_sources] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'1eadcc01-0000-4000-8000-100000000001',
        N'Web',
        10

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[lead_sources] WHERE [id] = N'1eadcc01-0000-4000-8000-100000000002')
    INSERT INTO [crm].[lead_sources] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'1eadcc01-0000-4000-8000-100000000002',
        N'Phone Inquiry',
        20

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[lead_sources] WHERE [id] = N'1eadcc01-0000-4000-8000-100000000003')
    INSERT INTO [crm].[lead_sources] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'1eadcc01-0000-4000-8000-100000000003',
        N'Partner Referral',
        30

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[lead_sources] WHERE [id] = N'1eadcc01-0000-4000-8000-100000000004')
    INSERT INTO [crm].[lead_sources] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'1eadcc01-0000-4000-8000-100000000004',
        N'Trade Show',
        40

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[lead_sources] WHERE [id] = N'1eadcc01-0000-4000-8000-100000000005')
    INSERT INTO [crm].[lead_sources] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'1eadcc01-0000-4000-8000-100000000005',
        N'Employee Referral',
        50

    );





-- ----------------------------------------------------------------------------
-- LeadStatus
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[lead_statuses] WHERE [id] = N'1eadcc00-0000-4000-8000-100000000001')
    INSERT INTO [crm].[lead_statuses] (
        [id], [name], [is_converted], [sort_order]
    )
    VALUES (
        N'1eadcc00-0000-4000-8000-100000000001',
        N'New',
        0,
        10

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[lead_statuses] WHERE [id] = N'1eadcc00-0000-4000-8000-100000000002')
    INSERT INTO [crm].[lead_statuses] (
        [id], [name], [is_converted], [sort_order]
    )
    VALUES (
        N'1eadcc00-0000-4000-8000-100000000002',
        N'Contacted',
        0,
        20

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[lead_statuses] WHERE [id] = N'1eadcc00-0000-4000-8000-100000000003')
    INSERT INTO [crm].[lead_statuses] (
        [id], [name], [is_converted], [sort_order]
    )
    VALUES (
        N'1eadcc00-0000-4000-8000-100000000003',
        N'Qualified',
        0,
        30

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[lead_statuses] WHERE [id] = N'1eadcc00-0000-4000-8000-100000000004')
    INSERT INTO [crm].[lead_statuses] (
        [id], [name], [is_converted], [sort_order]
    )
    VALUES (
        N'1eadcc00-0000-4000-8000-100000000004',
        N'Unqualified',
        0,
        40

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[lead_statuses] WHERE [id] = N'1eadcc00-0000-4000-8000-100000000005')
    INSERT INTO [crm].[lead_statuses] (
        [id], [name], [is_converted], [sort_order]
    )
    VALUES (
        N'1eadcc00-0000-4000-8000-100000000005',
        N'Converted',
        1,
        50

    );





-- ----------------------------------------------------------------------------
-- OpportunityStage
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[opportunity_stages] WHERE [id] = N'0998a900-0000-4000-8000-100000000001')
    INSERT INTO [crm].[opportunity_stages] (
        [id], [name], [probability], [is_closed], [is_won], [sort_order]
    )
    VALUES (
        N'0998a900-0000-4000-8000-100000000001',
        N'Prospecting',
        0.1,
        0,
        0,
        10

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunity_stages] WHERE [id] = N'0998a900-0000-4000-8000-100000000002')
    INSERT INTO [crm].[opportunity_stages] (
        [id], [name], [probability], [is_closed], [is_won], [sort_order]
    )
    VALUES (
        N'0998a900-0000-4000-8000-100000000002',
        N'Qualification',
        0.2,
        0,
        0,
        20

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunity_stages] WHERE [id] = N'0998a900-0000-4000-8000-100000000003')
    INSERT INTO [crm].[opportunity_stages] (
        [id], [name], [probability], [is_closed], [is_won], [sort_order]
    )
    VALUES (
        N'0998a900-0000-4000-8000-100000000003',
        N'Proposal',
        0.5,
        0,
        0,
        30

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunity_stages] WHERE [id] = N'0998a900-0000-4000-8000-100000000004')
    INSERT INTO [crm].[opportunity_stages] (
        [id], [name], [probability], [is_closed], [is_won], [sort_order]
    )
    VALUES (
        N'0998a900-0000-4000-8000-100000000004',
        N'Closed Won',
        1,
        1,
        1,
        40

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunity_stages] WHERE [id] = N'0998a900-0000-4000-8000-100000000005')
    INSERT INTO [crm].[opportunity_stages] (
        [id], [name], [probability], [is_closed], [is_won], [sort_order]
    )
    VALUES (
        N'0998a900-0000-4000-8000-100000000005',
        N'Closed Lost',
        0,
        1,
        0,
        50

    );





-- ----------------------------------------------------------------------------
-- Pricebook
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[pricebooks] WHERE [id] = N'97000b00-0000-4000-8000-100000000001')
    INSERT INTO [crm].[pricebooks] (
        [id], [name], [description], [is_active], [is_standard]
    )
    VALUES (
        N'97000b00-0000-4000-8000-100000000001',
        N'Standard Price Book',
        N'Default price book for all products',
        1,
        1

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[pricebooks] WHERE [id] = N'97000b00-0000-4000-8000-100000000002')
    INSERT INTO [crm].[pricebooks] (
        [id], [name], [description], [is_active], [is_standard]
    )
    VALUES (
        N'97000b00-0000-4000-8000-100000000002',
        N'Partner Price Book',
        N'Discounted pricing for channel partners',
        1,
        0

    );





-- ----------------------------------------------------------------------------
-- QuoteStatus
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[quote_statuses] WHERE [id] = N'9407ec00-0000-4000-8000-100000000001')
    INSERT INTO [crm].[quote_statuses] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'9407ec00-0000-4000-8000-100000000001',
        N'Draft',
        10

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_statuses] WHERE [id] = N'9407ec00-0000-4000-8000-100000000002')
    INSERT INTO [crm].[quote_statuses] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'9407ec00-0000-4000-8000-100000000002',
        N'Needs Review',
        20

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_statuses] WHERE [id] = N'9407ec00-0000-4000-8000-100000000003')
    INSERT INTO [crm].[quote_statuses] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'9407ec00-0000-4000-8000-100000000003',
        N'Delivered',
        30

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_statuses] WHERE [id] = N'9407ec00-0000-4000-8000-100000000004')
    INSERT INTO [crm].[quote_statuses] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'9407ec00-0000-4000-8000-100000000004',
        N'Accepted',
        40

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_statuses] WHERE [id] = N'9407ec00-0000-4000-8000-100000000005')
    INSERT INTO [crm].[quote_statuses] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'9407ec00-0000-4000-8000-100000000005',
        N'Rejected',
        50

    );





-- ----------------------------------------------------------------------------
-- Account
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[accounts] WHERE [id] = N'a0c00000-0000-4000-8000-100000000001')
    INSERT INTO [crm].[accounts] (
        [id], [name], [website], [phone], [email], [billing_city], [billing_state], [billing_country], [annual_revenue], [number_of_employees], [industry_id]
    )
    VALUES (
        N'a0c00000-0000-4000-8000-100000000001',
        N'Acme Dental Group',
        N'https://acmedental.com',
        N'555-0100',
        N'info@acmedental.com',
        N'Austin',
        N'TX',
        N'US',
        12000000,
        85,
        N'10100070-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[accounts] WHERE [id] = N'a0c00000-0000-4000-8000-100000000002')
    INSERT INTO [crm].[accounts] (
        [id], [name], [website], [phone], [email], [billing_city], [billing_state], [billing_country], [annual_revenue], [number_of_employees], [industry_id]
    )
    VALUES (
        N'a0c00000-0000-4000-8000-100000000002',
        N'TechBridge Solutions',
        N'https://techbridge.io',
        N'555-0200',
        N'hello@techbridge.io',
        N'San Francisco',
        N'CA',
        N'US',
        45000000,
        220,
        N'10100070-0000-4000-8000-100000000002'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[accounts] WHERE [id] = N'a0c00000-0000-4000-8000-100000000003')
    INSERT INTO [crm].[accounts] (
        [id], [name], [website], [phone], [email], [billing_city], [billing_state], [billing_country], [annual_revenue], [number_of_employees], [industry_id]
    )
    VALUES (
        N'a0c00000-0000-4000-8000-100000000003',
        N'CapStone Financial',
        N'https://capstone-fin.com',
        N'555-0300',
        N'contact@capstone-fin.com',
        N'New York',
        N'NY',
        N'US',
        90000000,
        450,
        N'10100070-0000-4000-8000-100000000003'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[accounts] WHERE [id] = N'a0c00000-0000-4000-8000-100000000004')
    INSERT INTO [crm].[accounts] (
        [id], [name], [website], [phone], [email], [billing_city], [billing_state], [billing_country], [annual_revenue], [number_of_employees], [industry_id]
    )
    VALUES (
        N'a0c00000-0000-4000-8000-100000000004',
        N'MediSystems Inc',
        N'https://medisystems.com',
        N'555-0400',
        N'info@medisystems.com',
        N'Chicago',
        N'IL',
        N'US',
        22000000,
        130,
        N'10100070-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[accounts] WHERE [id] = N'a0c00000-0000-4000-8000-100000000005')
    INSERT INTO [crm].[accounts] (
        [id], [name], [website], [phone], [email], [billing_city], [billing_state], [billing_country], [annual_revenue], [number_of_employees], [industry_id]
    )
    VALUES (
        N'a0c00000-0000-4000-8000-100000000005',
        N'RetailPlus Corp',
        N'https://retailplus.com',
        N'555-0500',
        N'sales@retailplus.com',
        N'Dallas',
        N'TX',
        N'US',
        18000000,
        110,
        N'10100070-0000-4000-8000-100000000005'

    );





-- ----------------------------------------------------------------------------
-- Product
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[products] WHERE [id] = N'9700d000-0000-4000-8000-100000000001')
    INSERT INTO [crm].[products] (
        [id], [name], [product_code], [description], [list_price], [is_active], [family], [pricebook_id]
    )
    VALUES (
        N'9700d000-0000-4000-8000-100000000001',
        N'Enterprise Suite',
        N'ENT-001',
        N'Full-featured enterprise platform license',
        75000,
        1,
        N'Software',
        N'97000b00-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[products] WHERE [id] = N'9700d000-0000-4000-8000-100000000002')
    INSERT INTO [crm].[products] (
        [id], [name], [product_code], [description], [list_price], [is_active], [family], [pricebook_id]
    )
    VALUES (
        N'9700d000-0000-4000-8000-100000000002',
        N'Professional Edition',
        N'PRO-001',
        N'Mid-market platform license',
        25000,
        1,
        N'Software',
        N'97000b00-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[products] WHERE [id] = N'9700d000-0000-4000-8000-100000000003')
    INSERT INTO [crm].[products] (
        [id], [name], [product_code], [description], [list_price], [is_active], [family], [pricebook_id]
    )
    VALUES (
        N'9700d000-0000-4000-8000-100000000003',
        N'Implementation Services',
        N'SVC-001',
        N'Professional services for deployment',
        15000,
        1,
        N'Services',
        N'97000b00-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[products] WHERE [id] = N'9700d000-0000-4000-8000-100000000004')
    INSERT INTO [crm].[products] (
        [id], [name], [product_code], [description], [list_price], [is_active], [family], [pricebook_id]
    )
    VALUES (
        N'9700d000-0000-4000-8000-100000000004',
        N'Annual Support',
        N'SUP-001',
        N'Yearly support and maintenance contract',
        7500,
        1,
        N'Support',
        N'97000b00-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[products] WHERE [id] = N'9700d000-0000-4000-8000-100000000005')
    INSERT INTO [crm].[products] (
        [id], [name], [product_code], [description], [list_price], [is_active], [family], [pricebook_id]
    )
    VALUES (
        N'9700d000-0000-4000-8000-100000000005',
        N'Training Package',
        N'TRN-001',
        N'User and admin training bundle',
        5000,
        1,
        N'Services',
        N'97000b00-0000-4000-8000-100000000001'

    );





-- ----------------------------------------------------------------------------
-- Contact
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[contacts] WHERE [id] = N'c0c00000-0000-4000-8000-100000000001')
    INSERT INTO [crm].[contacts] (
        [id], [first_name], [last_name], [email], [phone], [title], [department], [account_id]
    )
    VALUES (
        N'c0c00000-0000-4000-8000-100000000001',
        N'Sarah',
        N'Mitchell',
        N's.mitchell@acmedental.com',
        N'555-0101',
        N'VP Operations',
        N'Operations',
        N'a0c00000-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[contacts] WHERE [id] = N'c0c00000-0000-4000-8000-100000000002')
    INSERT INTO [crm].[contacts] (
        [id], [first_name], [last_name], [email], [phone], [title], [department], [account_id]
    )
    VALUES (
        N'c0c00000-0000-4000-8000-100000000002',
        N'James',
        N'Okafor',
        N'j.okafor@techbridge.io',
        N'555-0201',
        N'CTO',
        N'Engineering',
        N'a0c00000-0000-4000-8000-100000000002'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[contacts] WHERE [id] = N'c0c00000-0000-4000-8000-100000000003')
    INSERT INTO [crm].[contacts] (
        [id], [first_name], [last_name], [email], [phone], [title], [department], [account_id]
    )
    VALUES (
        N'c0c00000-0000-4000-8000-100000000003',
        N'Lisa',
        N'Chen',
        N'l.chen@capstone-fin.com',
        N'555-0301',
        N'CFO',
        N'Finance',
        N'a0c00000-0000-4000-8000-100000000003'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[contacts] WHERE [id] = N'c0c00000-0000-4000-8000-100000000004')
    INSERT INTO [crm].[contacts] (
        [id], [first_name], [last_name], [email], [phone], [title], [department], [account_id]
    )
    VALUES (
        N'c0c00000-0000-4000-8000-100000000004',
        N'David',
        N'Torres',
        N'd.torres@medisystems.com',
        N'555-0401',
        N'Director of IT',
        N'Information Technology',
        N'a0c00000-0000-4000-8000-100000000004'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[contacts] WHERE [id] = N'c0c00000-0000-4000-8000-100000000005')
    INSERT INTO [crm].[contacts] (
        [id], [first_name], [last_name], [email], [phone], [title], [department], [account_id]
    )
    VALUES (
        N'c0c00000-0000-4000-8000-100000000005',
        N'Priya',
        N'Sharma',
        N'p.sharma@retailplus.com',
        N'555-0501',
        N'VP Purchasing',
        N'Procurement',
        N'a0c00000-0000-4000-8000-100000000005'

    );





-- ----------------------------------------------------------------------------
-- Lead
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[leads] WHERE [id] = N'1eadc000-0000-4000-8000-100000000001')
    INSERT INTO [crm].[leads] (
        [id], [first_name], [last_name], [email], [phone], [company], [title], [is_converted], [status_id], [source_id], [industry_id]
    )
    VALUES (
        N'1eadc000-0000-4000-8000-100000000001',
        N'Michael',
        N'Nguyen',
        N'm.nguyen@sunrise-dental.com',
        N'555-1001',
        N'Sunrise Dental',
        N'Office Manager',
        0,
        N'1eadcc00-0000-4000-8000-100000000001',
        N'1eadcc01-0000-4000-8000-100000000001',
        N'10100070-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[leads] WHERE [id] = N'1eadc000-0000-4000-8000-100000000002')
    INSERT INTO [crm].[leads] (
        [id], [first_name], [last_name], [email], [phone], [company], [title], [is_converted], [status_id], [source_id], [industry_id]
    )
    VALUES (
        N'1eadc000-0000-4000-8000-100000000002',
        N'Amanda',
        N'Brooks',
        N'a.brooks@vistaclinic.com',
        N'555-1002',
        N'Vista Clinic Group',
        N'Practice Administrator',
        0,
        N'1eadcc00-0000-4000-8000-100000000002',
        N'1eadcc01-0000-4000-8000-100000000003',
        N'10100070-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[leads] WHERE [id] = N'1eadc000-0000-4000-8000-100000000003')
    INSERT INTO [crm].[leads] (
        [id], [first_name], [last_name], [email], [phone], [company], [title], [is_converted], [status_id], [source_id], [industry_id]
    )
    VALUES (
        N'1eadc000-0000-4000-8000-100000000003',
        N'Robert',
        N'Kim',
        N'r.kim@nextech.co',
        N'555-1003',
        N'NexTech Co',
        N'IT Director',
        0,
        N'1eadcc00-0000-4000-8000-100000000003',
        N'1eadcc01-0000-4000-8000-100000000004',
        N'10100070-0000-4000-8000-100000000002'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[leads] WHERE [id] = N'1eadc000-0000-4000-8000-100000000004')
    INSERT INTO [crm].[leads] (
        [id], [first_name], [last_name], [email], [phone], [company], [title], [is_converted], [status_id], [source_id], [industry_id]
    )
    VALUES (
        N'1eadc000-0000-4000-8000-100000000004',
        N'Elena',
        N'Vasquez',
        N'e.vasquez@meridian-health.org',
        N'555-1004',
        N'Meridian Health',
        N'COO',
        0,
        N'1eadcc00-0000-4000-8000-100000000001',
        N'1eadcc01-0000-4000-8000-100000000002',
        N'10100070-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[leads] WHERE [id] = N'1eadc000-0000-4000-8000-100000000005')
    INSERT INTO [crm].[leads] (
        [id], [first_name], [last_name], [email], [phone], [company], [title], [is_converted], [status_id], [source_id], [industry_id]
    )
    VALUES (
        N'1eadc000-0000-4000-8000-100000000005',
        N'Thomas',
        N'Adeyemi',
        N't.adeyemi@freshmarket.com',
        N'555-1005',
        N'Fresh Market Chain',
        N'VP Technology',
        0,
        N'1eadcc00-0000-4000-8000-100000000002',
        N'1eadcc01-0000-4000-8000-100000000005',
        N'10100070-0000-4000-8000-100000000005'

    );





-- ----------------------------------------------------------------------------
-- Opportunity
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[opportunities] WHERE [id] = N'099c0000-0000-4000-8000-100000000001')
    INSERT INTO [crm].[opportunities] (
        [id], [name], [amount], [close_date], [lead_source], [account_id], [stage_id]
    )
    VALUES (
        N'099c0000-0000-4000-8000-100000000001',
        N'Acme Dental - Enterprise Suite',
        97500,
        N'2026-06-30',
        N'Partner Referral',
        N'a0c00000-0000-4000-8000-100000000001',
        N'0998a900-0000-4000-8000-100000000003'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunities] WHERE [id] = N'099c0000-0000-4000-8000-100000000002')
    INSERT INTO [crm].[opportunities] (
        [id], [name], [amount], [close_date], [lead_source], [account_id], [stage_id]
    )
    VALUES (
        N'099c0000-0000-4000-8000-100000000002',
        N'TechBridge - Platform Expansion',
        145000,
        N'2026-07-31',
        N'Web',
        N'a0c00000-0000-4000-8000-100000000002',
        N'0998a900-0000-4000-8000-100000000002'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunities] WHERE [id] = N'099c0000-0000-4000-8000-100000000003')
    INSERT INTO [crm].[opportunities] (
        [id], [name], [amount], [close_date], [lead_source], [account_id], [stage_id]
    )
    VALUES (
        N'099c0000-0000-4000-8000-100000000003',
        N'CapStone - Analytics Module',
        32500,
        N'2026-05-31',
        N'Trade Show',
        N'a0c00000-0000-4000-8000-100000000003',
        N'0998a900-0000-4000-8000-100000000004'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunities] WHERE [id] = N'099c0000-0000-4000-8000-100000000004')
    INSERT INTO [crm].[opportunities] (
        [id], [name], [amount], [close_date], [lead_source], [account_id], [stage_id]
    )
    VALUES (
        N'099c0000-0000-4000-8000-100000000004',
        N'MediSystems - Pro Edition',
        47500,
        N'2026-08-31',
        N'Phone Inquiry',
        N'a0c00000-0000-4000-8000-100000000004',
        N'0998a900-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunities] WHERE [id] = N'099c0000-0000-4000-8000-100000000005')
    INSERT INTO [crm].[opportunities] (
        [id], [name], [amount], [close_date], [lead_source], [account_id], [stage_id]
    )
    VALUES (
        N'099c0000-0000-4000-8000-100000000005',
        N'RetailPlus - Services Bundle',
        27500,
        N'2026-09-30',
        N'Employee Referral',
        N'a0c00000-0000-4000-8000-100000000005',
        N'0998a900-0000-4000-8000-100000000002'

    );





-- ----------------------------------------------------------------------------
-- Activity
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[activities] WHERE [id] = N'ac710007-0000-4000-8000-100000000001')
    INSERT INTO [crm].[activities] (
        [id], [subject], [description], [activity_date], [is_closed], [priority], [status], [type_id], [account_id], [contact_id], [opportunity_id]
    )
    VALUES (
        N'ac710007-0000-4000-8000-100000000001',
        N'Discovery Call - Acme Dental',
        N'Initial discovery call to understand requirements',
        N'2026-05-01',
        1,
        N'High',
        N'Completed',
        N'ac71ec00-0000-4000-8000-100000000002',
        N'a0c00000-0000-4000-8000-100000000001',
        N'c0c00000-0000-4000-8000-100000000001',
        N'099c0000-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[activities] WHERE [id] = N'ac710007-0000-4000-8000-100000000002')
    INSERT INTO [crm].[activities] (
        [id], [subject], [description], [activity_date], [is_closed], [priority], [status], [type_id], [account_id], [contact_id], [opportunity_id]
    )
    VALUES (
        N'ac710007-0000-4000-8000-100000000002',
        N'Demo - TechBridge Platform',
        N'Full product demonstration for expansion proposal',
        N'2026-05-10',
        1,
        N'High',
        N'Completed',
        N'ac71ec00-0000-4000-8000-100000000003',
        N'a0c00000-0000-4000-8000-100000000002',
        N'c0c00000-0000-4000-8000-100000000002',
        N'099c0000-0000-4000-8000-100000000002'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[activities] WHERE [id] = N'ac710007-0000-4000-8000-100000000003')
    INSERT INTO [crm].[activities] (
        [id], [subject], [description], [activity_date], [is_closed], [priority], [status], [type_id], [account_id], [contact_id], [opportunity_id]
    )
    VALUES (
        N'ac710007-0000-4000-8000-100000000003',
        N'Follow-up Email - CapStone Analytics',
        N'Sent ROI analysis and case studies',
        N'2026-05-12',
        1,
        N'Normal',
        N'Completed',
        N'ac71ec00-0000-4000-8000-100000000001',
        N'a0c00000-0000-4000-8000-100000000003',
        N'c0c00000-0000-4000-8000-100000000003',
        N'099c0000-0000-4000-8000-100000000003'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[activities] WHERE [id] = N'ac710007-0000-4000-8000-100000000004')
    INSERT INTO [crm].[activities] (
        [id], [subject], [description], [activity_date], [is_closed], [priority], [status], [type_id], [account_id], [contact_id], [opportunity_id]
    )
    VALUES (
        N'ac710007-0000-4000-8000-100000000004',
        N'Intro Call - MediSystems',
        N'First contact, qualify needs and budget',
        N'2026-05-19',
        0,
        N'Normal',
        N'Planned',
        N'ac71ec00-0000-4000-8000-100000000002',
        N'a0c00000-0000-4000-8000-100000000004',
        N'c0c00000-0000-4000-8000-100000000004',
        N'099c0000-0000-4000-8000-100000000004'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[activities] WHERE [id] = N'ac710007-0000-4000-8000-100000000005')
    INSERT INTO [crm].[activities] (
        [id], [subject], [description], [activity_date], [is_closed], [priority], [status], [type_id], [account_id], [contact_id], [opportunity_id]
    )
    VALUES (
        N'ac710007-0000-4000-8000-100000000005',
        N'Proposal Review Meeting - RetailPlus',
        N'Walk through the services bundle proposal',
        N'2026-05-28',
        0,
        N'Normal',
        N'Planned',
        N'ac71ec00-0000-4000-8000-100000000003',
        N'a0c00000-0000-4000-8000-100000000005',
        N'c0c00000-0000-4000-8000-100000000005',
        N'099c0000-0000-4000-8000-100000000005'

    );





-- ----------------------------------------------------------------------------
-- OpportunityContact
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[opportunity_contacts] WHERE [id] = N'0c0c0000-0000-4000-8000-100000000001')
    INSERT INTO [crm].[opportunity_contacts] (
        [id], [opportunity_id], [contact_id]
    )
    VALUES (
        N'0c0c0000-0000-4000-8000-100000000001',
        N'099c0000-0000-4000-8000-100000000001',
        N'c0c00000-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunity_contacts] WHERE [id] = N'0c0c0000-0000-4000-8000-100000000002')
    INSERT INTO [crm].[opportunity_contacts] (
        [id], [opportunity_id], [contact_id]
    )
    VALUES (
        N'0c0c0000-0000-4000-8000-100000000002',
        N'099c0000-0000-4000-8000-100000000002',
        N'c0c00000-0000-4000-8000-100000000002'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunity_contacts] WHERE [id] = N'0c0c0000-0000-4000-8000-100000000003')
    INSERT INTO [crm].[opportunity_contacts] (
        [id], [opportunity_id], [contact_id]
    )
    VALUES (
        N'0c0c0000-0000-4000-8000-100000000003',
        N'099c0000-0000-4000-8000-100000000003',
        N'c0c00000-0000-4000-8000-100000000003'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunity_contacts] WHERE [id] = N'0c0c0000-0000-4000-8000-100000000004')
    INSERT INTO [crm].[opportunity_contacts] (
        [id], [opportunity_id], [contact_id]
    )
    VALUES (
        N'0c0c0000-0000-4000-8000-100000000004',
        N'099c0000-0000-4000-8000-100000000004',
        N'c0c00000-0000-4000-8000-100000000004'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunity_contacts] WHERE [id] = N'0c0c0000-0000-4000-8000-100000000005')
    INSERT INTO [crm].[opportunity_contacts] (
        [id], [opportunity_id], [contact_id]
    )
    VALUES (
        N'0c0c0000-0000-4000-8000-100000000005',
        N'099c0000-0000-4000-8000-100000000005',
        N'c0c00000-0000-4000-8000-100000000005'

    );





-- ----------------------------------------------------------------------------
-- Quote
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[quotes] WHERE [id] = N'9407e000-0000-4000-8000-100000000001')
    INSERT INTO [crm].[quotes] (
        [id], [name], [quote_number], [expiration_date], [subtotal], [total_price], [opportunity_id], [account_id], [status_id]
    )
    VALUES (
        N'9407e000-0000-4000-8000-100000000001',
        N'Q-2026-001 Acme Enterprise',
        N'Q-2026-001',
        N'2026-07-31',
        97500,
        97500,
        N'099c0000-0000-4000-8000-100000000001',
        N'a0c00000-0000-4000-8000-100000000001',
        N'9407ec00-0000-4000-8000-100000000003'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quotes] WHERE [id] = N'9407e000-0000-4000-8000-100000000002')
    INSERT INTO [crm].[quotes] (
        [id], [name], [quote_number], [expiration_date], [subtotal], [total_price], [opportunity_id], [account_id], [status_id]
    )
    VALUES (
        N'9407e000-0000-4000-8000-100000000002',
        N'Q-2026-002 TechBridge Platform',
        N'Q-2026-002',
        N'2026-08-31',
        145000,
        145000,
        N'099c0000-0000-4000-8000-100000000002',
        N'a0c00000-0000-4000-8000-100000000002',
        N'9407ec00-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quotes] WHERE [id] = N'9407e000-0000-4000-8000-100000000003')
    INSERT INTO [crm].[quotes] (
        [id], [name], [quote_number], [expiration_date], [subtotal], [total_price], [opportunity_id], [account_id], [status_id]
    )
    VALUES (
        N'9407e000-0000-4000-8000-100000000003',
        N'Q-2026-003 CapStone Analytics',
        N'Q-2026-003',
        N'2026-06-15',
        32500,
        32500,
        N'099c0000-0000-4000-8000-100000000003',
        N'a0c00000-0000-4000-8000-100000000003',
        N'9407ec00-0000-4000-8000-100000000004'

    );





-- ----------------------------------------------------------------------------
-- QuoteLineItem
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[quote_line_items] WHERE [id] = N'9407e110-0000-4000-8000-100000000001')
    INSERT INTO [crm].[quote_line_items] (
        [id], [quantity], [unit_price], [total_price], [sort_order], [quote_id], [product_id]
    )
    VALUES (
        N'9407e110-0000-4000-8000-100000000001',
        1,
        75000,
        75000,
        1,
        N'9407e000-0000-4000-8000-100000000001',
        N'9700d000-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_line_items] WHERE [id] = N'9407e110-0000-4000-8000-100000000002')
    INSERT INTO [crm].[quote_line_items] (
        [id], [quantity], [unit_price], [total_price], [sort_order], [quote_id], [product_id]
    )
    VALUES (
        N'9407e110-0000-4000-8000-100000000002',
        1,
        15000,
        15000,
        2,
        N'9407e000-0000-4000-8000-100000000001',
        N'9700d000-0000-4000-8000-100000000003'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_line_items] WHERE [id] = N'9407e110-0000-4000-8000-100000000003')
    INSERT INTO [crm].[quote_line_items] (
        [id], [quantity], [unit_price], [total_price], [sort_order], [quote_id], [product_id]
    )
    VALUES (
        N'9407e110-0000-4000-8000-100000000003',
        1,
        7500,
        7500,
        3,
        N'9407e000-0000-4000-8000-100000000001',
        N'9700d000-0000-4000-8000-100000000004'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_line_items] WHERE [id] = N'9407e110-0000-4000-8000-100000000004')
    INSERT INTO [crm].[quote_line_items] (
        [id], [quantity], [unit_price], [total_price], [sort_order], [quote_id], [product_id]
    )
    VALUES (
        N'9407e110-0000-4000-8000-100000000004',
        5,
        25000,
        125000,
        1,
        N'9407e000-0000-4000-8000-100000000002',
        N'9700d000-0000-4000-8000-100000000002'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_line_items] WHERE [id] = N'9407e110-0000-4000-8000-100000000005')
    INSERT INTO [crm].[quote_line_items] (
        [id], [quantity], [unit_price], [total_price], [sort_order], [quote_id], [product_id]
    )
    VALUES (
        N'9407e110-0000-4000-8000-100000000005',
        1,
        20000,
        20000,
        2,
        N'9407e000-0000-4000-8000-100000000002',
        N'9700d000-0000-4000-8000-100000000003'

    );
