--
--    Generated by app_gen.
--    by app_gen/_templates/database/mssql/create_tables_sql/_mod.j2
--    Defines storage tables for entity_types (T-SQL dialect).
--

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = N'crm')
    EXEC('CREATE SCHEMA [crm]');
GO



IF OBJECT_ID(N'[crm].[accounts]', N'U') IS NOT NULL
BEGIN
    PRINT N'ALTERING table accounts';

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[accounts]')
          AND name = N'name'
    )
        ALTER TABLE [crm].[accounts] ADD [name] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[accounts]')
          AND name = N'website'
    )
        ALTER TABLE [crm].[accounts] ADD [website] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[accounts]')
          AND name = N'phone'
    )
        ALTER TABLE [crm].[accounts] ADD [phone] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[accounts]')
          AND name = N'email'
    )
        ALTER TABLE [crm].[accounts] ADD [email] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[accounts]')
          AND name = N'billing_street'
    )
        ALTER TABLE [crm].[accounts] ADD [billing_street] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[accounts]')
          AND name = N'billing_city'
    )
        ALTER TABLE [crm].[accounts] ADD [billing_city] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[accounts]')
          AND name = N'billing_state'
    )
        ALTER TABLE [crm].[accounts] ADD [billing_state] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[accounts]')
          AND name = N'billing_postal_code'
    )
        ALTER TABLE [crm].[accounts] ADD [billing_postal_code] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[accounts]')
          AND name = N'billing_country'
    )
        ALTER TABLE [crm].[accounts] ADD [billing_country] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[accounts]')
          AND name = N'annual_revenue'
    )
        ALTER TABLE [crm].[accounts] ADD [annual_revenue] float;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[accounts]')
          AND name = N'number_of_employees'
    )
        ALTER TABLE [crm].[accounts] ADD [number_of_employees] int;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[accounts]')
          AND name = N'description'
    )
        ALTER TABLE [crm].[accounts] ADD [description] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[accounts]')
          AND name = N'industry_id'
    )
        ALTER TABLE [crm].[accounts] ADD [industry_id] uniqueidentifier;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[accounts]')
          AND name = N'version'
    )
        ALTER TABLE [crm].[accounts] ADD [version] bigint;

END
ELSE
BEGIN
    PRINT N'CREATING table accounts';
    CREATE TABLE [crm].[accounts]
    (
        [id] uniqueidentifier NOT NULL CONSTRAINT [df_accounts_id] DEFAULT NEWID() CONSTRAINT [pk_accounts] PRIMARY KEY
        ,[name] nvarchar(450)
        ,[website] nvarchar(450)
        ,[phone] nvarchar(450)
        ,[email] nvarchar(450)
        ,[billing_street] nvarchar(450)
        ,[billing_city] nvarchar(450)
        ,[billing_state] nvarchar(450)
        ,[billing_postal_code] nvarchar(450)
        ,[billing_country] nvarchar(450)
        ,[annual_revenue] float
        ,[number_of_employees] int
        ,[description] nvarchar(450)
        ,[industry_id] uniqueidentifier
        ,[version] bigint
    );
END

IF OBJECT_ID(N'[crm].[activities]', N'U') IS NOT NULL
BEGIN
    PRINT N'ALTERING table activities';

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[activities]')
          AND name = N'subject'
    )
        ALTER TABLE [crm].[activities] ADD [subject] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[activities]')
          AND name = N'description'
    )
        ALTER TABLE [crm].[activities] ADD [description] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[activities]')
          AND name = N'activity_date'
    )
        ALTER TABLE [crm].[activities] ADD [activity_date] date;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[activities]')
          AND name = N'due_date'
    )
        ALTER TABLE [crm].[activities] ADD [due_date] date;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[activities]')
          AND name = N'is_closed'
    )
        ALTER TABLE [crm].[activities] ADD [is_closed] bit;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[activities]')
          AND name = N'priority'
    )
        ALTER TABLE [crm].[activities] ADD [priority] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[activities]')
          AND name = N'status'
    )
        ALTER TABLE [crm].[activities] ADD [status] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[activities]')
          AND name = N'type_id'
    )
        ALTER TABLE [crm].[activities] ADD [type_id] uniqueidentifier;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[activities]')
          AND name = N'account_id'
    )
        ALTER TABLE [crm].[activities] ADD [account_id] uniqueidentifier;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[activities]')
          AND name = N'contact_id'
    )
        ALTER TABLE [crm].[activities] ADD [contact_id] uniqueidentifier;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[activities]')
          AND name = N'opportunity_id'
    )
        ALTER TABLE [crm].[activities] ADD [opportunity_id] uniqueidentifier;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[activities]')
          AND name = N'lead_id'
    )
        ALTER TABLE [crm].[activities] ADD [lead_id] uniqueidentifier;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[activities]')
          AND name = N'version'
    )
        ALTER TABLE [crm].[activities] ADD [version] bigint;

END
ELSE
BEGIN
    PRINT N'CREATING table activities';
    CREATE TABLE [crm].[activities]
    (
        [id] uniqueidentifier NOT NULL CONSTRAINT [df_activities_id] DEFAULT NEWID() CONSTRAINT [pk_activities] PRIMARY KEY
        ,[subject] nvarchar(450)
        ,[description] nvarchar(450)
        ,[activity_date] date
        ,[due_date] date
        ,[is_closed] bit
        ,[priority] nvarchar(450)
        ,[status] nvarchar(450)
        ,[type_id] uniqueidentifier
        ,[account_id] uniqueidentifier
        ,[contact_id] uniqueidentifier
        ,[opportunity_id] uniqueidentifier
        ,[lead_id] uniqueidentifier
        ,[version] bigint
    );
END

IF OBJECT_ID(N'[crm].[activity_types]', N'U') IS NOT NULL
BEGIN
    PRINT N'ALTERING table activity_types';

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[activity_types]')
          AND name = N'name'
    )
        ALTER TABLE [crm].[activity_types] ADD [name] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[activity_types]')
          AND name = N'sort_order'
    )
        ALTER TABLE [crm].[activity_types] ADD [sort_order] smallint;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[activity_types]')
          AND name = N'version'
    )
        ALTER TABLE [crm].[activity_types] ADD [version] bigint;

END
ELSE
BEGIN
    PRINT N'CREATING table activity_types';
    CREATE TABLE [crm].[activity_types]
    (
        [id] uniqueidentifier NOT NULL CONSTRAINT [df_activity_types_id] DEFAULT NEWID() CONSTRAINT [pk_activity_types] PRIMARY KEY
        ,[name] nvarchar(450)
        ,[sort_order] smallint
        ,[version] bigint
    );
END

IF OBJECT_ID(N'[crm].[contacts]', N'U') IS NOT NULL
BEGIN
    PRINT N'ALTERING table contacts';

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[contacts]')
          AND name = N'first_name'
    )
        ALTER TABLE [crm].[contacts] ADD [first_name] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[contacts]')
          AND name = N'last_name'
    )
        ALTER TABLE [crm].[contacts] ADD [last_name] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[contacts]')
          AND name = N'email'
    )
        ALTER TABLE [crm].[contacts] ADD [email] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[contacts]')
          AND name = N'phone'
    )
        ALTER TABLE [crm].[contacts] ADD [phone] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[contacts]')
          AND name = N'mobile'
    )
        ALTER TABLE [crm].[contacts] ADD [mobile] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[contacts]')
          AND name = N'title'
    )
        ALTER TABLE [crm].[contacts] ADD [title] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[contacts]')
          AND name = N'department'
    )
        ALTER TABLE [crm].[contacts] ADD [department] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[contacts]')
          AND name = N'mailing_street'
    )
        ALTER TABLE [crm].[contacts] ADD [mailing_street] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[contacts]')
          AND name = N'mailing_city'
    )
        ALTER TABLE [crm].[contacts] ADD [mailing_city] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[contacts]')
          AND name = N'mailing_state'
    )
        ALTER TABLE [crm].[contacts] ADD [mailing_state] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[contacts]')
          AND name = N'mailing_postal_code'
    )
        ALTER TABLE [crm].[contacts] ADD [mailing_postal_code] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[contacts]')
          AND name = N'mailing_country'
    )
        ALTER TABLE [crm].[contacts] ADD [mailing_country] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[contacts]')
          AND name = N'account_id'
    )
        ALTER TABLE [crm].[contacts] ADD [account_id] uniqueidentifier;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[contacts]')
          AND name = N'version'
    )
        ALTER TABLE [crm].[contacts] ADD [version] bigint;

END
ELSE
BEGIN
    PRINT N'CREATING table contacts';
    CREATE TABLE [crm].[contacts]
    (
        [id] uniqueidentifier NOT NULL CONSTRAINT [df_contacts_id] DEFAULT NEWID() CONSTRAINT [pk_contacts] PRIMARY KEY
        ,[first_name] nvarchar(450)
        ,[last_name] nvarchar(450)
        ,[email] nvarchar(450)
        ,[phone] nvarchar(450)
        ,[mobile] nvarchar(450)
        ,[title] nvarchar(450)
        ,[department] nvarchar(450)
        ,[mailing_street] nvarchar(450)
        ,[mailing_city] nvarchar(450)
        ,[mailing_state] nvarchar(450)
        ,[mailing_postal_code] nvarchar(450)
        ,[mailing_country] nvarchar(450)
        ,[account_id] uniqueidentifier
        ,[version] bigint
    );
END

IF OBJECT_ID(N'[crm].[industries]', N'U') IS NOT NULL
BEGIN
    PRINT N'ALTERING table industries';

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[industries]')
          AND name = N'name'
    )
        ALTER TABLE [crm].[industries] ADD [name] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[industries]')
          AND name = N'description'
    )
        ALTER TABLE [crm].[industries] ADD [description] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[industries]')
          AND name = N'sort_order'
    )
        ALTER TABLE [crm].[industries] ADD [sort_order] smallint;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[industries]')
          AND name = N'version'
    )
        ALTER TABLE [crm].[industries] ADD [version] bigint;

END
ELSE
BEGIN
    PRINT N'CREATING table industries';
    CREATE TABLE [crm].[industries]
    (
        [id] uniqueidentifier NOT NULL CONSTRAINT [df_industries_id] DEFAULT NEWID() CONSTRAINT [pk_industries] PRIMARY KEY
        ,[name] nvarchar(450)
        ,[description] nvarchar(450)
        ,[sort_order] smallint
        ,[version] bigint
    );
END

IF OBJECT_ID(N'[crm].[leads]', N'U') IS NOT NULL
BEGIN
    PRINT N'ALTERING table leads';

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[leads]')
          AND name = N'first_name'
    )
        ALTER TABLE [crm].[leads] ADD [first_name] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[leads]')
          AND name = N'last_name'
    )
        ALTER TABLE [crm].[leads] ADD [last_name] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[leads]')
          AND name = N'email'
    )
        ALTER TABLE [crm].[leads] ADD [email] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[leads]')
          AND name = N'phone'
    )
        ALTER TABLE [crm].[leads] ADD [phone] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[leads]')
          AND name = N'company'
    )
        ALTER TABLE [crm].[leads] ADD [company] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[leads]')
          AND name = N'title'
    )
        ALTER TABLE [crm].[leads] ADD [title] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[leads]')
          AND name = N'website'
    )
        ALTER TABLE [crm].[leads] ADD [website] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[leads]')
          AND name = N'description'
    )
        ALTER TABLE [crm].[leads] ADD [description] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[leads]')
          AND name = N'annual_revenue'
    )
        ALTER TABLE [crm].[leads] ADD [annual_revenue] float;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[leads]')
          AND name = N'number_of_employees'
    )
        ALTER TABLE [crm].[leads] ADD [number_of_employees] int;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[leads]')
          AND name = N'is_converted'
    )
        ALTER TABLE [crm].[leads] ADD [is_converted] bit;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[leads]')
          AND name = N'converted_account_id'
    )
        ALTER TABLE [crm].[leads] ADD [converted_account_id] uniqueidentifier;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[leads]')
          AND name = N'status_id'
    )
        ALTER TABLE [crm].[leads] ADD [status_id] uniqueidentifier;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[leads]')
          AND name = N'source_id'
    )
        ALTER TABLE [crm].[leads] ADD [source_id] uniqueidentifier;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[leads]')
          AND name = N'industry_id'
    )
        ALTER TABLE [crm].[leads] ADD [industry_id] uniqueidentifier;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[leads]')
          AND name = N'version'
    )
        ALTER TABLE [crm].[leads] ADD [version] bigint;

END
ELSE
BEGIN
    PRINT N'CREATING table leads';
    CREATE TABLE [crm].[leads]
    (
        [id] uniqueidentifier NOT NULL CONSTRAINT [df_leads_id] DEFAULT NEWID() CONSTRAINT [pk_leads] PRIMARY KEY
        ,[first_name] nvarchar(450)
        ,[last_name] nvarchar(450)
        ,[email] nvarchar(450)
        ,[phone] nvarchar(450)
        ,[company] nvarchar(450)
        ,[title] nvarchar(450)
        ,[website] nvarchar(450)
        ,[description] nvarchar(450)
        ,[annual_revenue] float
        ,[number_of_employees] int
        ,[is_converted] bit
        ,[converted_account_id] uniqueidentifier
        ,[status_id] uniqueidentifier
        ,[source_id] uniqueidentifier
        ,[industry_id] uniqueidentifier
        ,[version] bigint
    );
END

IF OBJECT_ID(N'[crm].[lead_sources]', N'U') IS NOT NULL
BEGIN
    PRINT N'ALTERING table lead_sources';

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[lead_sources]')
          AND name = N'name'
    )
        ALTER TABLE [crm].[lead_sources] ADD [name] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[lead_sources]')
          AND name = N'sort_order'
    )
        ALTER TABLE [crm].[lead_sources] ADD [sort_order] smallint;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[lead_sources]')
          AND name = N'version'
    )
        ALTER TABLE [crm].[lead_sources] ADD [version] bigint;

END
ELSE
BEGIN
    PRINT N'CREATING table lead_sources';
    CREATE TABLE [crm].[lead_sources]
    (
        [id] uniqueidentifier NOT NULL CONSTRAINT [df_lead_sources_id] DEFAULT NEWID() CONSTRAINT [pk_lead_sources] PRIMARY KEY
        ,[name] nvarchar(450)
        ,[sort_order] smallint
        ,[version] bigint
    );
END

IF OBJECT_ID(N'[crm].[lead_statuses]', N'U') IS NOT NULL
BEGIN
    PRINT N'ALTERING table lead_statuses';

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[lead_statuses]')
          AND name = N'name'
    )
        ALTER TABLE [crm].[lead_statuses] ADD [name] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[lead_statuses]')
          AND name = N'is_converted'
    )
        ALTER TABLE [crm].[lead_statuses] ADD [is_converted] bit;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[lead_statuses]')
          AND name = N'sort_order'
    )
        ALTER TABLE [crm].[lead_statuses] ADD [sort_order] smallint;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[lead_statuses]')
          AND name = N'version'
    )
        ALTER TABLE [crm].[lead_statuses] ADD [version] bigint;

END
ELSE
BEGIN
    PRINT N'CREATING table lead_statuses';
    CREATE TABLE [crm].[lead_statuses]
    (
        [id] uniqueidentifier NOT NULL CONSTRAINT [df_lead_statuses_id] DEFAULT NEWID() CONSTRAINT [pk_lead_statuses] PRIMARY KEY
        ,[name] nvarchar(450)
        ,[is_converted] bit
        ,[sort_order] smallint
        ,[version] bigint
    );
END

IF OBJECT_ID(N'[crm].[opportunities]', N'U') IS NOT NULL
BEGIN
    PRINT N'ALTERING table opportunities';

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[opportunities]')
          AND name = N'name'
    )
        ALTER TABLE [crm].[opportunities] ADD [name] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[opportunities]')
          AND name = N'amount'
    )
        ALTER TABLE [crm].[opportunities] ADD [amount] float;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[opportunities]')
          AND name = N'close_date'
    )
        ALTER TABLE [crm].[opportunities] ADD [close_date] date;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[opportunities]')
          AND name = N'description'
    )
        ALTER TABLE [crm].[opportunities] ADD [description] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[opportunities]')
          AND name = N'next_step'
    )
        ALTER TABLE [crm].[opportunities] ADD [next_step] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[opportunities]')
          AND name = N'lead_source'
    )
        ALTER TABLE [crm].[opportunities] ADD [lead_source] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[opportunities]')
          AND name = N'account_id'
    )
        ALTER TABLE [crm].[opportunities] ADD [account_id] uniqueidentifier;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[opportunities]')
          AND name = N'stage_id'
    )
        ALTER TABLE [crm].[opportunities] ADD [stage_id] uniqueidentifier;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[opportunities]')
          AND name = N'version'
    )
        ALTER TABLE [crm].[opportunities] ADD [version] bigint;

END
ELSE
BEGIN
    PRINT N'CREATING table opportunities';
    CREATE TABLE [crm].[opportunities]
    (
        [id] uniqueidentifier NOT NULL CONSTRAINT [df_opportunities_id] DEFAULT NEWID() CONSTRAINT [pk_opportunities] PRIMARY KEY
        ,[name] nvarchar(450)
        ,[amount] float
        ,[close_date] date
        ,[description] nvarchar(450)
        ,[next_step] nvarchar(450)
        ,[lead_source] nvarchar(450)
        ,[account_id] uniqueidentifier
        ,[stage_id] uniqueidentifier
        ,[version] bigint
    );
END

IF OBJECT_ID(N'[crm].[opportunity_stages]', N'U') IS NOT NULL
BEGIN
    PRINT N'ALTERING table opportunity_stages';

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[opportunity_stages]')
          AND name = N'name'
    )
        ALTER TABLE [crm].[opportunity_stages] ADD [name] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[opportunity_stages]')
          AND name = N'probability'
    )
        ALTER TABLE [crm].[opportunity_stages] ADD [probability] real;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[opportunity_stages]')
          AND name = N'is_closed'
    )
        ALTER TABLE [crm].[opportunity_stages] ADD [is_closed] bit;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[opportunity_stages]')
          AND name = N'is_won'
    )
        ALTER TABLE [crm].[opportunity_stages] ADD [is_won] bit;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[opportunity_stages]')
          AND name = N'sort_order'
    )
        ALTER TABLE [crm].[opportunity_stages] ADD [sort_order] smallint;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[opportunity_stages]')
          AND name = N'version'
    )
        ALTER TABLE [crm].[opportunity_stages] ADD [version] bigint;

END
ELSE
BEGIN
    PRINT N'CREATING table opportunity_stages';
    CREATE TABLE [crm].[opportunity_stages]
    (
        [id] uniqueidentifier NOT NULL CONSTRAINT [df_opportunity_stages_id] DEFAULT NEWID() CONSTRAINT [pk_opportunity_stages] PRIMARY KEY
        ,[name] nvarchar(450)
        ,[probability] real
        ,[is_closed] bit
        ,[is_won] bit
        ,[sort_order] smallint
        ,[version] bigint
    );
END

IF OBJECT_ID(N'[crm].[pricebooks]', N'U') IS NOT NULL
BEGIN
    PRINT N'ALTERING table pricebooks';

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[pricebooks]')
          AND name = N'name'
    )
        ALTER TABLE [crm].[pricebooks] ADD [name] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[pricebooks]')
          AND name = N'description'
    )
        ALTER TABLE [crm].[pricebooks] ADD [description] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[pricebooks]')
          AND name = N'is_active'
    )
        ALTER TABLE [crm].[pricebooks] ADD [is_active] bit;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[pricebooks]')
          AND name = N'is_standard'
    )
        ALTER TABLE [crm].[pricebooks] ADD [is_standard] bit;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[pricebooks]')
          AND name = N'version'
    )
        ALTER TABLE [crm].[pricebooks] ADD [version] bigint;

END
ELSE
BEGIN
    PRINT N'CREATING table pricebooks';
    CREATE TABLE [crm].[pricebooks]
    (
        [id] uniqueidentifier NOT NULL CONSTRAINT [df_pricebooks_id] DEFAULT NEWID() CONSTRAINT [pk_pricebooks] PRIMARY KEY
        ,[name] nvarchar(450)
        ,[description] nvarchar(450)
        ,[is_active] bit
        ,[is_standard] bit
        ,[version] bigint
    );
END

IF OBJECT_ID(N'[crm].[products]', N'U') IS NOT NULL
BEGIN
    PRINT N'ALTERING table products';

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[products]')
          AND name = N'name'
    )
        ALTER TABLE [crm].[products] ADD [name] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[products]')
          AND name = N'product_code'
    )
        ALTER TABLE [crm].[products] ADD [product_code] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[products]')
          AND name = N'description'
    )
        ALTER TABLE [crm].[products] ADD [description] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[products]')
          AND name = N'list_price'
    )
        ALTER TABLE [crm].[products] ADD [list_price] float;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[products]')
          AND name = N'is_active'
    )
        ALTER TABLE [crm].[products] ADD [is_active] bit;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[products]')
          AND name = N'family'
    )
        ALTER TABLE [crm].[products] ADD [family] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[products]')
          AND name = N'pricebook_id'
    )
        ALTER TABLE [crm].[products] ADD [pricebook_id] uniqueidentifier;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[products]')
          AND name = N'version'
    )
        ALTER TABLE [crm].[products] ADD [version] bigint;

END
ELSE
BEGIN
    PRINT N'CREATING table products';
    CREATE TABLE [crm].[products]
    (
        [id] uniqueidentifier NOT NULL CONSTRAINT [df_products_id] DEFAULT NEWID() CONSTRAINT [pk_products] PRIMARY KEY
        ,[name] nvarchar(450)
        ,[product_code] nvarchar(450)
        ,[description] nvarchar(450)
        ,[list_price] float
        ,[is_active] bit
        ,[family] nvarchar(450)
        ,[pricebook_id] uniqueidentifier
        ,[version] bigint
    );
END

IF OBJECT_ID(N'[crm].[quotes]', N'U') IS NOT NULL
BEGIN
    PRINT N'ALTERING table quotes';

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quotes]')
          AND name = N'name'
    )
        ALTER TABLE [crm].[quotes] ADD [name] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quotes]')
          AND name = N'quote_number'
    )
        ALTER TABLE [crm].[quotes] ADD [quote_number] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quotes]')
          AND name = N'expiration_date'
    )
        ALTER TABLE [crm].[quotes] ADD [expiration_date] date;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quotes]')
          AND name = N'description'
    )
        ALTER TABLE [crm].[quotes] ADD [description] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quotes]')
          AND name = N'subtotal'
    )
        ALTER TABLE [crm].[quotes] ADD [subtotal] float;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quotes]')
          AND name = N'discount'
    )
        ALTER TABLE [crm].[quotes] ADD [discount] float;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quotes]')
          AND name = N'tax'
    )
        ALTER TABLE [crm].[quotes] ADD [tax] float;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quotes]')
          AND name = N'total_price'
    )
        ALTER TABLE [crm].[quotes] ADD [total_price] float;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quotes]')
          AND name = N'opportunity_id'
    )
        ALTER TABLE [crm].[quotes] ADD [opportunity_id] uniqueidentifier;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quotes]')
          AND name = N'account_id'
    )
        ALTER TABLE [crm].[quotes] ADD [account_id] uniqueidentifier;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quotes]')
          AND name = N'status_id'
    )
        ALTER TABLE [crm].[quotes] ADD [status_id] uniqueidentifier;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quotes]')
          AND name = N'version'
    )
        ALTER TABLE [crm].[quotes] ADD [version] bigint;

END
ELSE
BEGIN
    PRINT N'CREATING table quotes';
    CREATE TABLE [crm].[quotes]
    (
        [id] uniqueidentifier NOT NULL CONSTRAINT [df_quotes_id] DEFAULT NEWID() CONSTRAINT [pk_quotes] PRIMARY KEY
        ,[name] nvarchar(450)
        ,[quote_number] nvarchar(450)
        ,[expiration_date] date
        ,[description] nvarchar(450)
        ,[subtotal] float
        ,[discount] float
        ,[tax] float
        ,[total_price] float
        ,[opportunity_id] uniqueidentifier
        ,[account_id] uniqueidentifier
        ,[status_id] uniqueidentifier
        ,[version] bigint
    );
END

IF OBJECT_ID(N'[crm].[quote_line_items]', N'U') IS NOT NULL
BEGIN
    PRINT N'ALTERING table quote_line_items';

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quote_line_items]')
          AND name = N'quantity'
    )
        ALTER TABLE [crm].[quote_line_items] ADD [quantity] float;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quote_line_items]')
          AND name = N'unit_price'
    )
        ALTER TABLE [crm].[quote_line_items] ADD [unit_price] float;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quote_line_items]')
          AND name = N'discount'
    )
        ALTER TABLE [crm].[quote_line_items] ADD [discount] float;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quote_line_items]')
          AND name = N'total_price'
    )
        ALTER TABLE [crm].[quote_line_items] ADD [total_price] float;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quote_line_items]')
          AND name = N'description'
    )
        ALTER TABLE [crm].[quote_line_items] ADD [description] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quote_line_items]')
          AND name = N'sort_order'
    )
        ALTER TABLE [crm].[quote_line_items] ADD [sort_order] smallint;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quote_line_items]')
          AND name = N'quote_id'
    )
        ALTER TABLE [crm].[quote_line_items] ADD [quote_id] uniqueidentifier;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quote_line_items]')
          AND name = N'product_id'
    )
        ALTER TABLE [crm].[quote_line_items] ADD [product_id] uniqueidentifier;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quote_line_items]')
          AND name = N'version'
    )
        ALTER TABLE [crm].[quote_line_items] ADD [version] bigint;

END
ELSE
BEGIN
    PRINT N'CREATING table quote_line_items';
    CREATE TABLE [crm].[quote_line_items]
    (
        [id] uniqueidentifier NOT NULL CONSTRAINT [df_quote_line_items_id] DEFAULT NEWID() CONSTRAINT [pk_quote_line_items] PRIMARY KEY
        ,[quantity] float
        ,[unit_price] float
        ,[discount] float
        ,[total_price] float
        ,[description] nvarchar(450)
        ,[sort_order] smallint
        ,[quote_id] uniqueidentifier
        ,[product_id] uniqueidentifier
        ,[version] bigint
    );
END

IF OBJECT_ID(N'[crm].[quote_statuses]', N'U') IS NOT NULL
BEGIN
    PRINT N'ALTERING table quote_statuses';

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quote_statuses]')
          AND name = N'name'
    )
        ALTER TABLE [crm].[quote_statuses] ADD [name] nvarchar(450);

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quote_statuses]')
          AND name = N'sort_order'
    )
        ALTER TABLE [crm].[quote_statuses] ADD [sort_order] smallint;

    IF NOT EXISTS (
        SELECT 1 FROM sys.columns
        WHERE object_id = OBJECT_ID(N'[crm].[quote_statuses]')
          AND name = N'version'
    )
        ALTER TABLE [crm].[quote_statuses] ADD [version] bigint;

END
ELSE
BEGIN
    PRINT N'CREATING table quote_statuses';
    CREATE TABLE [crm].[quote_statuses]
    (
        [id] uniqueidentifier NOT NULL CONSTRAINT [df_quote_statuses_id] DEFAULT NEWID() CONSTRAINT [pk_quote_statuses] PRIMARY KEY
        ,[name] nvarchar(450)
        ,[sort_order] smallint
        ,[version] bigint
    );
END







IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_accounts_name'
      AND object_id = OBJECT_ID(N'[crm].[accounts]')
)
BEGIN
    PRINT N'Creating index idx_accounts_name';
    CREATE INDEX [idx_accounts_name]
        ON [crm].[accounts] ([name]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_accounts_industry_id'
      AND object_id = OBJECT_ID(N'[crm].[accounts]')
)
BEGIN
    PRINT N'Creating index idx_accounts_industry_id';
    CREATE INDEX [idx_accounts_industry_id]
        ON [crm].[accounts] ([industry_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_activities_account_id_contact_id_opportunity_id'
      AND object_id = OBJECT_ID(N'[crm].[activities]')
)
BEGIN
    PRINT N'Creating index idx_activities_account_id_contact_id_opportunity_id';
    CREATE INDEX [idx_activities_account_id_contact_id_opportunity_id]
        ON [crm].[activities] ([account_id], [contact_id], [opportunity_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_activities_type_id'
      AND object_id = OBJECT_ID(N'[crm].[activities]')
)
BEGIN
    PRINT N'Creating index idx_activities_type_id';
    CREATE INDEX [idx_activities_type_id]
        ON [crm].[activities] ([type_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_activities_account_id'
      AND object_id = OBJECT_ID(N'[crm].[activities]')
)
BEGIN
    PRINT N'Creating index idx_activities_account_id';
    CREATE INDEX [idx_activities_account_id]
        ON [crm].[activities] ([account_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_activities_contact_id'
      AND object_id = OBJECT_ID(N'[crm].[activities]')
)
BEGIN
    PRINT N'Creating index idx_activities_contact_id';
    CREATE INDEX [idx_activities_contact_id]
        ON [crm].[activities] ([contact_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_activities_opportunity_id'
      AND object_id = OBJECT_ID(N'[crm].[activities]')
)
BEGIN
    PRINT N'Creating index idx_activities_opportunity_id';
    CREATE INDEX [idx_activities_opportunity_id]
        ON [crm].[activities] ([opportunity_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_activities_lead_id'
      AND object_id = OBJECT_ID(N'[crm].[activities]')
)
BEGIN
    PRINT N'Creating index idx_activities_lead_id';
    CREATE INDEX [idx_activities_lead_id]
        ON [crm].[activities] ([lead_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_activity_types_name'
      AND object_id = OBJECT_ID(N'[crm].[activity_types]')
)
BEGIN
    PRINT N'Creating index idx_activity_types_name';
    CREATE INDEX [idx_activity_types_name]
        ON [crm].[activity_types] ([name]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_contacts_account_id'
      AND object_id = OBJECT_ID(N'[crm].[contacts]')
)
BEGIN
    PRINT N'Creating index idx_contacts_account_id';
    CREATE INDEX [idx_contacts_account_id]
        ON [crm].[contacts] ([account_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_contacts_account_id'
      AND object_id = OBJECT_ID(N'[crm].[contacts]')
)
BEGIN
    PRINT N'Creating index idx_contacts_account_id';
    CREATE INDEX [idx_contacts_account_id]
        ON [crm].[contacts] ([account_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_industries_name'
      AND object_id = OBJECT_ID(N'[crm].[industries]')
)
BEGIN
    PRINT N'Creating index idx_industries_name';
    CREATE INDEX [idx_industries_name]
        ON [crm].[industries] ([name]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_leads_email'
      AND object_id = OBJECT_ID(N'[crm].[leads]')
)
BEGIN
    PRINT N'Creating index idx_leads_email';
    CREATE INDEX [idx_leads_email]
        ON [crm].[leads] ([email]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_leads_converted_account_id'
      AND object_id = OBJECT_ID(N'[crm].[leads]')
)
BEGIN
    PRINT N'Creating index idx_leads_converted_account_id';
    CREATE INDEX [idx_leads_converted_account_id]
        ON [crm].[leads] ([converted_account_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_leads_status_id'
      AND object_id = OBJECT_ID(N'[crm].[leads]')
)
BEGIN
    PRINT N'Creating index idx_leads_status_id';
    CREATE INDEX [idx_leads_status_id]
        ON [crm].[leads] ([status_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_leads_source_id'
      AND object_id = OBJECT_ID(N'[crm].[leads]')
)
BEGIN
    PRINT N'Creating index idx_leads_source_id';
    CREATE INDEX [idx_leads_source_id]
        ON [crm].[leads] ([source_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_leads_industry_id'
      AND object_id = OBJECT_ID(N'[crm].[leads]')
)
BEGIN
    PRINT N'Creating index idx_leads_industry_id';
    CREATE INDEX [idx_leads_industry_id]
        ON [crm].[leads] ([industry_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_lead_sources_name'
      AND object_id = OBJECT_ID(N'[crm].[lead_sources]')
)
BEGIN
    PRINT N'Creating index idx_lead_sources_name';
    CREATE INDEX [idx_lead_sources_name]
        ON [crm].[lead_sources] ([name]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_lead_statuses_name'
      AND object_id = OBJECT_ID(N'[crm].[lead_statuses]')
)
BEGIN
    PRINT N'Creating index idx_lead_statuses_name';
    CREATE INDEX [idx_lead_statuses_name]
        ON [crm].[lead_statuses] ([name]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_opportunities_name_account_id'
      AND object_id = OBJECT_ID(N'[crm].[opportunities]')
)
BEGIN
    PRINT N'Creating index idx_opportunities_name_account_id';
    CREATE INDEX [idx_opportunities_name_account_id]
        ON [crm].[opportunities] ([name], [account_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_opportunities_account_id'
      AND object_id = OBJECT_ID(N'[crm].[opportunities]')
)
BEGIN
    PRINT N'Creating index idx_opportunities_account_id';
    CREATE INDEX [idx_opportunities_account_id]
        ON [crm].[opportunities] ([account_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_opportunities_stage_id'
      AND object_id = OBJECT_ID(N'[crm].[opportunities]')
)
BEGIN
    PRINT N'Creating index idx_opportunities_stage_id';
    CREATE INDEX [idx_opportunities_stage_id]
        ON [crm].[opportunities] ([stage_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_opportunity_stages_name'
      AND object_id = OBJECT_ID(N'[crm].[opportunity_stages]')
)
BEGIN
    PRINT N'Creating index idx_opportunity_stages_name';
    CREATE INDEX [idx_opportunity_stages_name]
        ON [crm].[opportunity_stages] ([name]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_pricebooks_name'
      AND object_id = OBJECT_ID(N'[crm].[pricebooks]')
)
BEGIN
    PRINT N'Creating index idx_pricebooks_name';
    CREATE INDEX [idx_pricebooks_name]
        ON [crm].[pricebooks] ([name]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_products_name'
      AND object_id = OBJECT_ID(N'[crm].[products]')
)
BEGIN
    PRINT N'Creating index idx_products_name';
    CREATE INDEX [idx_products_name]
        ON [crm].[products] ([name]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_products_pricebook_id'
      AND object_id = OBJECT_ID(N'[crm].[products]')
)
BEGIN
    PRINT N'Creating index idx_products_pricebook_id';
    CREATE INDEX [idx_products_pricebook_id]
        ON [crm].[products] ([pricebook_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_quotes_opportunity_id'
      AND object_id = OBJECT_ID(N'[crm].[quotes]')
)
BEGIN
    PRINT N'Creating index idx_quotes_opportunity_id';
    CREATE INDEX [idx_quotes_opportunity_id]
        ON [crm].[quotes] ([opportunity_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_quotes_opportunity_id'
      AND object_id = OBJECT_ID(N'[crm].[quotes]')
)
BEGIN
    PRINT N'Creating index idx_quotes_opportunity_id';
    CREATE INDEX [idx_quotes_opportunity_id]
        ON [crm].[quotes] ([opportunity_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_quotes_account_id'
      AND object_id = OBJECT_ID(N'[crm].[quotes]')
)
BEGIN
    PRINT N'Creating index idx_quotes_account_id';
    CREATE INDEX [idx_quotes_account_id]
        ON [crm].[quotes] ([account_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_quotes_status_id'
      AND object_id = OBJECT_ID(N'[crm].[quotes]')
)
BEGIN
    PRINT N'Creating index idx_quotes_status_id';
    CREATE INDEX [idx_quotes_status_id]
        ON [crm].[quotes] ([status_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_quote_line_items_quote_id'
      AND object_id = OBJECT_ID(N'[crm].[quote_line_items]')
)
BEGIN
    PRINT N'Creating index idx_quote_line_items_quote_id';
    CREATE INDEX [idx_quote_line_items_quote_id]
        ON [crm].[quote_line_items] ([quote_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_quote_line_items_quote_id'
      AND object_id = OBJECT_ID(N'[crm].[quote_line_items]')
)
BEGIN
    PRINT N'Creating index idx_quote_line_items_quote_id';
    CREATE INDEX [idx_quote_line_items_quote_id]
        ON [crm].[quote_line_items] ([quote_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_quote_line_items_product_id'
      AND object_id = OBJECT_ID(N'[crm].[quote_line_items]')
)
BEGIN
    PRINT N'Creating index idx_quote_line_items_product_id';
    CREATE INDEX [idx_quote_line_items_product_id]
        ON [crm].[quote_line_items] ([product_id]);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'idx_quote_statuses_name'
      AND object_id = OBJECT_ID(N'[crm].[quote_statuses]')
)
BEGIN
    PRINT N'Creating index idx_quote_statuses_name';
    CREATE INDEX [idx_quote_statuses_name]
        ON [crm].[quote_statuses] ([name]);
END




IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'fk_accounts_industry_id'
      AND parent_object_id = OBJECT_ID(N'[crm].[accounts]')
)
BEGIN
    PRINT N'Creating foreign key constraint fk_accounts_industry_id';
    ALTER TABLE [crm].[accounts]
        ADD CONSTRAINT [fk_accounts_industry_id]
        FOREIGN KEY ([industry_id])
        REFERENCES [crm].[industries]([id])
        ON DELETE NO ACTION ON UPDATE NO ACTION;
END

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'fk_activities_type_id'
      AND parent_object_id = OBJECT_ID(N'[crm].[activities]')
)
BEGIN
    PRINT N'Creating foreign key constraint fk_activities_type_id';
    ALTER TABLE [crm].[activities]
        ADD CONSTRAINT [fk_activities_type_id]
        FOREIGN KEY ([type_id])
        REFERENCES [crm].[activity_types]([id])
        ON DELETE NO ACTION ON UPDATE NO ACTION;
END

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'fk_activities_account_id'
      AND parent_object_id = OBJECT_ID(N'[crm].[activities]')
)
BEGIN
    PRINT N'Creating foreign key constraint fk_activities_account_id';
    ALTER TABLE [crm].[activities]
        ADD CONSTRAINT [fk_activities_account_id]
        FOREIGN KEY ([account_id])
        REFERENCES [crm].[accounts]([id])
        ON DELETE NO ACTION ON UPDATE NO ACTION;
END

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'fk_activities_contact_id'
      AND parent_object_id = OBJECT_ID(N'[crm].[activities]')
)
BEGIN
    PRINT N'Creating foreign key constraint fk_activities_contact_id';
    ALTER TABLE [crm].[activities]
        ADD CONSTRAINT [fk_activities_contact_id]
        FOREIGN KEY ([contact_id])
        REFERENCES [crm].[contacts]([id])
        ON DELETE NO ACTION ON UPDATE NO ACTION;
END

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'fk_activities_opportunity_id'
      AND parent_object_id = OBJECT_ID(N'[crm].[activities]')
)
BEGIN
    PRINT N'Creating foreign key constraint fk_activities_opportunity_id';
    ALTER TABLE [crm].[activities]
        ADD CONSTRAINT [fk_activities_opportunity_id]
        FOREIGN KEY ([opportunity_id])
        REFERENCES [crm].[opportunities]([id])
        ON DELETE NO ACTION ON UPDATE NO ACTION;
END

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'fk_activities_lead_id'
      AND parent_object_id = OBJECT_ID(N'[crm].[activities]')
)
BEGIN
    PRINT N'Creating foreign key constraint fk_activities_lead_id';
    ALTER TABLE [crm].[activities]
        ADD CONSTRAINT [fk_activities_lead_id]
        FOREIGN KEY ([lead_id])
        REFERENCES [crm].[leads]([id])
        ON DELETE NO ACTION ON UPDATE NO ACTION;
END

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'fk_contacts_account_id'
      AND parent_object_id = OBJECT_ID(N'[crm].[contacts]')
)
BEGIN
    PRINT N'Creating foreign key constraint fk_contacts_account_id';
    ALTER TABLE [crm].[contacts]
        ADD CONSTRAINT [fk_contacts_account_id]
        FOREIGN KEY ([account_id])
        REFERENCES [crm].[accounts]([id])
        ON DELETE NO ACTION ON UPDATE NO ACTION;
END

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'fk_leads_converted_account_id'
      AND parent_object_id = OBJECT_ID(N'[crm].[leads]')
)
BEGIN
    PRINT N'Creating foreign key constraint fk_leads_converted_account_id';
    ALTER TABLE [crm].[leads]
        ADD CONSTRAINT [fk_leads_converted_account_id]
        FOREIGN KEY ([converted_account_id])
        REFERENCES [crm].[accounts]([id])
        ON DELETE NO ACTION ON UPDATE NO ACTION;
END

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'fk_leads_status_id'
      AND parent_object_id = OBJECT_ID(N'[crm].[leads]')
)
BEGIN
    PRINT N'Creating foreign key constraint fk_leads_status_id';
    ALTER TABLE [crm].[leads]
        ADD CONSTRAINT [fk_leads_status_id]
        FOREIGN KEY ([status_id])
        REFERENCES [crm].[lead_statuses]([id])
        ON DELETE NO ACTION ON UPDATE NO ACTION;
END

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'fk_leads_source_id'
      AND parent_object_id = OBJECT_ID(N'[crm].[leads]')
)
BEGIN
    PRINT N'Creating foreign key constraint fk_leads_source_id';
    ALTER TABLE [crm].[leads]
        ADD CONSTRAINT [fk_leads_source_id]
        FOREIGN KEY ([source_id])
        REFERENCES [crm].[lead_sources]([id])
        ON DELETE NO ACTION ON UPDATE NO ACTION;
END

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'fk_leads_industry_id'
      AND parent_object_id = OBJECT_ID(N'[crm].[leads]')
)
BEGIN
    PRINT N'Creating foreign key constraint fk_leads_industry_id';
    ALTER TABLE [crm].[leads]
        ADD CONSTRAINT [fk_leads_industry_id]
        FOREIGN KEY ([industry_id])
        REFERENCES [crm].[industries]([id])
        ON DELETE NO ACTION ON UPDATE NO ACTION;
END

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'fk_opportunities_account_id'
      AND parent_object_id = OBJECT_ID(N'[crm].[opportunities]')
)
BEGIN
    PRINT N'Creating foreign key constraint fk_opportunities_account_id';
    ALTER TABLE [crm].[opportunities]
        ADD CONSTRAINT [fk_opportunities_account_id]
        FOREIGN KEY ([account_id])
        REFERENCES [crm].[accounts]([id])
        ON DELETE NO ACTION ON UPDATE NO ACTION;
END

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'fk_opportunities_stage_id'
      AND parent_object_id = OBJECT_ID(N'[crm].[opportunities]')
)
BEGIN
    PRINT N'Creating foreign key constraint fk_opportunities_stage_id';
    ALTER TABLE [crm].[opportunities]
        ADD CONSTRAINT [fk_opportunities_stage_id]
        FOREIGN KEY ([stage_id])
        REFERENCES [crm].[opportunity_stages]([id])
        ON DELETE NO ACTION ON UPDATE NO ACTION;
END

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'fk_products_pricebook_id'
      AND parent_object_id = OBJECT_ID(N'[crm].[products]')
)
BEGIN
    PRINT N'Creating foreign key constraint fk_products_pricebook_id';
    ALTER TABLE [crm].[products]
        ADD CONSTRAINT [fk_products_pricebook_id]
        FOREIGN KEY ([pricebook_id])
        REFERENCES [crm].[pricebooks]([id])
        ON DELETE NO ACTION ON UPDATE NO ACTION;
END

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'fk_quotes_opportunity_id'
      AND parent_object_id = OBJECT_ID(N'[crm].[quotes]')
)
BEGIN
    PRINT N'Creating foreign key constraint fk_quotes_opportunity_id';
    ALTER TABLE [crm].[quotes]
        ADD CONSTRAINT [fk_quotes_opportunity_id]
        FOREIGN KEY ([opportunity_id])
        REFERENCES [crm].[opportunities]([id])
        ON DELETE NO ACTION ON UPDATE NO ACTION;
END

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'fk_quotes_account_id'
      AND parent_object_id = OBJECT_ID(N'[crm].[quotes]')
)
BEGIN
    PRINT N'Creating foreign key constraint fk_quotes_account_id';
    ALTER TABLE [crm].[quotes]
        ADD CONSTRAINT [fk_quotes_account_id]
        FOREIGN KEY ([account_id])
        REFERENCES [crm].[accounts]([id])
        ON DELETE NO ACTION ON UPDATE NO ACTION;
END

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'fk_quotes_status_id'
      AND parent_object_id = OBJECT_ID(N'[crm].[quotes]')
)
BEGIN
    PRINT N'Creating foreign key constraint fk_quotes_status_id';
    ALTER TABLE [crm].[quotes]
        ADD CONSTRAINT [fk_quotes_status_id]
        FOREIGN KEY ([status_id])
        REFERENCES [crm].[quote_statuses]([id])
        ON DELETE NO ACTION ON UPDATE NO ACTION;
END

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'fk_quote_line_items_quote_id'
      AND parent_object_id = OBJECT_ID(N'[crm].[quote_line_items]')
)
BEGIN
    PRINT N'Creating foreign key constraint fk_quote_line_items_quote_id';
    ALTER TABLE [crm].[quote_line_items]
        ADD CONSTRAINT [fk_quote_line_items_quote_id]
        FOREIGN KEY ([quote_id])
        REFERENCES [crm].[quotes]([id])
        ON DELETE NO ACTION ON UPDATE NO ACTION;
END

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'fk_quote_line_items_product_id'
      AND parent_object_id = OBJECT_ID(N'[crm].[quote_line_items]')
)
BEGIN
    PRINT N'Creating foreign key constraint fk_quote_line_items_product_id';
    ALTER TABLE [crm].[quote_line_items]
        ADD CONSTRAINT [fk_quote_line_items_product_id]
        FOREIGN KEY ([product_id])
        REFERENCES [crm].[products]([id])
        ON DELETE NO ACTION ON UPDATE NO ACTION;
END







-- Junction table for ManyToMany: Contact <-> Opportunity
IF OBJECT_ID(N'[crm].[opportunity_contacts]', N'U') IS NULL
BEGIN
    PRINT N'CREATING junction table OpportunityContact';
    CREATE TABLE [crm].[opportunity_contacts]
    (
        [id] uniqueidentifier NOT NULL CONSTRAINT [df_opportunity_contacts_id] DEFAULT NEWID() CONSTRAINT [pk_opportunity_contacts] PRIMARY KEY,
        [contact_id] uniqueidentifier NOT NULL,
        [opportunity_id] uniqueidentifier NOT NULL,
        [created_at] datetimeoffset(7) NOT NULL CONSTRAINT [df_opportunity_contacts_created_at] DEFAULT SYSDATETIMEOFFSET(),
        CONSTRAINT [uq_opportunity_contacts] UNIQUE ([contact_id], [opportunity_id])
    );

    CREATE INDEX [idx_opportunity_contacts_contact_id]
        ON [crm].[opportunity_contacts] ([contact_id]);
    CREATE INDEX [idx_opportunity_contacts_opportunity_id]
        ON [crm].[opportunity_contacts] ([opportunity_id]);

    ALTER TABLE [crm].[opportunity_contacts]
        ADD CONSTRAINT [fk_opportunity_contacts_contact_id]
        FOREIGN KEY ([contact_id])
        REFERENCES [crm].[contacts]([id])
        ON DELETE CASCADE ON UPDATE CASCADE;

    ALTER TABLE [crm].[opportunity_contacts]
        ADD CONSTRAINT [fk_opportunity_contacts_opportunity_id]
        FOREIGN KEY ([opportunity_id])
        REFERENCES [crm].[opportunities]([id])
        ON DELETE NO ACTION ON UPDATE NO ACTION;
END

-- Junction table for ManyToMany: Opportunity <-> Contact
IF OBJECT_ID(N'[crm].[opportunity_contacts]', N'U') IS NULL
BEGIN
    PRINT N'CREATING junction table OpportunityContact';
    CREATE TABLE [crm].[opportunity_contacts]
    (
        [id] uniqueidentifier NOT NULL CONSTRAINT [df_opportunity_contacts_id] DEFAULT NEWID() CONSTRAINT [pk_opportunity_contacts] PRIMARY KEY,
        [opportunity_id] uniqueidentifier NOT NULL,
        [contact_id] uniqueidentifier NOT NULL,
        [created_at] datetimeoffset(7) NOT NULL CONSTRAINT [df_opportunity_contacts_created_at] DEFAULT SYSDATETIMEOFFSET(),
        CONSTRAINT [uq_opportunity_contacts] UNIQUE ([opportunity_id], [contact_id])
    );

    CREATE INDEX [idx_opportunity_contacts_opportunity_id]
        ON [crm].[opportunity_contacts] ([opportunity_id]);
    CREATE INDEX [idx_opportunity_contacts_contact_id]
        ON [crm].[opportunity_contacts] ([contact_id]);

    ALTER TABLE [crm].[opportunity_contacts]
        ADD CONSTRAINT [fk_opportunity_contacts_opportunity_id]
        FOREIGN KEY ([opportunity_id])
        REFERENCES [crm].[opportunities]([id])
        ON DELETE CASCADE ON UPDATE CASCADE;

    ALTER TABLE [crm].[opportunity_contacts]
        ADD CONSTRAINT [fk_opportunity_contacts_contact_id]
        FOREIGN KEY ([contact_id])
        REFERENCES [crm].[contacts]([id])
        ON DELETE NO ACTION ON UPDATE NO ACTION;
END
