//
// Backend denovo_workflow: Handlers
//    Defines Query and Mutation objects for denovo_workflow GQL entity_types
//    Generated by app_gen.
//
#![allow(dead_code)]

//
// Mod crates

pub(crate) mod de_novo_task;
pub(crate) mod generated;
pub(crate) mod team;
pub(crate) mod workstream;

//
// Wireups
#[cfg(feature = "http")]
use async_graphql::{Context, FieldResult, Object};

#[cfg(feature = "http")]
use super::selections::get_query_selections;
#[cfg(feature = "http")]
use crate::schemas::common::AggregateResult;
#[cfg(feature = "http")]
#[allow(unused)]
use crate::{
    data::query_ir::PaginationPolicy,
    product_api::{
        data_access_from_context, entity_type_for_handler, user_from_context, EntityType,
        HandlerContext, JsonValue,
    },
    routes::app_error::AppError,
    schemas::denovo_workflow::{
        DeNovoTaskProjection, DeNovoTaskQueryResult, InputDeNovoTask, InputTeam, InputWorkstream,
        TeamProjection, TeamQueryResult, WorkstreamProjection, WorkstreamQueryResult,
    },
};

#[cfg(feature = "http")]
#[derive(Default)]
pub struct DenovoWorkflowQuery;

#[cfg(feature = "http")]
#[Object(extends)]
impl DenovoWorkflowQuery {
    async fn find_de_novo_task(
        &self,
        ctx: &Context<'_>,
        id: String,
    ) -> FieldResult<Option<DeNovoTaskProjection>> {
        let handler_context = from_context(ctx, "denovo_workflow", "DeNovoTask")?;
        let (user, data_access, entity_type, selections) = handler_context.into_handler_parts();

        let res = de_novo_task::find_impl(user, &data_access, &entity_type, selections, id).await;

        match res {
            Ok(res) => Ok(res),
            Err(e) => Err(e.into()),
        }
    }

    async fn find_de_novo_task_by_locator(
        &self,
        ctx: &Context<'_>,
        locator: String,
    ) -> FieldResult<Option<DeNovoTaskProjection>> {
        let handler_context = from_context(ctx, "denovo_workflow", "DeNovoTask")?;
        let (user, data_access, entity_type, selections) = handler_context.into_handler_parts();

        let res = de_novo_task::find_by_locator_impl(
            user,
            &data_access,
            &entity_type,
            selections,
            locator,
        )
        .await;

        match res {
            Ok(res) => Ok(res),
            Err(e) => Err(e.into()),
        }
    }

    async fn get_de_novo_tasks(&self, ctx: &Context<'_>) -> FieldResult<Vec<DeNovoTaskProjection>> {
        let handler_context = from_context(ctx, "denovo_workflow", "DeNovoTask")?;
        let (user, data_access, entity_type, selections) = handler_context.into_handler_parts();

        let res = de_novo_task::get_impl(user, &data_access, &entity_type, selections).await;

        match res {
            Ok(res) => Ok(res),
            Err(e) => Err(e.into()),
        }
    }

    async fn query_de_novo_tasks(
        &self,
        ctx: &Context<'_>,
        filter: Option<JsonValue>,
        sort: Option<JsonValue>,
        skip: Option<i32>,
        limit: Option<i32>,
        after: Option<String>,
    ) -> FieldResult<DeNovoTaskQueryResult> {
        let handler_context = from_context(ctx, "denovo_workflow", "DeNovoTask")?;
        let (user, data_access, entity_type, selections) = handler_context.into_handler_parts();
        let (skip, limit) = pagination_args(skip, limit)?;

        let res = de_novo_task::query_impl(
            user,
            &data_access,
            &entity_type,
            selections,
            filter,
            sort,
            skip,
            limit,
            after,
        )
        .await;

        match res {
            Ok(res) => Ok(DeNovoTaskQueryResult {
                date_time: res.date_time,
                request_duration: res.request_duration,
                skip: res.skip,
                limit: res.limit,
                page_count: res.page_count,
                page_index: res.page_index,
                query_count: res.query_count,
                next_cursor: res.next_cursor,
                previous_cursor: res.previous_cursor,
                items: res.items,
            }),
            Err(e) => Err(e.into()),
        }
    }
    async fn aggregate_de_novo_tasks(
        &self,
        ctx: &Context<'_>,
        filter: Option<JsonValue>,
        group_by: Option<JsonValue>,
        metrics: Option<JsonValue>,
        having: Option<JsonValue>,
        sort: Option<JsonValue>,
        skip: Option<i32>,
        limit: Option<i32>,
    ) -> FieldResult<AggregateResult> {
        let handler_context =
            from_context_without_selections(ctx, "denovo_workflow", "DeNovoTask")?;
        let (user, data_access, entity_type, _) = handler_context.into_handler_parts();
        let (skip, limit) = pagination_args(skip, limit)?;

        let res = data_access
            .aggregate_items(
                entity_type,
                filter,
                group_by,
                metrics,
                having,
                sort,
                skip,
                limit,
                user,
            )
            .await;

        match res {
            Ok(res) => Ok(res),
            Err(e) => Err(e.into()),
        }
    }

    async fn find_team(
        &self,
        ctx: &Context<'_>,
        id: String,
    ) -> FieldResult<Option<TeamProjection>> {
        let handler_context = from_context(ctx, "denovo_workflow", "Team")?;
        let (user, data_access, entity_type, selections) = handler_context.into_handler_parts();

        let res = team::find_impl(user, &data_access, &entity_type, selections, id).await;

        match res {
            Ok(res) => Ok(res),
            Err(e) => Err(e.into()),
        }
    }

    async fn find_team_by_locator(
        &self,
        ctx: &Context<'_>,
        locator: String,
    ) -> FieldResult<Option<TeamProjection>> {
        let handler_context = from_context(ctx, "denovo_workflow", "Team")?;
        let (user, data_access, entity_type, selections) = handler_context.into_handler_parts();

        let res =
            team::find_by_locator_impl(user, &data_access, &entity_type, selections, locator).await;

        match res {
            Ok(res) => Ok(res),
            Err(e) => Err(e.into()),
        }
    }

    async fn get_teams(&self, ctx: &Context<'_>) -> FieldResult<Vec<TeamProjection>> {
        let handler_context = from_context(ctx, "denovo_workflow", "Team")?;
        let (user, data_access, entity_type, selections) = handler_context.into_handler_parts();

        let res = team::get_impl(user, &data_access, &entity_type, selections).await;

        match res {
            Ok(res) => Ok(res),
            Err(e) => Err(e.into()),
        }
    }

    async fn query_teams(
        &self,
        ctx: &Context<'_>,
        filter: Option<JsonValue>,
        sort: Option<JsonValue>,
        skip: Option<i32>,
        limit: Option<i32>,
        after: Option<String>,
    ) -> FieldResult<TeamQueryResult> {
        let handler_context = from_context(ctx, "denovo_workflow", "Team")?;
        let (user, data_access, entity_type, selections) = handler_context.into_handler_parts();
        let (skip, limit) = pagination_args(skip, limit)?;

        let res = team::query_impl(
            user,
            &data_access,
            &entity_type,
            selections,
            filter,
            sort,
            skip,
            limit,
            after,
        )
        .await;

        match res {
            Ok(res) => Ok(TeamQueryResult {
                date_time: res.date_time,
                request_duration: res.request_duration,
                skip: res.skip,
                limit: res.limit,
                page_count: res.page_count,
                page_index: res.page_index,
                query_count: res.query_count,
                next_cursor: res.next_cursor,
                previous_cursor: res.previous_cursor,
                items: res.items,
            }),
            Err(e) => Err(e.into()),
        }
    }
    async fn aggregate_teams(
        &self,
        ctx: &Context<'_>,
        filter: Option<JsonValue>,
        group_by: Option<JsonValue>,
        metrics: Option<JsonValue>,
        having: Option<JsonValue>,
        sort: Option<JsonValue>,
        skip: Option<i32>,
        limit: Option<i32>,
    ) -> FieldResult<AggregateResult> {
        let handler_context = from_context_without_selections(ctx, "denovo_workflow", "Team")?;
        let (user, data_access, entity_type, _) = handler_context.into_handler_parts();
        let (skip, limit) = pagination_args(skip, limit)?;

        let res = data_access
            .aggregate_items(
                entity_type,
                filter,
                group_by,
                metrics,
                having,
                sort,
                skip,
                limit,
                user,
            )
            .await;

        match res {
            Ok(res) => Ok(res),
            Err(e) => Err(e.into()),
        }
    }

    async fn find_workstream(
        &self,
        ctx: &Context<'_>,
        id: String,
    ) -> FieldResult<Option<WorkstreamProjection>> {
        let handler_context = from_context(ctx, "denovo_workflow", "Workstream")?;
        let (user, data_access, entity_type, selections) = handler_context.into_handler_parts();

        let res = workstream::find_impl(user, &data_access, &entity_type, selections, id).await;

        match res {
            Ok(res) => Ok(res),
            Err(e) => Err(e.into()),
        }
    }

    async fn find_workstream_by_locator(
        &self,
        ctx: &Context<'_>,
        locator: String,
    ) -> FieldResult<Option<WorkstreamProjection>> {
        let handler_context = from_context(ctx, "denovo_workflow", "Workstream")?;
        let (user, data_access, entity_type, selections) = handler_context.into_handler_parts();

        let res =
            workstream::find_by_locator_impl(user, &data_access, &entity_type, selections, locator)
                .await;

        match res {
            Ok(res) => Ok(res),
            Err(e) => Err(e.into()),
        }
    }

    async fn get_workstreams(&self, ctx: &Context<'_>) -> FieldResult<Vec<WorkstreamProjection>> {
        let handler_context = from_context(ctx, "denovo_workflow", "Workstream")?;
        let (user, data_access, entity_type, selections) = handler_context.into_handler_parts();

        let res = workstream::get_impl(user, &data_access, &entity_type, selections).await;

        match res {
            Ok(res) => Ok(res),
            Err(e) => Err(e.into()),
        }
    }

    async fn query_workstreams(
        &self,
        ctx: &Context<'_>,
        filter: Option<JsonValue>,
        sort: Option<JsonValue>,
        skip: Option<i32>,
        limit: Option<i32>,
        after: Option<String>,
    ) -> FieldResult<WorkstreamQueryResult> {
        let handler_context = from_context(ctx, "denovo_workflow", "Workstream")?;
        let (user, data_access, entity_type, selections) = handler_context.into_handler_parts();
        let (skip, limit) = pagination_args(skip, limit)?;

        let res = workstream::query_impl(
            user,
            &data_access,
            &entity_type,
            selections,
            filter,
            sort,
            skip,
            limit,
            after,
        )
        .await;

        match res {
            Ok(res) => Ok(WorkstreamQueryResult {
                date_time: res.date_time,
                request_duration: res.request_duration,
                skip: res.skip,
                limit: res.limit,
                page_count: res.page_count,
                page_index: res.page_index,
                query_count: res.query_count,
                next_cursor: res.next_cursor,
                previous_cursor: res.previous_cursor,
                items: res.items,
            }),
            Err(e) => Err(e.into()),
        }
    }
    async fn aggregate_workstreams(
        &self,
        ctx: &Context<'_>,
        filter: Option<JsonValue>,
        group_by: Option<JsonValue>,
        metrics: Option<JsonValue>,
        having: Option<JsonValue>,
        sort: Option<JsonValue>,
        skip: Option<i32>,
        limit: Option<i32>,
    ) -> FieldResult<AggregateResult> {
        let handler_context =
            from_context_without_selections(ctx, "denovo_workflow", "Workstream")?;
        let (user, data_access, entity_type, _) = handler_context.into_handler_parts();
        let (skip, limit) = pagination_args(skip, limit)?;

        let res = data_access
            .aggregate_items(
                entity_type,
                filter,
                group_by,
                metrics,
                having,
                sort,
                skip,
                limit,
                user,
            )
            .await;

        match res {
            Ok(res) => Ok(res),
            Err(e) => Err(e.into()),
        }
    }
}

#[cfg(feature = "http")]
#[derive(Default)]
pub struct DenovoWorkflowMutation;

#[cfg(feature = "http")]
#[Object]
impl DenovoWorkflowMutation {
    #[graphql(visible = false)]
    async fn appfw_mutation_root(&self) -> bool {
        true
    }
}

#[cfg(feature = "http")]
fn from_context(
    ctx: &Context<'_>,
    schema_name: &'static str,
    type_name: &'static str,
) -> std::result::Result<HandlerContext, AppError> {
    let user = user_from_context(ctx);
    let data_access = data_access_from_context(ctx);
    let entity_type = entity_type_for_handler(&data_access, schema_name, type_name)?;
    let selections = get_query_selections(
        data_access.app_config.clone(),
        entity_type.clone(),
        ctx.field(),
    )?;
    Ok(HandlerContext::new(
        user,
        data_access,
        entity_type,
        selections,
    ))
}

#[cfg(feature = "http")]
fn from_context_without_selections(
    ctx: &Context<'_>,
    schema_name: &'static str,
    type_name: &'static str,
) -> std::result::Result<HandlerContext, AppError> {
    let user = user_from_context(ctx);
    let data_access = data_access_from_context(ctx);
    let entity_type = entity_type_for_handler(&data_access, schema_name, type_name)?;
    Ok(HandlerContext::new(
        user,
        data_access,
        entity_type,
        JsonValue::Null,
    ))
}

#[cfg(feature = "http")]
fn pagination_args(
    skip: Option<i32>,
    limit: Option<i32>,
) -> std::result::Result<(i32, i32), AppError> {
    Ok(PaginationPolicy::from_env().normalize(skip, limit)?)
}
