--
--    Generated by app_gen.
--    by app_gen/_templates/database/mssql/seed_sql/_mod.j2
--    Seed data for crm schema (T-SQL dialect)
--




-- ----------------------------------------------------------------------------
-- ActivityType
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[activity_types] WHERE [id] = N'ac71ec00-0000-4000-8000-100000000001')
    INSERT INTO [crm].[activity_types] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'ac71ec00-0000-4000-8000-100000000001',
        N'Email',
        10

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[activity_types] WHERE [id] = N'ac71ec00-0000-4000-8000-100000000002')
    INSERT INTO [crm].[activity_types] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'ac71ec00-0000-4000-8000-100000000002',
        N'Call',
        20

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[activity_types] WHERE [id] = N'ac71ec00-0000-4000-8000-100000000003')
    INSERT INTO [crm].[activity_types] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'ac71ec00-0000-4000-8000-100000000003',
        N'Meeting',
        30

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[activity_types] WHERE [id] = N'ac71ec00-0000-4000-8000-100000000004')
    INSERT INTO [crm].[activity_types] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'ac71ec00-0000-4000-8000-100000000004',
        N'Task',
        40

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[activity_types] WHERE [id] = N'ac71ec00-0000-4000-8000-100000000005')
    INSERT INTO [crm].[activity_types] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'ac71ec00-0000-4000-8000-100000000005',
        N'Note',
        50

    );





-- ----------------------------------------------------------------------------
-- Industry
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[industries] WHERE [id] = N'10100070-0000-4000-8000-100000000001')
    INSERT INTO [crm].[industries] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'10100070-0000-4000-8000-100000000001',
        N'Healthcare',
        10

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[industries] WHERE [id] = N'10100070-0000-4000-8000-100000000002')
    INSERT INTO [crm].[industries] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'10100070-0000-4000-8000-100000000002',
        N'Technology',
        20

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[industries] WHERE [id] = N'10100070-0000-4000-8000-100000000003')
    INSERT INTO [crm].[industries] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'10100070-0000-4000-8000-100000000003',
        N'Financial Services',
        30

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[industries] WHERE [id] = N'10100070-0000-4000-8000-100000000004')
    INSERT INTO [crm].[industries] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'10100070-0000-4000-8000-100000000004',
        N'Manufacturing',
        40

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[industries] WHERE [id] = N'10100070-0000-4000-8000-100000000005')
    INSERT INTO [crm].[industries] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'10100070-0000-4000-8000-100000000005',
        N'Retail',
        50

    );





-- ----------------------------------------------------------------------------
-- LeadSource
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[lead_sources] WHERE [id] = N'1eadcc01-0000-4000-8000-100000000001')
    INSERT INTO [crm].[lead_sources] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'1eadcc01-0000-4000-8000-100000000001',
        N'Web',
        10

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[lead_sources] WHERE [id] = N'1eadcc01-0000-4000-8000-100000000002')
    INSERT INTO [crm].[lead_sources] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'1eadcc01-0000-4000-8000-100000000002',
        N'Phone Inquiry',
        20

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[lead_sources] WHERE [id] = N'1eadcc01-0000-4000-8000-100000000003')
    INSERT INTO [crm].[lead_sources] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'1eadcc01-0000-4000-8000-100000000003',
        N'Partner Referral',
        30

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[lead_sources] WHERE [id] = N'1eadcc01-0000-4000-8000-100000000004')
    INSERT INTO [crm].[lead_sources] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'1eadcc01-0000-4000-8000-100000000004',
        N'Trade Show',
        40

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[lead_sources] WHERE [id] = N'1eadcc01-0000-4000-8000-100000000005')
    INSERT INTO [crm].[lead_sources] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'1eadcc01-0000-4000-8000-100000000005',
        N'Employee Referral',
        50

    );





-- ----------------------------------------------------------------------------
-- LeadStatus
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[lead_statuses] WHERE [id] = N'1eadcc00-0000-4000-8000-100000000001')
    INSERT INTO [crm].[lead_statuses] (
        [id], [name], [is_converted], [sort_order]
    )
    VALUES (
        N'1eadcc00-0000-4000-8000-100000000001',
        N'New',
        0,
        10

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[lead_statuses] WHERE [id] = N'1eadcc00-0000-4000-8000-100000000002')
    INSERT INTO [crm].[lead_statuses] (
        [id], [name], [is_converted], [sort_order]
    )
    VALUES (
        N'1eadcc00-0000-4000-8000-100000000002',
        N'Contacted',
        0,
        20

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[lead_statuses] WHERE [id] = N'1eadcc00-0000-4000-8000-100000000003')
    INSERT INTO [crm].[lead_statuses] (
        [id], [name], [is_converted], [sort_order]
    )
    VALUES (
        N'1eadcc00-0000-4000-8000-100000000003',
        N'Qualified',
        0,
        30

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[lead_statuses] WHERE [id] = N'1eadcc00-0000-4000-8000-100000000004')
    INSERT INTO [crm].[lead_statuses] (
        [id], [name], [is_converted], [sort_order]
    )
    VALUES (
        N'1eadcc00-0000-4000-8000-100000000004',
        N'Unqualified',
        0,
        40

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[lead_statuses] WHERE [id] = N'1eadcc00-0000-4000-8000-100000000005')
    INSERT INTO [crm].[lead_statuses] (
        [id], [name], [is_converted], [sort_order]
    )
    VALUES (
        N'1eadcc00-0000-4000-8000-100000000005',
        N'Converted',
        1,
        50

    );





-- ----------------------------------------------------------------------------
-- OpportunityStage
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[opportunity_stages] WHERE [id] = N'0998a900-0000-4000-8000-100000000001')
    INSERT INTO [crm].[opportunity_stages] (
        [id], [name], [probability], [is_closed], [is_won], [sort_order]
    )
    VALUES (
        N'0998a900-0000-4000-8000-100000000001',
        N'Prospecting',
        0.1,
        0,
        0,
        10

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunity_stages] WHERE [id] = N'0998a900-0000-4000-8000-100000000002')
    INSERT INTO [crm].[opportunity_stages] (
        [id], [name], [probability], [is_closed], [is_won], [sort_order]
    )
    VALUES (
        N'0998a900-0000-4000-8000-100000000002',
        N'Qualification',
        0.2,
        0,
        0,
        20

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunity_stages] WHERE [id] = N'0998a900-0000-4000-8000-100000000003')
    INSERT INTO [crm].[opportunity_stages] (
        [id], [name], [probability], [is_closed], [is_won], [sort_order]
    )
    VALUES (
        N'0998a900-0000-4000-8000-100000000003',
        N'Proposal',
        0.5,
        0,
        0,
        30

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunity_stages] WHERE [id] = N'0998a900-0000-4000-8000-100000000004')
    INSERT INTO [crm].[opportunity_stages] (
        [id], [name], [probability], [is_closed], [is_won], [sort_order]
    )
    VALUES (
        N'0998a900-0000-4000-8000-100000000004',
        N'Closed Won',
        1.0,
        1,
        1,
        40

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunity_stages] WHERE [id] = N'0998a900-0000-4000-8000-100000000005')
    INSERT INTO [crm].[opportunity_stages] (
        [id], [name], [probability], [is_closed], [is_won], [sort_order]
    )
    VALUES (
        N'0998a900-0000-4000-8000-100000000005',
        N'Closed Lost',
        0.0,
        1,
        0,
        50

    );





-- ----------------------------------------------------------------------------
-- Pricebook
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[pricebooks] WHERE [id] = N'97000b00-0000-4000-8000-100000000001')
    INSERT INTO [crm].[pricebooks] (
        [id], [name], [description], [is_active], [is_standard]
    )
    VALUES (
        N'97000b00-0000-4000-8000-100000000001',
        N'Standard Price Book',
        N'Default price book for all products',
        1,
        1

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[pricebooks] WHERE [id] = N'97000b00-0000-4000-8000-100000000002')
    INSERT INTO [crm].[pricebooks] (
        [id], [name], [description], [is_active], [is_standard]
    )
    VALUES (
        N'97000b00-0000-4000-8000-100000000002',
        N'Partner Price Book',
        N'Discounted pricing for channel partners',
        1,
        0

    );





-- ----------------------------------------------------------------------------
-- QuoteStatus
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[quote_statuses] WHERE [id] = N'9407ec00-0000-4000-8000-100000000001')
    INSERT INTO [crm].[quote_statuses] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'9407ec00-0000-4000-8000-100000000001',
        N'Draft',
        10

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_statuses] WHERE [id] = N'9407ec00-0000-4000-8000-100000000002')
    INSERT INTO [crm].[quote_statuses] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'9407ec00-0000-4000-8000-100000000002',
        N'Needs Review',
        20

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_statuses] WHERE [id] = N'9407ec00-0000-4000-8000-100000000003')
    INSERT INTO [crm].[quote_statuses] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'9407ec00-0000-4000-8000-100000000003',
        N'Delivered',
        30

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_statuses] WHERE [id] = N'9407ec00-0000-4000-8000-100000000004')
    INSERT INTO [crm].[quote_statuses] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'9407ec00-0000-4000-8000-100000000004',
        N'Accepted',
        40

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_statuses] WHERE [id] = N'9407ec00-0000-4000-8000-100000000005')
    INSERT INTO [crm].[quote_statuses] (
        [id], [name], [sort_order]
    )
    VALUES (
        N'9407ec00-0000-4000-8000-100000000005',
        N'Rejected',
        50

    );





-- ----------------------------------------------------------------------------
-- Account
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[accounts] WHERE [id] = N'a0c00000-0000-4000-8000-100000000001')
    INSERT INTO [crm].[accounts] (
        [id], [name], [website], [phone], [email], [tags], [billing_street], [billing_city], [billing_state], [billing_postal_code], [billing_country], [annual_revenue], [number_of_employees], [description], [industry_id]
    )
    VALUES (
        N'a0c00000-0000-4000-8000-100000000001',
        N'Acme Dental Group',
        N'https://acmedental.com',
        N'555-0100',
        N'info@acmedental.com',
        N'["baseline","healthcare","south","mid-market"]',
        N'101 Congress Ave',
        N'Austin',
        N'TX',
        N'78701',
        N'US',
        12000000,
        85,
        N'Regional dental services group expanding patient engagement and back-office automation.',
        N'10100070-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[accounts] WHERE [id] = N'a0c00000-0000-4000-8000-100000000002')
    INSERT INTO [crm].[accounts] (
        [id], [name], [website], [phone], [email], [tags], [billing_street], [billing_city], [billing_state], [billing_postal_code], [billing_country], [annual_revenue], [number_of_employees], [description], [industry_id]
    )
    VALUES (
        N'a0c00000-0000-4000-8000-100000000002',
        N'TechBridge Solutions',
        N'https://techbridge.io',
        N'555-0200',
        N'hello@techbridge.io',
        N'["baseline","technology","west","mid-market"]',
        N'500 Market St',
        N'San Francisco',
        N'CA',
        N'94105',
        N'US',
        45000000,
        220,
        N'Cloud integration consultancy standardizing customer success operations.',
        N'10100070-0000-4000-8000-100000000002'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[accounts] WHERE [id] = N'a0c00000-0000-4000-8000-100000000003')
    INSERT INTO [crm].[accounts] (
        [id], [name], [website], [phone], [email], [tags], [billing_street], [billing_city], [billing_state], [billing_postal_code], [billing_country], [annual_revenue], [number_of_employees], [description], [industry_id]
    )
    VALUES (
        N'a0c00000-0000-4000-8000-100000000003',
        N'CapStone Financial',
        N'https://capstone-fin.com',
        N'555-0300',
        N'contact@capstone-fin.com',
        N'["baseline","financial-services","northeast","enterprise"]',
        N'75 Broad St',
        N'New York',
        N'NY',
        N'10004',
        N'US',
        90000000,
        450,
        N'Wealth management firm evaluating analytics and compliance reporting capabilities.',
        N'10100070-0000-4000-8000-100000000003'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[accounts] WHERE [id] = N'a0c00000-0000-4000-8000-100000000004')
    INSERT INTO [crm].[accounts] (
        [id], [name], [website], [phone], [email], [tags], [billing_street], [billing_city], [billing_state], [billing_postal_code], [billing_country], [annual_revenue], [number_of_employees], [description], [industry_id]
    )
    VALUES (
        N'a0c00000-0000-4000-8000-100000000004',
        N'MediSystems Inc',
        N'https://medisystems.com',
        N'555-0400',
        N'info@medisystems.com',
        N'["baseline","healthcare","midwest","mid-market"]',
        N'233 W Wacker Dr',
        N'Chicago',
        N'IL',
        N'60606',
        N'US',
        22000000,
        130,
        N'Healthcare technology provider modernizing account management and field operations.',
        N'10100070-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[accounts] WHERE [id] = N'a0c00000-0000-4000-8000-100000000005')
    INSERT INTO [crm].[accounts] (
        [id], [name], [website], [phone], [email], [tags], [billing_street], [billing_city], [billing_state], [billing_postal_code], [billing_country], [annual_revenue], [number_of_employees], [description], [industry_id]
    )
    VALUES (
        N'a0c00000-0000-4000-8000-100000000005',
        N'RetailPlus Corp',
        N'https://retailplus.com',
        N'555-0500',
        N'sales@retailplus.com',
        N'["baseline","retail","south","mid-market"]',
        N'1720 Commerce St',
        N'Dallas',
        N'TX',
        N'75201',
        N'US',
        18000000,
        110,
        N'Regional retailer piloting service workflows across store operations and procurement.',
        N'10100070-0000-4000-8000-100000000005'

    );





-- ----------------------------------------------------------------------------
-- Product
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[products] WHERE [id] = N'9700d000-0000-4000-8000-100000000001')
    INSERT INTO [crm].[products] (
        [id], [name], [product_code], [description], [list_price], [is_active], [family], [pricebook_id]
    )
    VALUES (
        N'9700d000-0000-4000-8000-100000000001',
        N'Enterprise Suite',
        N'ENT-001',
        N'Full-featured enterprise platform license',
        75000.0,
        1,
        N'Software',
        N'97000b00-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[products] WHERE [id] = N'9700d000-0000-4000-8000-100000000002')
    INSERT INTO [crm].[products] (
        [id], [name], [product_code], [description], [list_price], [is_active], [family], [pricebook_id]
    )
    VALUES (
        N'9700d000-0000-4000-8000-100000000002',
        N'Professional Edition',
        N'PRO-001',
        N'Mid-market platform license',
        25000.0,
        1,
        N'Software',
        N'97000b00-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[products] WHERE [id] = N'9700d000-0000-4000-8000-100000000003')
    INSERT INTO [crm].[products] (
        [id], [name], [product_code], [description], [list_price], [is_active], [family], [pricebook_id]
    )
    VALUES (
        N'9700d000-0000-4000-8000-100000000003',
        N'Implementation Services',
        N'SVC-001',
        N'Professional services for deployment',
        15000.0,
        1,
        N'Services',
        N'97000b00-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[products] WHERE [id] = N'9700d000-0000-4000-8000-100000000004')
    INSERT INTO [crm].[products] (
        [id], [name], [product_code], [description], [list_price], [is_active], [family], [pricebook_id]
    )
    VALUES (
        N'9700d000-0000-4000-8000-100000000004',
        N'Annual Support',
        N'SUP-001',
        N'Yearly support and maintenance contract',
        7500.0,
        1,
        N'Support',
        N'97000b00-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[products] WHERE [id] = N'9700d000-0000-4000-8000-100000000005')
    INSERT INTO [crm].[products] (
        [id], [name], [product_code], [description], [list_price], [is_active], [family], [pricebook_id]
    )
    VALUES (
        N'9700d000-0000-4000-8000-100000000005',
        N'Training Package',
        N'TRN-001',
        N'User and admin training bundle',
        5000.0,
        1,
        N'Services',
        N'97000b00-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[products] WHERE [id] = N'9700d000-0000-4000-8000-100000000006')
    INSERT INTO [crm].[products] (
        [id], [name], [product_code], [description], [list_price], [is_active], [family], [pricebook_id]
    )
    VALUES (
        N'9700d000-0000-4000-8000-100000000006',
        N'Data Migration Accelerator',
        N'SVC-002',
        N'Fixed-scope migration package for legacy CRM and ERP data',
        18000.0,
        1,
        N'Services',
        N'97000b00-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[products] WHERE [id] = N'9700d000-0000-4000-8000-100000000007')
    INSERT INTO [crm].[products] (
        [id], [name], [product_code], [description], [list_price], [is_active], [family], [pricebook_id]
    )
    VALUES (
        N'9700d000-0000-4000-8000-100000000007',
        N'Customer Portal Add-On',
        N'ADD-001',
        N'Customer self-service portal and branded access layer',
        32000.0,
        1,
        N'Software',
        N'97000b00-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[products] WHERE [id] = N'9700d000-0000-4000-8000-100000000008')
    INSERT INTO [crm].[products] (
        [id], [name], [product_code], [description], [list_price], [is_active], [family], [pricebook_id]
    )
    VALUES (
        N'9700d000-0000-4000-8000-100000000008',
        N'Compliance Reporting Pack',
        N'REP-001',
        N'Regulated reporting dashboards and export templates',
        12000.0,
        1,
        N'Reporting',
        N'97000b00-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[products] WHERE [id] = N'9700d000-0000-4000-8000-100000000009')
    INSERT INTO [crm].[products] (
        [id], [name], [product_code], [description], [list_price], [is_active], [family], [pricebook_id]
    )
    VALUES (
        N'9700d000-0000-4000-8000-100000000009',
        N'Partner Enablement Kit',
        N'PRT-001',
        N'Partner onboarding workshops, playbooks, and co-selling assets',
        8500.0,
        1,
        N'Services',
        N'97000b00-0000-4000-8000-100000000002'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[products] WHERE [id] = N'9700d000-0000-4000-8000-100000000010')
    INSERT INTO [crm].[products] (
        [id], [name], [product_code], [description], [list_price], [is_active], [family], [pricebook_id]
    )
    VALUES (
        N'9700d000-0000-4000-8000-100000000010',
        N'Sandbox Environment',
        N'SBOX-001',
        N'Isolated non-production environment for testing and training',
        6000.0,
        1,
        N'Software',
        N'97000b00-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[products] WHERE [id] = N'9700d000-0000-4000-8000-100000000011')
    INSERT INTO [crm].[products] (
        [id], [name], [product_code], [description], [list_price], [is_active], [family], [pricebook_id]
    )
    VALUES (
        N'9700d000-0000-4000-8000-100000000011',
        N'Legacy Connector Pack',
        N'INT-001',
        N'Connector bundle for file drops, SFTP, and legacy API synchronization',
        14000.0,
        1,
        N'Integrations',
        N'97000b00-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[products] WHERE [id] = N'9700d000-0000-4000-8000-100000000012')
    INSERT INTO [crm].[products] (
        [id], [name], [product_code], [description], [list_price], [is_active], [family], [pricebook_id]
    )
    VALUES (
        N'9700d000-0000-4000-8000-100000000012',
        N'Retired On-Prem Connector',
        N'INT-LEGACY',
        N'Inactive connector retained to exercise inactive product filtering',
        9500.0,
        0,
        N'Integrations',
        N'97000b00-0000-4000-8000-100000000002'

    );





-- ----------------------------------------------------------------------------
-- Contact
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[contacts] WHERE [id] = N'c0c00000-0000-4000-8000-100000000001')
    INSERT INTO [crm].[contacts] (
        [id], [first_name], [last_name], [email], [phone], [mobile], [title], [department], [mailing_street], [mailing_city], [mailing_state], [mailing_postal_code], [mailing_country], [account_id]
    )
    VALUES (
        N'c0c00000-0000-4000-8000-100000000001',
        N'Sarah',
        N'Mitchell',
        N's.mitchell@acmedental.com',
        N'555-0101',
        N'555-0109',
        N'VP Operations',
        N'Operations',
        N'101 Congress Ave',
        N'Austin',
        N'TX',
        N'78701',
        N'US',
        N'a0c00000-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[contacts] WHERE [id] = N'c0c00000-0000-4000-8000-100000000002')
    INSERT INTO [crm].[contacts] (
        [id], [first_name], [last_name], [email], [phone], [mobile], [title], [department], [mailing_street], [mailing_city], [mailing_state], [mailing_postal_code], [mailing_country], [account_id]
    )
    VALUES (
        N'c0c00000-0000-4000-8000-100000000002',
        N'James',
        N'Okafor',
        N'j.okafor@techbridge.io',
        N'555-0201',
        N'555-0209',
        N'CTO',
        N'Engineering',
        N'500 Market St',
        N'San Francisco',
        N'CA',
        N'94105',
        N'US',
        N'a0c00000-0000-4000-8000-100000000002'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[contacts] WHERE [id] = N'c0c00000-0000-4000-8000-100000000003')
    INSERT INTO [crm].[contacts] (
        [id], [first_name], [last_name], [email], [phone], [mobile], [title], [department], [mailing_street], [mailing_city], [mailing_state], [mailing_postal_code], [mailing_country], [account_id]
    )
    VALUES (
        N'c0c00000-0000-4000-8000-100000000003',
        N'Lisa',
        N'Chen',
        N'l.chen@capstone-fin.com',
        N'555-0301',
        N'555-0309',
        N'CFO',
        N'Finance',
        N'75 Broad St',
        N'New York',
        N'NY',
        N'10004',
        N'US',
        N'a0c00000-0000-4000-8000-100000000003'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[contacts] WHERE [id] = N'c0c00000-0000-4000-8000-100000000004')
    INSERT INTO [crm].[contacts] (
        [id], [first_name], [last_name], [email], [phone], [mobile], [title], [department], [mailing_street], [mailing_city], [mailing_state], [mailing_postal_code], [mailing_country], [account_id]
    )
    VALUES (
        N'c0c00000-0000-4000-8000-100000000004',
        N'David',
        N'Torres',
        N'd.torres@medisystems.com',
        N'555-0401',
        N'555-0409',
        N'Director of IT',
        N'Information Technology',
        N'233 W Wacker Dr',
        N'Chicago',
        N'IL',
        N'60606',
        N'US',
        N'a0c00000-0000-4000-8000-100000000004'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[contacts] WHERE [id] = N'c0c00000-0000-4000-8000-100000000005')
    INSERT INTO [crm].[contacts] (
        [id], [first_name], [last_name], [email], [phone], [mobile], [title], [department], [mailing_street], [mailing_city], [mailing_state], [mailing_postal_code], [mailing_country], [account_id]
    )
    VALUES (
        N'c0c00000-0000-4000-8000-100000000005',
        N'Priya',
        N'Sharma',
        N'p.sharma@retailplus.com',
        N'555-0501',
        N'555-0509',
        N'VP Purchasing',
        N'Procurement',
        N'1720 Commerce St',
        N'Dallas',
        N'TX',
        N'75201',
        N'US',
        N'a0c00000-0000-4000-8000-100000000005'

    );





-- ----------------------------------------------------------------------------
-- Lead
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[leads] WHERE [id] = N'1eadc000-0000-4000-8000-100000000001')
    INSERT INTO [crm].[leads] (
        [id], [first_name], [last_name], [email], [phone], [company], [title], [website], [description], [annual_revenue], [number_of_employees], [is_converted], [converted_account_id], [status_id], [source_id], [industry_id]
    )
    VALUES (
        N'1eadc000-0000-4000-8000-100000000001',
        N'Michael',
        N'Nguyen',
        N'm.nguyen@sunrise-dental.com',
        N'555-1001',
        N'Sunrise Dental',
        N'Office Manager',
        N'https://sunrise-dental.example.com',
        N'New inbound lead requesting a patient communication workflow review.',
        2500000,
        28,
        0,
        NULL,
        N'1eadcc00-0000-4000-8000-100000000001',
        N'1eadcc01-0000-4000-8000-100000000001',
        N'10100070-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[leads] WHERE [id] = N'1eadc000-0000-4000-8000-100000000002')
    INSERT INTO [crm].[leads] (
        [id], [first_name], [last_name], [email], [phone], [company], [title], [website], [description], [annual_revenue], [number_of_employees], [is_converted], [converted_account_id], [status_id], [source_id], [industry_id]
    )
    VALUES (
        N'1eadc000-0000-4000-8000-100000000002',
        N'Amanda',
        N'Brooks',
        N'a.brooks@vistaclinic.com',
        N'555-1002',
        N'Vista Clinic Group',
        N'Practice Administrator',
        N'https://vistaclinic.example.com',
        N'Multi-location practice comparing pricing and implementation services.',
        8700000,
        74,
        0,
        NULL,
        N'1eadcc00-0000-4000-8000-100000000002',
        N'1eadcc01-0000-4000-8000-100000000003',
        N'10100070-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[leads] WHERE [id] = N'1eadc000-0000-4000-8000-100000000003')
    INSERT INTO [crm].[leads] (
        [id], [first_name], [last_name], [email], [phone], [company], [title], [website], [description], [annual_revenue], [number_of_employees], [is_converted], [converted_account_id], [status_id], [source_id], [industry_id]
    )
    VALUES (
        N'1eadc000-0000-4000-8000-100000000003',
        N'Robert',
        N'Kim',
        N'r.kim@nextech.co',
        N'555-1003',
        N'NexTech Co',
        N'IT Director',
        N'https://nextech.example.com',
        N'Qualified technology prospect interested in sandbox environments and connectors.',
        19000000,
        120,
        0,
        NULL,
        N'1eadcc00-0000-4000-8000-100000000003',
        N'1eadcc01-0000-4000-8000-100000000004',
        N'10100070-0000-4000-8000-100000000002'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[leads] WHERE [id] = N'1eadc000-0000-4000-8000-100000000004')
    INSERT INTO [crm].[leads] (
        [id], [first_name], [last_name], [email], [phone], [company], [title], [website], [description], [annual_revenue], [number_of_employees], [is_converted], [converted_account_id], [status_id], [source_id], [industry_id]
    )
    VALUES (
        N'1eadc000-0000-4000-8000-100000000004',
        N'Elena',
        N'Vasquez',
        N'e.vasquez@meridian-health.org',
        N'555-1004',
        N'Meridian Health',
        N'COO',
        N'https://meridian-health.example.org',
        N'Early healthcare inquiry with budget owner identified.',
        32000000,
        210,
        0,
        NULL,
        N'1eadcc00-0000-4000-8000-100000000001',
        N'1eadcc01-0000-4000-8000-100000000002',
        N'10100070-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[leads] WHERE [id] = N'1eadc000-0000-4000-8000-100000000005')
    INSERT INTO [crm].[leads] (
        [id], [first_name], [last_name], [email], [phone], [company], [title], [website], [description], [annual_revenue], [number_of_employees], [is_converted], [converted_account_id], [status_id], [source_id], [industry_id]
    )
    VALUES (
        N'1eadc000-0000-4000-8000-100000000005',
        N'Thomas',
        N'Adeyemi',
        N't.adeyemi@freshmarket.com',
        N'555-1005',
        N'Fresh Market Chain',
        N'VP Technology',
        N'https://freshmarket.example.com',
        N'Retail lead referred by an internal customer success manager.',
        41000000,
        330,
        0,
        NULL,
        N'1eadcc00-0000-4000-8000-100000000002',
        N'1eadcc01-0000-4000-8000-100000000005',
        N'10100070-0000-4000-8000-100000000005'

    );





-- ----------------------------------------------------------------------------
-- Opportunity
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[opportunities] WHERE [id] = N'099c0000-0000-4000-8000-100000000001')
    INSERT INTO [crm].[opportunities] (
        [id], [name], [amount], [close_date], [description], [next_step], [lead_source], [account_id], [stage_id]
    )
    VALUES (
        N'099c0000-0000-4000-8000-100000000001',
        N'Acme Dental - Enterprise Suite',
        97500,
        N'2026-06-30',
        N'Enterprise platform evaluation for operations, patient engagement, and staff enablement.',
        N'Confirm legal review owner and implementation window.',
        N'Partner Referral',
        N'a0c00000-0000-4000-8000-100000000001',
        N'0998a900-0000-4000-8000-100000000003'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunities] WHERE [id] = N'099c0000-0000-4000-8000-100000000002')
    INSERT INTO [crm].[opportunities] (
        [id], [name], [amount], [close_date], [description], [next_step], [lead_source], [account_id], [stage_id]
    )
    VALUES (
        N'099c0000-0000-4000-8000-100000000002',
        N'TechBridge - Platform Expansion',
        145000,
        N'2026-07-31',
        N'Expansion opportunity covering additional platform seats and service packaging.',
        N'Send security package and revised partner services estimate.',
        N'Web',
        N'a0c00000-0000-4000-8000-100000000002',
        N'0998a900-0000-4000-8000-100000000002'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunities] WHERE [id] = N'099c0000-0000-4000-8000-100000000003')
    INSERT INTO [crm].[opportunities] (
        [id], [name], [amount], [close_date], [description], [next_step], [lead_source], [account_id], [stage_id]
    )
    VALUES (
        N'099c0000-0000-4000-8000-100000000003',
        N'CapStone - Analytics Module',
        32500,
        N'2026-05-31',
        N'Analytics module and compliance reporting add-on for financial advisors.',
        N'Schedule executive readout with finance and compliance stakeholders.',
        N'Trade Show',
        N'a0c00000-0000-4000-8000-100000000003',
        N'0998a900-0000-4000-8000-100000000004'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunities] WHERE [id] = N'099c0000-0000-4000-8000-100000000004')
    INSERT INTO [crm].[opportunities] (
        [id], [name], [amount], [close_date], [description], [next_step], [lead_source], [account_id], [stage_id]
    )
    VALUES (
        N'099c0000-0000-4000-8000-100000000004',
        N'MediSystems - Pro Edition',
        47500,
        N'2026-08-31',
        N'Professional edition rollout for care coordination and IT service workflows.',
        N'Complete technical discovery with integrations team.',
        N'Phone Inquiry',
        N'a0c00000-0000-4000-8000-100000000004',
        N'0998a900-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunities] WHERE [id] = N'099c0000-0000-4000-8000-100000000005')
    INSERT INTO [crm].[opportunities] (
        [id], [name], [amount], [close_date], [description], [next_step], [lead_source], [account_id], [stage_id]
    )
    VALUES (
        N'099c0000-0000-4000-8000-100000000005',
        N'RetailPlus - Services Bundle',
        27500,
        N'2026-09-30',
        N'Services and enablement bundle for store support and procurement coordination.',
        N'Align procurement scope and delivery schedule.',
        N'Employee Referral',
        N'a0c00000-0000-4000-8000-100000000005',
        N'0998a900-0000-4000-8000-100000000002'

    );





-- ----------------------------------------------------------------------------
-- Activity
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[activities] WHERE [id] = N'ac710007-0000-4000-8000-100000000001')
    INSERT INTO [crm].[activities] (
        [id], [subject], [description], [activity_date], [due_date], [is_closed], [priority], [status], [type_id], [account_id], [contact_id], [opportunity_id], [lead_id]
    )
    VALUES (
        N'ac710007-0000-4000-8000-100000000001',
        N'Discovery Call - Acme Dental',
        N'Initial discovery call to understand requirements',
        N'2026-05-01',
        N'2026-05-01',
        1,
        N'High',
        N'Completed',
        N'ac71ec00-0000-4000-8000-100000000002',
        N'a0c00000-0000-4000-8000-100000000001',
        N'c0c00000-0000-4000-8000-100000000001',
        N'099c0000-0000-4000-8000-100000000001',
        NULL

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[activities] WHERE [id] = N'ac710007-0000-4000-8000-100000000002')
    INSERT INTO [crm].[activities] (
        [id], [subject], [description], [activity_date], [due_date], [is_closed], [priority], [status], [type_id], [account_id], [contact_id], [opportunity_id], [lead_id]
    )
    VALUES (
        N'ac710007-0000-4000-8000-100000000002',
        N'Demo - TechBridge Platform',
        N'Full product demonstration for expansion proposal',
        N'2026-05-10',
        N'2026-05-10',
        1,
        N'High',
        N'Completed',
        N'ac71ec00-0000-4000-8000-100000000003',
        N'a0c00000-0000-4000-8000-100000000002',
        N'c0c00000-0000-4000-8000-100000000002',
        N'099c0000-0000-4000-8000-100000000002',
        NULL

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[activities] WHERE [id] = N'ac710007-0000-4000-8000-100000000003')
    INSERT INTO [crm].[activities] (
        [id], [subject], [description], [activity_date], [due_date], [is_closed], [priority], [status], [type_id], [account_id], [contact_id], [opportunity_id], [lead_id]
    )
    VALUES (
        N'ac710007-0000-4000-8000-100000000003',
        N'Follow-up Email - CapStone Analytics',
        N'Sent ROI analysis and case studies',
        N'2026-05-12',
        N'2026-05-12',
        1,
        N'Normal',
        N'Completed',
        N'ac71ec00-0000-4000-8000-100000000001',
        N'a0c00000-0000-4000-8000-100000000003',
        N'c0c00000-0000-4000-8000-100000000003',
        N'099c0000-0000-4000-8000-100000000003',
        NULL

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[activities] WHERE [id] = N'ac710007-0000-4000-8000-100000000004')
    INSERT INTO [crm].[activities] (
        [id], [subject], [description], [activity_date], [due_date], [is_closed], [priority], [status], [type_id], [account_id], [contact_id], [opportunity_id], [lead_id]
    )
    VALUES (
        N'ac710007-0000-4000-8000-100000000004',
        N'Intro Call - MediSystems',
        N'First contact, qualify needs and budget',
        N'2026-05-19',
        N'2026-05-19',
        0,
        N'Normal',
        N'Planned',
        N'ac71ec00-0000-4000-8000-100000000002',
        N'a0c00000-0000-4000-8000-100000000004',
        N'c0c00000-0000-4000-8000-100000000004',
        N'099c0000-0000-4000-8000-100000000004',
        NULL

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[activities] WHERE [id] = N'ac710007-0000-4000-8000-100000000005')
    INSERT INTO [crm].[activities] (
        [id], [subject], [description], [activity_date], [due_date], [is_closed], [priority], [status], [type_id], [account_id], [contact_id], [opportunity_id], [lead_id]
    )
    VALUES (
        N'ac710007-0000-4000-8000-100000000005',
        N'Proposal Review Meeting - RetailPlus',
        N'Walk through the services bundle proposal',
        N'2026-05-28',
        N'2026-05-28',
        0,
        N'Normal',
        N'Planned',
        N'ac71ec00-0000-4000-8000-100000000003',
        N'a0c00000-0000-4000-8000-100000000005',
        N'c0c00000-0000-4000-8000-100000000005',
        N'099c0000-0000-4000-8000-100000000005',
        NULL

    );





-- ----------------------------------------------------------------------------
-- OpportunityContact
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[opportunity_contacts] WHERE [id] = N'0c0c0000-0000-4000-8000-100000000001')
    INSERT INTO [crm].[opportunity_contacts] (
        [id], [opportunity_id], [contact_id]
    )
    VALUES (
        N'0c0c0000-0000-4000-8000-100000000001',
        N'099c0000-0000-4000-8000-100000000001',
        N'c0c00000-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunity_contacts] WHERE [id] = N'0c0c0000-0000-4000-8000-100000000002')
    INSERT INTO [crm].[opportunity_contacts] (
        [id], [opportunity_id], [contact_id]
    )
    VALUES (
        N'0c0c0000-0000-4000-8000-100000000002',
        N'099c0000-0000-4000-8000-100000000002',
        N'c0c00000-0000-4000-8000-100000000002'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunity_contacts] WHERE [id] = N'0c0c0000-0000-4000-8000-100000000003')
    INSERT INTO [crm].[opportunity_contacts] (
        [id], [opportunity_id], [contact_id]
    )
    VALUES (
        N'0c0c0000-0000-4000-8000-100000000003',
        N'099c0000-0000-4000-8000-100000000003',
        N'c0c00000-0000-4000-8000-100000000003'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunity_contacts] WHERE [id] = N'0c0c0000-0000-4000-8000-100000000004')
    INSERT INTO [crm].[opportunity_contacts] (
        [id], [opportunity_id], [contact_id]
    )
    VALUES (
        N'0c0c0000-0000-4000-8000-100000000004',
        N'099c0000-0000-4000-8000-100000000004',
        N'c0c00000-0000-4000-8000-100000000004'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[opportunity_contacts] WHERE [id] = N'0c0c0000-0000-4000-8000-100000000005')
    INSERT INTO [crm].[opportunity_contacts] (
        [id], [opportunity_id], [contact_id]
    )
    VALUES (
        N'0c0c0000-0000-4000-8000-100000000005',
        N'099c0000-0000-4000-8000-100000000005',
        N'c0c00000-0000-4000-8000-100000000005'

    );





-- ----------------------------------------------------------------------------
-- Quote
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[quotes] WHERE [id] = N'9407e000-0000-4000-8000-100000000001')
    INSERT INTO [crm].[quotes] (
        [id], [name], [quote_number], [expiration_date], [description], [subtotal], [discount], [tax], [total_price], [opportunity_id], [account_id], [status_id]
    )
    VALUES (
        N'9407e000-0000-4000-8000-100000000001',
        N'Q-2026-001 Acme Enterprise',
        N'Q-2026-001',
        N'2026-07-31',
        N'Enterprise suite package with implementation and annual support.',
        97500,
        0,
        0,
        97500,
        N'099c0000-0000-4000-8000-100000000001',
        N'a0c00000-0000-4000-8000-100000000001',
        N'9407ec00-0000-4000-8000-100000000003'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quotes] WHERE [id] = N'9407e000-0000-4000-8000-100000000002')
    INSERT INTO [crm].[quotes] (
        [id], [name], [quote_number], [expiration_date], [description], [subtotal], [discount], [tax], [total_price], [opportunity_id], [account_id], [status_id]
    )
    VALUES (
        N'9407e000-0000-4000-8000-100000000002',
        N'Q-2026-002 TechBridge Platform',
        N'Q-2026-002',
        N'2026-08-31',
        N'Multi-seat professional edition expansion and implementation package.',
        145000,
        0,
        0,
        145000,
        N'099c0000-0000-4000-8000-100000000002',
        N'a0c00000-0000-4000-8000-100000000002',
        N'9407ec00-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quotes] WHERE [id] = N'9407e000-0000-4000-8000-100000000003')
    INSERT INTO [crm].[quotes] (
        [id], [name], [quote_number], [expiration_date], [description], [subtotal], [discount], [tax], [total_price], [opportunity_id], [account_id], [status_id]
    )
    VALUES (
        N'9407e000-0000-4000-8000-100000000003',
        N'Q-2026-003 CapStone Analytics',
        N'Q-2026-003',
        N'2026-06-15',
        N'Analytics module acceptance package with added training.',
        32500,
        0,
        0,
        32500,
        N'099c0000-0000-4000-8000-100000000003',
        N'a0c00000-0000-4000-8000-100000000003',
        N'9407ec00-0000-4000-8000-100000000004'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quotes] WHERE [id] = N'9407e000-0000-4000-8000-100000000004')
    INSERT INTO [crm].[quotes] (
        [id], [name], [quote_number], [expiration_date], [description], [subtotal], [discount], [tax], [total_price], [opportunity_id], [account_id], [status_id]
    )
    VALUES (
        N'9407e000-0000-4000-8000-100000000004',
        N'Q-2026-004 MediSystems Pro Edition',
        N'Q-2026-004',
        N'2026-09-30',
        N'Professional edition, implementation, and annual support proposal.',
        47500,
        2500,
        0,
        45000,
        N'099c0000-0000-4000-8000-100000000004',
        N'a0c00000-0000-4000-8000-100000000004',
        N'9407ec00-0000-4000-8000-100000000002'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quotes] WHERE [id] = N'9407e000-0000-4000-8000-100000000005')
    INSERT INTO [crm].[quotes] (
        [id], [name], [quote_number], [expiration_date], [description], [subtotal], [discount], [tax], [total_price], [opportunity_id], [account_id], [status_id]
    )
    VALUES (
        N'9407e000-0000-4000-8000-100000000005',
        N'Q-2026-005 RetailPlus Services',
        N'Q-2026-005',
        N'2026-10-31',
        N'Services bundle for procurement and store operations enablement.',
        27500,
        0,
        0,
        27500,
        N'099c0000-0000-4000-8000-100000000005',
        N'a0c00000-0000-4000-8000-100000000005',
        N'9407ec00-0000-4000-8000-100000000003'

    );





-- ----------------------------------------------------------------------------
-- QuoteLineItem
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[quote_line_items] WHERE [id] = N'9407e110-0000-4000-8000-100000000001')
    INSERT INTO [crm].[quote_line_items] (
        [id], [quantity], [unit_price], [discount], [total_price], [description], [sort_order], [quote_id], [product_id]
    )
    VALUES (
        N'9407e110-0000-4000-8000-100000000001',
        1,
        75000,
        0,
        75000,
        N'Enterprise platform license.',
        1,
        N'9407e000-0000-4000-8000-100000000001',
        N'9700d000-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_line_items] WHERE [id] = N'9407e110-0000-4000-8000-100000000002')
    INSERT INTO [crm].[quote_line_items] (
        [id], [quantity], [unit_price], [discount], [total_price], [description], [sort_order], [quote_id], [product_id]
    )
    VALUES (
        N'9407e110-0000-4000-8000-100000000002',
        1,
        15000,
        0,
        15000,
        N'Standard implementation services.',
        2,
        N'9407e000-0000-4000-8000-100000000001',
        N'9700d000-0000-4000-8000-100000000003'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_line_items] WHERE [id] = N'9407e110-0000-4000-8000-100000000003')
    INSERT INTO [crm].[quote_line_items] (
        [id], [quantity], [unit_price], [discount], [total_price], [description], [sort_order], [quote_id], [product_id]
    )
    VALUES (
        N'9407e110-0000-4000-8000-100000000003',
        1,
        7500,
        0,
        7500,
        N'Annual support package.',
        3,
        N'9407e000-0000-4000-8000-100000000001',
        N'9700d000-0000-4000-8000-100000000004'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_line_items] WHERE [id] = N'9407e110-0000-4000-8000-100000000004')
    INSERT INTO [crm].[quote_line_items] (
        [id], [quantity], [unit_price], [discount], [total_price], [description], [sort_order], [quote_id], [product_id]
    )
    VALUES (
        N'9407e110-0000-4000-8000-100000000004',
        5,
        25000,
        0,
        125000,
        N'Five professional edition licenses.',
        1,
        N'9407e000-0000-4000-8000-100000000002',
        N'9700d000-0000-4000-8000-100000000002'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_line_items] WHERE [id] = N'9407e110-0000-4000-8000-100000000005')
    INSERT INTO [crm].[quote_line_items] (
        [id], [quantity], [unit_price], [discount], [total_price], [description], [sort_order], [quote_id], [product_id]
    )
    VALUES (
        N'9407e110-0000-4000-8000-100000000005',
        1,
        20000,
        0,
        20000,
        N'Expanded implementation package.',
        2,
        N'9407e000-0000-4000-8000-100000000002',
        N'9700d000-0000-4000-8000-100000000003'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_line_items] WHERE [id] = N'9407e110-0000-4000-8000-100000000006')
    INSERT INTO [crm].[quote_line_items] (
        [id], [quantity], [unit_price], [discount], [total_price], [description], [sort_order], [quote_id], [product_id]
    )
    VALUES (
        N'9407e110-0000-4000-8000-100000000006',
        1,
        25000,
        0,
        25000,
        N'Professional edition analytics module.',
        1,
        N'9407e000-0000-4000-8000-100000000003',
        N'9700d000-0000-4000-8000-100000000002'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_line_items] WHERE [id] = N'9407e110-0000-4000-8000-100000000007')
    INSERT INTO [crm].[quote_line_items] (
        [id], [quantity], [unit_price], [discount], [total_price], [description], [sort_order], [quote_id], [product_id]
    )
    VALUES (
        N'9407e110-0000-4000-8000-100000000007',
        1,
        7500,
        0,
        7500,
        N'Analytics support package.',
        2,
        N'9407e000-0000-4000-8000-100000000003',
        N'9700d000-0000-4000-8000-100000000004'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_line_items] WHERE [id] = N'9407e110-0000-4000-8000-100000000008')
    INSERT INTO [crm].[quote_line_items] (
        [id], [quantity], [unit_price], [discount], [total_price], [description], [sort_order], [quote_id], [product_id]
    )
    VALUES (
        N'9407e110-0000-4000-8000-100000000008',
        1,
        25000,
        0,
        25000,
        N'Professional edition core license.',
        1,
        N'9407e000-0000-4000-8000-100000000004',
        N'9700d000-0000-4000-8000-100000000002'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_line_items] WHERE [id] = N'9407e110-0000-4000-8000-100000000009')
    INSERT INTO [crm].[quote_line_items] (
        [id], [quantity], [unit_price], [discount], [total_price], [description], [sort_order], [quote_id], [product_id]
    )
    VALUES (
        N'9407e110-0000-4000-8000-100000000009',
        1,
        15000,
        0,
        15000,
        N'Implementation services for care workflows.',
        2,
        N'9407e000-0000-4000-8000-100000000004',
        N'9700d000-0000-4000-8000-100000000003'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_line_items] WHERE [id] = N'9407e110-0000-4000-8000-100000000010')
    INSERT INTO [crm].[quote_line_items] (
        [id], [quantity], [unit_price], [discount], [total_price], [description], [sort_order], [quote_id], [product_id]
    )
    VALUES (
        N'9407e110-0000-4000-8000-100000000010',
        1,
        7500,
        2500,
        5000,
        N'Discounted annual support.',
        3,
        N'9407e000-0000-4000-8000-100000000004',
        N'9700d000-0000-4000-8000-100000000004'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_line_items] WHERE [id] = N'9407e110-0000-4000-8000-100000000011')
    INSERT INTO [crm].[quote_line_items] (
        [id], [quantity], [unit_price], [discount], [total_price], [description], [sort_order], [quote_id], [product_id]
    )
    VALUES (
        N'9407e110-0000-4000-8000-100000000011',
        1,
        15000,
        0,
        15000,
        N'Procurement implementation services.',
        1,
        N'9407e000-0000-4000-8000-100000000005',
        N'9700d000-0000-4000-8000-100000000003'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_line_items] WHERE [id] = N'9407e110-0000-4000-8000-100000000012')
    INSERT INTO [crm].[quote_line_items] (
        [id], [quantity], [unit_price], [discount], [total_price], [description], [sort_order], [quote_id], [product_id]
    )
    VALUES (
        N'9407e110-0000-4000-8000-100000000012',
        1,
        5000,
        0,
        5000,
        N'Store operations training package.',
        2,
        N'9407e000-0000-4000-8000-100000000005',
        N'9700d000-0000-4000-8000-100000000005'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[quote_line_items] WHERE [id] = N'9407e110-0000-4000-8000-100000000013')
    INSERT INTO [crm].[quote_line_items] (
        [id], [quantity], [unit_price], [discount], [total_price], [description], [sort_order], [quote_id], [product_id]
    )
    VALUES (
        N'9407e110-0000-4000-8000-100000000013',
        1,
        7500,
        0,
        7500,
        N'Support for store rollout.',
        3,
        N'9407e000-0000-4000-8000-100000000005',
        N'9700d000-0000-4000-8000-100000000004'

    );





-- ----------------------------------------------------------------------------
-- BusinessUnit
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[business_units] WHERE [id] = N'b0510000-0000-4000-8000-100000000001')
    INSERT INTO [crm].[business_units] (
        [id], [name], [code], [description], [region], [is_active]
    )
    VALUES (
        N'b0510000-0000-4000-8000-100000000001',
        N'West Commercial',
        N'WEST-COM',
        N'Commercial sales and service for western regional accounts',
        N'West',
        1

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[business_units] WHERE [id] = N'b0510000-0000-4000-8000-100000000002')
    INSERT INTO [crm].[business_units] (
        [id], [name], [code], [description], [region], [is_active]
    )
    VALUES (
        N'b0510000-0000-4000-8000-100000000002',
        N'National Service',
        N'NAT-SVC',
        N'Shared service and knowledge operations',
        N'National',
        1

    );





-- ----------------------------------------------------------------------------
-- Territory
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[territories] WHERE [id] = N'7e441000-0000-4000-8000-100000000001')
    INSERT INTO [crm].[territories] (
        [id], [name], [code], [region], [country], [state], [is_active], [business_unit_id]
    )
    VALUES (
        N'7e441000-0000-4000-8000-100000000001',
        N'Pacific Northwest',
        N'PNW',
        N'West',
        N'USA',
        N'WA',
        1,
        N'b0510000-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[territories] WHERE [id] = N'7e441000-0000-4000-8000-100000000002')
    INSERT INTO [crm].[territories] (
        [id], [name], [code], [region], [country], [state], [is_active], [business_unit_id]
    )
    VALUES (
        N'7e441000-0000-4000-8000-100000000002',
        N'California Enterprise',
        N'CA-ENT',
        N'West',
        N'USA',
        N'CA',
        1,
        N'b0510000-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[territories] WHERE [id] = N'7e441000-0000-4000-8000-100000000003')
    INSERT INTO [crm].[territories] (
        [id], [name], [code], [region], [country], [state], [is_active], [business_unit_id]
    )
    VALUES (
        N'7e441000-0000-4000-8000-100000000003',
        N'Remote Service Desk',
        N'RSD',
        N'National',
        N'USA',
        NULL,
        1,
        N'b0510000-0000-4000-8000-100000000002'

    );





-- ----------------------------------------------------------------------------
-- Queue
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[queues] WHERE [id] = N'9e0e0000-0000-4000-8000-100000000001')
    INSERT INTO [crm].[queues] (
        [id], [name], [queue_type], [description], [email], [is_active], [business_unit_id]
    )
    VALUES (
        N'9e0e0000-0000-4000-8000-100000000001',
        N'Enterprise Onboarding',
        N'Sales',
        N'High-touch queue for new enterprise opportunities',
        N'enterprise-onboarding@example.com',
        1,
        N'b0510000-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[queues] WHERE [id] = N'9e0e0000-0000-4000-8000-100000000002')
    INSERT INTO [crm].[queues] (
        [id], [name], [queue_type], [description], [email], [is_active], [business_unit_id]
    )
    VALUES (
        N'9e0e0000-0000-4000-8000-100000000002',
        N'Knowledge Review',
        N'Service',
        N'Review queue for externally visible knowledge articles',
        N'kb-review@example.com',
        1,
        N'b0510000-0000-4000-8000-100000000002'

    );





-- ----------------------------------------------------------------------------
-- Address
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[addresses] WHERE [id] = N'add00000-0000-4000-8000-100000000001')
    INSERT INTO [crm].[addresses] (
        [id], [name], [address_type], [street1], [street2], [city], [state], [postal_code], [country], [latitude], [longitude], [is_primary], [account_id], [contact_id]
    )
    VALUES (
        N'add00000-0000-4000-8000-100000000001',
        N'Acme Dental Billing',
        N'Billing',
        N'415 Market St',
        N'Suite 300',
        N'San Francisco',
        N'CA',
        N'94105',
        N'USA',
        37.7899,
        -122.3942,
        1,
        N'a0c00000-0000-4000-8000-100000000001',
        NULL

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[addresses] WHERE [id] = N'add00000-0000-4000-8000-100000000002')
    INSERT INTO [crm].[addresses] (
        [id], [name], [address_type], [street1], [street2], [city], [state], [postal_code], [country], [latitude], [longitude], [is_primary], [account_id], [contact_id]
    )
    VALUES (
        N'add00000-0000-4000-8000-100000000002',
        N'Acme Dental Shipping',
        N'Shipping',
        N'220 Harbor Way',
        NULL,
        N'Oakland',
        N'CA',
        N'94607',
        N'USA',
        37.7955,
        -122.2791,
        0,
        N'a0c00000-0000-4000-8000-100000000001',
        NULL

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[addresses] WHERE [id] = N'add00000-0000-4000-8000-100000000003')
    INSERT INTO [crm].[addresses] (
        [id], [name], [address_type], [street1], [street2], [city], [state], [postal_code], [country], [latitude], [longitude], [is_primary], [account_id], [contact_id]
    )
    VALUES (
        N'add00000-0000-4000-8000-100000000003',
        N'Maya Johnson Mailing',
        N'Mailing',
        N'18 Pine Ave',
        N'Apt 6C',
        N'Portland',
        N'OR',
        N'97205',
        N'USA',
        45.5202,
        -122.6742,
        1,
        NULL,
        N'c0c00000-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[addresses] WHERE [id] = N'add00000-0000-4000-8000-100000000004')
    INSERT INTO [crm].[addresses] (
        [id], [name], [address_type], [street1], [street2], [city], [state], [postal_code], [country], [latitude], [longitude], [is_primary], [account_id], [contact_id]
    )
    VALUES (
        N'add00000-0000-4000-8000-100000000004',
        N'Northstar Supply Billing',
        N'Billing',
        N'780 Lakeview Dr',
        NULL,
        N'Minneapolis',
        N'MN',
        N'55402',
        N'USA',
        44.9778,
        -93.265,
        1,
        N'a0c00000-0000-4000-8000-100000000002',
        NULL

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[addresses] WHERE [id] = N'add00000-0000-4000-8000-100000000005')
    INSERT INTO [crm].[addresses] (
        [id], [name], [address_type], [street1], [street2], [city], [state], [postal_code], [country], [latitude], [longitude], [is_primary], [account_id], [contact_id]
    )
    VALUES (
        N'add00000-0000-4000-8000-100000000005',
        N'Redwood Logistics Dock',
        N'Shipping',
        N'1000 Portside Rd',
        N'Dock 12',
        N'Tacoma',
        N'WA',
        N'98421',
        N'USA',
        47.2529,
        -122.4443,
        0,
        N'a0c00000-0000-4000-8000-100000000003',
        NULL

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[addresses] WHERE [id] = N'add00000-0000-4000-8000-100000000006')
    INSERT INTO [crm].[addresses] (
        [id], [name], [address_type], [street1], [street2], [city], [state], [postal_code], [country], [latitude], [longitude], [is_primary], [account_id], [contact_id]
    )
    VALUES (
        N'add00000-0000-4000-8000-100000000006',
        N'Jordan Lee Mailing',
        N'Mailing',
        N'501 Innovation Pkwy',
        NULL,
        N'Austin',
        N'TX',
        N'78701',
        N'USA',
        30.2672,
        -97.7431,
        1,
        NULL,
        N'c0c00000-0000-4000-8000-100000000002'

    );





-- ----------------------------------------------------------------------------
-- ActivityParty
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[activity_parties] WHERE [id] = N'ac71fa00-0000-4000-8000-100000000001')
    INSERT INTO [crm].[activity_parties] (
        [id], [role], [party_type], [party_id], [display_name], [email], [is_required], [responded_status], [activity_id]
    )
    VALUES (
        N'ac71fa00-0000-4000-8000-100000000001',
        N'Organizer',
        N'User',
        N'pdsh_admin',
        N'Priya Admin',
        N'priya.admin@example.com',
        1,
        N'Accepted',
        N'ac710007-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[activity_parties] WHERE [id] = N'ac71fa00-0000-4000-8000-100000000002')
    INSERT INTO [crm].[activity_parties] (
        [id], [role], [party_type], [party_id], [display_name], [email], [is_required], [responded_status], [activity_id]
    )
    VALUES (
        N'ac71fa00-0000-4000-8000-100000000002',
        N'Required Attendee',
        N'Contact',
        N'c0c00000-0000-4000-8000-100000000001',
        N'Maya Johnson',
        N'maya.johnson@example.com',
        1,
        N'Accepted',
        N'ac710007-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[activity_parties] WHERE [id] = N'ac71fa00-0000-4000-8000-100000000003')
    INSERT INTO [crm].[activity_parties] (
        [id], [role], [party_type], [party_id], [display_name], [email], [is_required], [responded_status], [activity_id]
    )
    VALUES (
        N'ac71fa00-0000-4000-8000-100000000003',
        N'Optional Attendee',
        N'Account',
        N'a0c00000-0000-4000-8000-100000000001',
        N'Acme Dental',
        N'info@acme-dental.example.com',
        0,
        N'Tentative',
        N'ac710007-0000-4000-8000-100000000002'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[activity_parties] WHERE [id] = N'ac71fa00-0000-4000-8000-100000000004')
    INSERT INTO [crm].[activity_parties] (
        [id], [role], [party_type], [party_id], [display_name], [email], [is_required], [responded_status], [activity_id]
    )
    VALUES (
        N'ac71fa00-0000-4000-8000-100000000004',
        N'Regarding',
        N'Opportunity',
        N'099c0000-0000-4000-8000-100000000002',
        N'Northstar Renewal',
        NULL,
        0,
        N'NotRequired',
        N'ac710007-0000-4000-8000-100000000003'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[activity_parties] WHERE [id] = N'ac71fa00-0000-4000-8000-100000000005')
    INSERT INTO [crm].[activity_parties] (
        [id], [role], [party_type], [party_id], [display_name], [email], [is_required], [responded_status], [activity_id]
    )
    VALUES (
        N'ac71fa00-0000-4000-8000-100000000005',
        N'Sender',
        N'User',
        N'pdsh_ops',
        N'Morgan Ops',
        N'morgan.ops@example.com',
        1,
        N'Sent',
        N'ac710007-0000-4000-8000-100000000004'

    );





-- ----------------------------------------------------------------------------
-- KnowledgeArticle
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[knowledge_articles] WHERE [id] = N'a471c1e0-0000-4000-8000-100000000001')
    INSERT INTO [crm].[knowledge_articles] (
        [id], [title], [slug], [summary], [body], [language], [status], [publish_date], [view_count], [is_public], [tags]
    )
    VALUES (
        N'a471c1e0-0000-4000-8000-100000000001',
        N'Enterprise Onboarding Checklist',
        N'enterprise-onboarding-checklist',
        N'Checklist used by implementation teams before go-live.',
        N'Confirm stakeholders, environments, data load, access review, and support handoff.',
        N'en-US',
        N'Published',
        N'2026-01-08',
        312,
        1,
        N'["onboarding","enterprise","implementation"]'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[knowledge_articles] WHERE [id] = N'a471c1e0-0000-4000-8000-100000000002')
    INSERT INTO [crm].[knowledge_articles] (
        [id], [title], [slug], [summary], [body], [language], [status], [publish_date], [view_count], [is_public], [tags]
    )
    VALUES (
        N'a471c1e0-0000-4000-8000-100000000002',
        N'Quote Discount Approval Guide',
        N'quote-discount-approval-guide',
        N'Internal guide for discount thresholds and finance approval.',
        N'Discounts above standard guardrails require finance review and attached business justification.',
        N'en-US',
        N'Draft',
        NULL,
        47,
        0,
        N'["quote","finance","approvals"]'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[knowledge_articles] WHERE [id] = N'a471c1e0-0000-4000-8000-100000000003')
    INSERT INTO [crm].[knowledge_articles] (
        [id], [title], [slug], [summary], [body], [language], [status], [publish_date], [view_count], [is_public], [tags]
    )
    VALUES (
        N'a471c1e0-0000-4000-8000-100000000003',
        N'Data Import Troubleshooting',
        N'data-import-troubleshooting',
        N'Common validation and mapping fixes for imported CRM data.',
        N'Review required fields, duplicate keys, invalid references, and provider-specific type mappings.',
        N'en-US',
        N'Published',
        N'2026-02-14',
        1289,
        1,
        N'["data-import","validation","support"]'

    );





-- ----------------------------------------------------------------------------
-- ArticleComment
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[article_comments] WHERE [id] = N'a471c0de-0000-4000-8000-100000000001')
    INSERT INTO [crm].[article_comments] (
        [id], [subject], [body], [author_name], [sentiment], [is_internal], [created_at], [article_id]
    )
    VALUES (
        N'a471c0de-0000-4000-8000-100000000001',
        N'Add security handoff step',
        N'Include evidence that admin access was reviewed before production handoff.',
        N'Priya Admin',
        N'Positive',
        1,
        N'2026-01-09T16:30:00Z',
        N'a471c1e0-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[article_comments] WHERE [id] = N'a471c0de-0000-4000-8000-100000000002')
    INSERT INTO [crm].[article_comments] (
        [id], [subject], [body], [author_name], [sentiment], [is_internal], [created_at], [article_id]
    )
    VALUES (
        N'a471c0de-0000-4000-8000-100000000002',
        N'Finance example needed',
        N'Add one worked example for a multi-year discount approval.',
        N'Iris Finance',
        N'Neutral',
        1,
        N'2026-01-12T19:10:00Z',
        N'a471c1e0-0000-4000-8000-100000000002'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[article_comments] WHERE [id] = N'a471c0de-0000-4000-8000-100000000003')
    INSERT INTO [crm].[article_comments] (
        [id], [subject], [body], [author_name], [sentiment], [is_internal], [created_at], [article_id]
    )
    VALUES (
        N'a471c0de-0000-4000-8000-100000000003',
        N'Helpful import notes',
        N'The duplicate key guidance reduced support back-and-forth on the last migration.',
        N'Morgan Ops',
        N'Positive',
        0,
        N'2026-02-17T11:45:00Z',
        N'a471c1e0-0000-4000-8000-100000000003'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[article_comments] WHERE [id] = N'a471c0de-0000-4000-8000-100000000004')
    INSERT INTO [crm].[article_comments] (
        [id], [subject], [body], [author_name], [sentiment], [is_internal], [created_at], [article_id]
    )
    VALUES (
        N'a471c0de-0000-4000-8000-100000000004',
        N'Clarify lookup failures',
        N'We should distinguish missing foreign keys from invalid UUID syntax.',
        N'Rowan Support',
        N'Neutral',
        1,
        N'2026-02-18T14:05:00Z',
        N'a471c1e0-0000-4000-8000-100000000003'

    );





-- ----------------------------------------------------------------------------
-- QueueItem
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [crm].[queue_items] WHERE [id] = N'9e0e1700-0000-4000-8000-100000000001')
    INSERT INTO [crm].[queue_items] (
        [id], [title], [item_type], [object_id], [status], [priority], [entered_at], [due_at], [queue_id], [account_id], [activity_id], [knowledge_article_id]
    )
    VALUES (
        N'9e0e1700-0000-4000-8000-100000000001',
        N'Prepare Acme onboarding workspace',
        N'Account',
        N'a0c00000-0000-4000-8000-100000000001',
        N'Open',
        1,
        N'2026-01-10T09:00:00Z',
        N'2026-01-12T17:00:00Z',
        N'9e0e0000-0000-4000-8000-100000000001',
        N'a0c00000-0000-4000-8000-100000000001',
        NULL,
        NULL

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[queue_items] WHERE [id] = N'9e0e1700-0000-4000-8000-100000000002')
    INSERT INTO [crm].[queue_items] (
        [id], [title], [item_type], [object_id], [status], [priority], [entered_at], [due_at], [queue_id], [account_id], [activity_id], [knowledge_article_id]
    )
    VALUES (
        N'9e0e1700-0000-4000-8000-100000000002',
        N'Review onboarding checklist',
        N'KnowledgeArticle',
        N'a471c1e0-0000-4000-8000-100000000001',
        N'InReview',
        2,
        N'2026-01-11T15:20:00Z',
        N'2026-01-15T17:00:00Z',
        N'9e0e0000-0000-4000-8000-100000000002',
        NULL,
        NULL,
        N'a471c1e0-0000-4000-8000-100000000001'

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[queue_items] WHERE [id] = N'9e0e1700-0000-4000-8000-100000000003')
    INSERT INTO [crm].[queue_items] (
        [id], [title], [item_type], [object_id], [status], [priority], [entered_at], [due_at], [queue_id], [account_id], [activity_id], [knowledge_article_id]
    )
    VALUES (
        N'9e0e1700-0000-4000-8000-100000000003',
        N'Follow up on Northstar renewal',
        N'Activity',
        N'ac710007-0000-4000-8000-100000000003',
        N'Open',
        2,
        N'2026-01-12T18:00:00Z',
        N'2026-01-13T22:00:00Z',
        N'9e0e0000-0000-4000-8000-100000000001',
        N'a0c00000-0000-4000-8000-100000000002',
        N'ac710007-0000-4000-8000-100000000003',
        NULL

    );

IF NOT EXISTS (SELECT 1 FROM [crm].[queue_items] WHERE [id] = N'9e0e1700-0000-4000-8000-100000000004')
    INSERT INTO [crm].[queue_items] (
        [id], [title], [item_type], [object_id], [status], [priority], [entered_at], [due_at], [queue_id], [account_id], [activity_id], [knowledge_article_id]
    )
    VALUES (
        N'9e0e1700-0000-4000-8000-100000000004',
        N'Publish data import troubleshooting',
        N'KnowledgeArticle',
        N'a471c1e0-0000-4000-8000-100000000003',
        N'Done',
        3,
        N'2026-02-15T10:30:00Z',
        N'2026-02-18T17:00:00Z',
        N'9e0e0000-0000-4000-8000-100000000002',
        NULL,
        NULL,
        N'a471c1e0-0000-4000-8000-100000000003'

    );
