--
--    Generated by app_gen.
--    by app_gen/_templates/database/postgresql/seed_sql/_mod.j2
--    Seed data for crm schema (PostgreSQL dialect)
--

DO $$
BEGIN




-- ----------------------------------------------------------------------------
-- ActivityType
-- ----------------------------------------------------------------------------


INSERT INTO crm.activity_types (
  id, name, sort_order
)
VALUES (
  'ac71ec00-0000-4000-8000-100000000001',

  'Email',

  10


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.activity_types (
  id, name, sort_order
)
VALUES (
  'ac71ec00-0000-4000-8000-100000000002',

  'Call',

  20


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.activity_types (
  id, name, sort_order
)
VALUES (
  'ac71ec00-0000-4000-8000-100000000003',

  'Meeting',

  30


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.activity_types (
  id, name, sort_order
)
VALUES (
  'ac71ec00-0000-4000-8000-100000000004',

  'Task',

  40


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.activity_types (
  id, name, sort_order
)
VALUES (
  'ac71ec00-0000-4000-8000-100000000005',

  'Note',

  50


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- Industry
-- ----------------------------------------------------------------------------


INSERT INTO crm.industries (
  id, name, sort_order
)
VALUES (
  '10100070-0000-4000-8000-100000000001',

  'Healthcare',

  10


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.industries (
  id, name, sort_order
)
VALUES (
  '10100070-0000-4000-8000-100000000002',

  'Technology',

  20


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.industries (
  id, name, sort_order
)
VALUES (
  '10100070-0000-4000-8000-100000000003',

  'Financial Services',

  30


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.industries (
  id, name, sort_order
)
VALUES (
  '10100070-0000-4000-8000-100000000004',

  'Manufacturing',

  40


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.industries (
  id, name, sort_order
)
VALUES (
  '10100070-0000-4000-8000-100000000005',

  'Retail',

  50


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- LeadSource
-- ----------------------------------------------------------------------------


INSERT INTO crm.lead_sources (
  id, name, sort_order
)
VALUES (
  '1eadcc01-0000-4000-8000-100000000001',

  'Web',

  10


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.lead_sources (
  id, name, sort_order
)
VALUES (
  '1eadcc01-0000-4000-8000-100000000002',

  'Phone Inquiry',

  20


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.lead_sources (
  id, name, sort_order
)
VALUES (
  '1eadcc01-0000-4000-8000-100000000003',

  'Partner Referral',

  30


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.lead_sources (
  id, name, sort_order
)
VALUES (
  '1eadcc01-0000-4000-8000-100000000004',

  'Trade Show',

  40


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.lead_sources (
  id, name, sort_order
)
VALUES (
  '1eadcc01-0000-4000-8000-100000000005',

  'Employee Referral',

  50


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- LeadStatus
-- ----------------------------------------------------------------------------


INSERT INTO crm.lead_statuses (
  id, name, is_converted, sort_order
)
VALUES (
  '1eadcc00-0000-4000-8000-100000000001',

  'New',

  false,

  10


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.lead_statuses (
  id, name, is_converted, sort_order
)
VALUES (
  '1eadcc00-0000-4000-8000-100000000002',

  'Contacted',

  false,

  20


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.lead_statuses (
  id, name, is_converted, sort_order
)
VALUES (
  '1eadcc00-0000-4000-8000-100000000003',

  'Qualified',

  false,

  30


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.lead_statuses (
  id, name, is_converted, sort_order
)
VALUES (
  '1eadcc00-0000-4000-8000-100000000004',

  'Unqualified',

  false,

  40


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.lead_statuses (
  id, name, is_converted, sort_order
)
VALUES (
  '1eadcc00-0000-4000-8000-100000000005',

  'Converted',

  true,

  50


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- OpportunityStage
-- ----------------------------------------------------------------------------


INSERT INTO crm.opportunity_stages (
  id, name, probability, is_closed, is_won, sort_order
)
VALUES (
  '0998a900-0000-4000-8000-100000000001',

  'Prospecting',

  0.1,

  false,

  false,

  10


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunity_stages (
  id, name, probability, is_closed, is_won, sort_order
)
VALUES (
  '0998a900-0000-4000-8000-100000000002',

  'Qualification',

  0.2,

  false,

  false,

  20


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunity_stages (
  id, name, probability, is_closed, is_won, sort_order
)
VALUES (
  '0998a900-0000-4000-8000-100000000003',

  'Proposal',

  0.5,

  false,

  false,

  30


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunity_stages (
  id, name, probability, is_closed, is_won, sort_order
)
VALUES (
  '0998a900-0000-4000-8000-100000000004',

  'Closed Won',

  1.0,

  true,

  true,

  40


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunity_stages (
  id, name, probability, is_closed, is_won, sort_order
)
VALUES (
  '0998a900-0000-4000-8000-100000000005',

  'Closed Lost',

  0.0,

  true,

  false,

  50


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- Pricebook
-- ----------------------------------------------------------------------------


INSERT INTO crm.pricebooks (
  id, name, description, is_active, is_standard
)
VALUES (
  '97000b00-0000-4000-8000-100000000001',

  'Standard Price Book',

  'Default price book for all products',

  true,

  true


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.pricebooks (
  id, name, description, is_active, is_standard
)
VALUES (
  '97000b00-0000-4000-8000-100000000002',

  'Partner Price Book',

  'Discounted pricing for channel partners',

  true,

  false


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- QuoteStatus
-- ----------------------------------------------------------------------------


INSERT INTO crm.quote_statuses (
  id, name, sort_order
)
VALUES (
  '9407ec00-0000-4000-8000-100000000001',

  'Draft',

  10


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_statuses (
  id, name, sort_order
)
VALUES (
  '9407ec00-0000-4000-8000-100000000002',

  'Needs Review',

  20


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_statuses (
  id, name, sort_order
)
VALUES (
  '9407ec00-0000-4000-8000-100000000003',

  'Delivered',

  30


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_statuses (
  id, name, sort_order
)
VALUES (
  '9407ec00-0000-4000-8000-100000000004',

  'Accepted',

  40


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_statuses (
  id, name, sort_order
)
VALUES (
  '9407ec00-0000-4000-8000-100000000005',

  'Rejected',

  50


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- Account
-- ----------------------------------------------------------------------------


INSERT INTO crm.accounts (
  id, name, website, phone, email, tags, billing_street, billing_city, billing_state, billing_postal_code, billing_country, annual_revenue, number_of_employees, description, industry_id
)
VALUES (
  'a0c00000-0000-4000-8000-100000000001',

  'Acme Dental Group',

  'https://acmedental.com',

  '555-0100',

  'info@acmedental.com',

  ARRAY['baseline', 'healthcare', 'south', 'mid-market'],

  '101 Congress Ave',

  'Austin',

  'TX',

  '78701',

  'US',

  12000000,

  85,

  'Regional dental services group expanding patient engagement and back-office automation.',

  '10100070-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.accounts (
  id, name, website, phone, email, tags, billing_street, billing_city, billing_state, billing_postal_code, billing_country, annual_revenue, number_of_employees, description, industry_id
)
VALUES (
  'a0c00000-0000-4000-8000-100000000002',

  'TechBridge Solutions',

  'https://techbridge.io',

  '555-0200',

  'hello@techbridge.io',

  ARRAY['baseline', 'technology', 'west', 'mid-market'],

  '500 Market St',

  'San Francisco',

  'CA',

  '94105',

  'US',

  45000000,

  220,

  'Cloud integration consultancy standardizing customer success operations.',

  '10100070-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.accounts (
  id, name, website, phone, email, tags, billing_street, billing_city, billing_state, billing_postal_code, billing_country, annual_revenue, number_of_employees, description, industry_id
)
VALUES (
  'a0c00000-0000-4000-8000-100000000003',

  'CapStone Financial',

  'https://capstone-fin.com',

  '555-0300',

  'contact@capstone-fin.com',

  ARRAY['baseline', 'financial-services', 'northeast', 'enterprise'],

  '75 Broad St',

  'New York',

  'NY',

  '10004',

  'US',

  90000000,

  450,

  'Wealth management firm evaluating analytics and compliance reporting capabilities.',

  '10100070-0000-4000-8000-100000000003'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.accounts (
  id, name, website, phone, email, tags, billing_street, billing_city, billing_state, billing_postal_code, billing_country, annual_revenue, number_of_employees, description, industry_id
)
VALUES (
  'a0c00000-0000-4000-8000-100000000004',

  'MediSystems Inc',

  'https://medisystems.com',

  '555-0400',

  'info@medisystems.com',

  ARRAY['baseline', 'healthcare', 'midwest', 'mid-market'],

  '233 W Wacker Dr',

  'Chicago',

  'IL',

  '60606',

  'US',

  22000000,

  130,

  'Healthcare technology provider modernizing account management and field operations.',

  '10100070-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.accounts (
  id, name, website, phone, email, tags, billing_street, billing_city, billing_state, billing_postal_code, billing_country, annual_revenue, number_of_employees, description, industry_id
)
VALUES (
  'a0c00000-0000-4000-8000-100000000005',

  'RetailPlus Corp',

  'https://retailplus.com',

  '555-0500',

  'sales@retailplus.com',

  ARRAY['baseline', 'retail', 'south', 'mid-market'],

  '1720 Commerce St',

  'Dallas',

  'TX',

  '75201',

  'US',

  18000000,

  110,

  'Regional retailer piloting service workflows across store operations and procurement.',

  '10100070-0000-4000-8000-100000000005'


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- Product
-- ----------------------------------------------------------------------------


INSERT INTO crm.products (
  id, name, product_code, description, list_price, is_active, family, pricebook_id
)
VALUES (
  '9700d000-0000-4000-8000-100000000001',

  'Enterprise Suite',

  'ENT-001',

  'Full-featured enterprise platform license',

  75000.0,

  true,

  'Software',

  '97000b00-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.products (
  id, name, product_code, description, list_price, is_active, family, pricebook_id
)
VALUES (
  '9700d000-0000-4000-8000-100000000002',

  'Professional Edition',

  'PRO-001',

  'Mid-market platform license',

  25000.0,

  true,

  'Software',

  '97000b00-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.products (
  id, name, product_code, description, list_price, is_active, family, pricebook_id
)
VALUES (
  '9700d000-0000-4000-8000-100000000003',

  'Implementation Services',

  'SVC-001',

  'Professional services for deployment',

  15000.0,

  true,

  'Services',

  '97000b00-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.products (
  id, name, product_code, description, list_price, is_active, family, pricebook_id
)
VALUES (
  '9700d000-0000-4000-8000-100000000004',

  'Annual Support',

  'SUP-001',

  'Yearly support and maintenance contract',

  7500.0,

  true,

  'Support',

  '97000b00-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.products (
  id, name, product_code, description, list_price, is_active, family, pricebook_id
)
VALUES (
  '9700d000-0000-4000-8000-100000000005',

  'Training Package',

  'TRN-001',

  'User and admin training bundle',

  5000.0,

  true,

  'Services',

  '97000b00-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.products (
  id, name, product_code, description, list_price, is_active, family, pricebook_id
)
VALUES (
  '9700d000-0000-4000-8000-100000000006',

  'Data Migration Accelerator',

  'SVC-002',

  'Fixed-scope migration package for legacy CRM and ERP data',

  18000.0,

  true,

  'Services',

  '97000b00-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.products (
  id, name, product_code, description, list_price, is_active, family, pricebook_id
)
VALUES (
  '9700d000-0000-4000-8000-100000000007',

  'Customer Portal Add-On',

  'ADD-001',

  'Customer self-service portal and branded access layer',

  32000.0,

  true,

  'Software',

  '97000b00-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.products (
  id, name, product_code, description, list_price, is_active, family, pricebook_id
)
VALUES (
  '9700d000-0000-4000-8000-100000000008',

  'Compliance Reporting Pack',

  'REP-001',

  'Regulated reporting dashboards and export templates',

  12000.0,

  true,

  'Reporting',

  '97000b00-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.products (
  id, name, product_code, description, list_price, is_active, family, pricebook_id
)
VALUES (
  '9700d000-0000-4000-8000-100000000009',

  'Partner Enablement Kit',

  'PRT-001',

  'Partner onboarding workshops, playbooks, and co-selling assets',

  8500.0,

  true,

  'Services',

  '97000b00-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.products (
  id, name, product_code, description, list_price, is_active, family, pricebook_id
)
VALUES (
  '9700d000-0000-4000-8000-100000000010',

  'Sandbox Environment',

  'SBOX-001',

  'Isolated non-production environment for testing and training',

  6000.0,

  true,

  'Software',

  '97000b00-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.products (
  id, name, product_code, description, list_price, is_active, family, pricebook_id
)
VALUES (
  '9700d000-0000-4000-8000-100000000011',

  'Legacy Connector Pack',

  'INT-001',

  'Connector bundle for file drops, SFTP, and legacy API synchronization',

  14000.0,

  true,

  'Integrations',

  '97000b00-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.products (
  id, name, product_code, description, list_price, is_active, family, pricebook_id
)
VALUES (
  '9700d000-0000-4000-8000-100000000012',

  'Retired On-Prem Connector',

  'INT-LEGACY',

  'Inactive connector retained to exercise inactive product filtering',

  9500.0,

  false,

  'Integrations',

  '97000b00-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- Contact
-- ----------------------------------------------------------------------------


INSERT INTO crm.contacts (
  id, first_name, last_name, email, phone, mobile, title, department, mailing_street, mailing_city, mailing_state, mailing_postal_code, mailing_country, account_id
)
VALUES (
  'c0c00000-0000-4000-8000-100000000001',

  'Sarah',

  'Mitchell',

  's.mitchell@acmedental.com',

  '555-0101',

  '555-0109',

  'VP Operations',

  'Operations',

  '101 Congress Ave',

  'Austin',

  'TX',

  '78701',

  'US',

  'a0c00000-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.contacts (
  id, first_name, last_name, email, phone, mobile, title, department, mailing_street, mailing_city, mailing_state, mailing_postal_code, mailing_country, account_id
)
VALUES (
  'c0c00000-0000-4000-8000-100000000002',

  'James',

  'Okafor',

  'j.okafor@techbridge.io',

  '555-0201',

  '555-0209',

  'CTO',

  'Engineering',

  '500 Market St',

  'San Francisco',

  'CA',

  '94105',

  'US',

  'a0c00000-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.contacts (
  id, first_name, last_name, email, phone, mobile, title, department, mailing_street, mailing_city, mailing_state, mailing_postal_code, mailing_country, account_id
)
VALUES (
  'c0c00000-0000-4000-8000-100000000003',

  'Lisa',

  'Chen',

  'l.chen@capstone-fin.com',

  '555-0301',

  '555-0309',

  'CFO',

  'Finance',

  '75 Broad St',

  'New York',

  'NY',

  '10004',

  'US',

  'a0c00000-0000-4000-8000-100000000003'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.contacts (
  id, first_name, last_name, email, phone, mobile, title, department, mailing_street, mailing_city, mailing_state, mailing_postal_code, mailing_country, account_id
)
VALUES (
  'c0c00000-0000-4000-8000-100000000004',

  'David',

  'Torres',

  'd.torres@medisystems.com',

  '555-0401',

  '555-0409',

  'Director of IT',

  'Information Technology',

  '233 W Wacker Dr',

  'Chicago',

  'IL',

  '60606',

  'US',

  'a0c00000-0000-4000-8000-100000000004'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.contacts (
  id, first_name, last_name, email, phone, mobile, title, department, mailing_street, mailing_city, mailing_state, mailing_postal_code, mailing_country, account_id
)
VALUES (
  'c0c00000-0000-4000-8000-100000000005',

  'Priya',

  'Sharma',

  'p.sharma@retailplus.com',

  '555-0501',

  '555-0509',

  'VP Purchasing',

  'Procurement',

  '1720 Commerce St',

  'Dallas',

  'TX',

  '75201',

  'US',

  'a0c00000-0000-4000-8000-100000000005'


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- Lead
-- ----------------------------------------------------------------------------


INSERT INTO crm.leads (
  id, first_name, last_name, email, phone, company, title, website, description, annual_revenue, number_of_employees, is_converted, converted_account_id, status_id, source_id, industry_id
)
VALUES (
  '1eadc000-0000-4000-8000-100000000001',

  'Michael',

  'Nguyen',

  'm.nguyen@sunrise-dental.com',

  '555-1001',

  'Sunrise Dental',

  'Office Manager',

  'https://sunrise-dental.example.com',

  'New inbound lead requesting a patient communication workflow review.',

  2500000,

  28,

  false,

  NULL,

  '1eadcc00-0000-4000-8000-100000000001',

  '1eadcc01-0000-4000-8000-100000000001',

  '10100070-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.leads (
  id, first_name, last_name, email, phone, company, title, website, description, annual_revenue, number_of_employees, is_converted, converted_account_id, status_id, source_id, industry_id
)
VALUES (
  '1eadc000-0000-4000-8000-100000000002',

  'Amanda',

  'Brooks',

  'a.brooks@vistaclinic.com',

  '555-1002',

  'Vista Clinic Group',

  'Practice Administrator',

  'https://vistaclinic.example.com',

  'Multi-location practice comparing pricing and implementation services.',

  8700000,

  74,

  false,

  NULL,

  '1eadcc00-0000-4000-8000-100000000002',

  '1eadcc01-0000-4000-8000-100000000003',

  '10100070-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.leads (
  id, first_name, last_name, email, phone, company, title, website, description, annual_revenue, number_of_employees, is_converted, converted_account_id, status_id, source_id, industry_id
)
VALUES (
  '1eadc000-0000-4000-8000-100000000003',

  'Robert',

  'Kim',

  'r.kim@nextech.co',

  '555-1003',

  'NexTech Co',

  'IT Director',

  'https://nextech.example.com',

  'Qualified technology prospect interested in sandbox environments and connectors.',

  19000000,

  120,

  false,

  NULL,

  '1eadcc00-0000-4000-8000-100000000003',

  '1eadcc01-0000-4000-8000-100000000004',

  '10100070-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.leads (
  id, first_name, last_name, email, phone, company, title, website, description, annual_revenue, number_of_employees, is_converted, converted_account_id, status_id, source_id, industry_id
)
VALUES (
  '1eadc000-0000-4000-8000-100000000004',

  'Elena',

  'Vasquez',

  'e.vasquez@meridian-health.org',

  '555-1004',

  'Meridian Health',

  'COO',

  'https://meridian-health.example.org',

  'Early healthcare inquiry with budget owner identified.',

  32000000,

  210,

  false,

  NULL,

  '1eadcc00-0000-4000-8000-100000000001',

  '1eadcc01-0000-4000-8000-100000000002',

  '10100070-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.leads (
  id, first_name, last_name, email, phone, company, title, website, description, annual_revenue, number_of_employees, is_converted, converted_account_id, status_id, source_id, industry_id
)
VALUES (
  '1eadc000-0000-4000-8000-100000000005',

  'Thomas',

  'Adeyemi',

  't.adeyemi@freshmarket.com',

  '555-1005',

  'Fresh Market Chain',

  'VP Technology',

  'https://freshmarket.example.com',

  'Retail lead referred by an internal customer success manager.',

  41000000,

  330,

  false,

  NULL,

  '1eadcc00-0000-4000-8000-100000000002',

  '1eadcc01-0000-4000-8000-100000000005',

  '10100070-0000-4000-8000-100000000005'


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- Opportunity
-- ----------------------------------------------------------------------------


INSERT INTO crm.opportunities (
  id, name, amount, close_date, description, next_step, lead_source, account_id, stage_id
)
VALUES (
  '099c0000-0000-4000-8000-100000000001',

  'Acme Dental - Enterprise Suite',

  97500,

  '2026-06-30',

  'Enterprise platform evaluation for operations, patient engagement, and staff enablement.',

  'Confirm legal review owner and implementation window.',

  'Partner Referral',

  'a0c00000-0000-4000-8000-100000000001',

  '0998a900-0000-4000-8000-100000000003'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunities (
  id, name, amount, close_date, description, next_step, lead_source, account_id, stage_id
)
VALUES (
  '099c0000-0000-4000-8000-100000000002',

  'TechBridge - Platform Expansion',

  145000,

  '2026-07-31',

  'Expansion opportunity covering additional platform seats and service packaging.',

  'Send security package and revised partner services estimate.',

  'Web',

  'a0c00000-0000-4000-8000-100000000002',

  '0998a900-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunities (
  id, name, amount, close_date, description, next_step, lead_source, account_id, stage_id
)
VALUES (
  '099c0000-0000-4000-8000-100000000003',

  'CapStone - Analytics Module',

  32500,

  '2026-05-31',

  'Analytics module and compliance reporting add-on for financial advisors.',

  'Schedule executive readout with finance and compliance stakeholders.',

  'Trade Show',

  'a0c00000-0000-4000-8000-100000000003',

  '0998a900-0000-4000-8000-100000000004'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunities (
  id, name, amount, close_date, description, next_step, lead_source, account_id, stage_id
)
VALUES (
  '099c0000-0000-4000-8000-100000000004',

  'MediSystems - Pro Edition',

  47500,

  '2026-08-31',

  'Professional edition rollout for care coordination and IT service workflows.',

  'Complete technical discovery with integrations team.',

  'Phone Inquiry',

  'a0c00000-0000-4000-8000-100000000004',

  '0998a900-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunities (
  id, name, amount, close_date, description, next_step, lead_source, account_id, stage_id
)
VALUES (
  '099c0000-0000-4000-8000-100000000005',

  'RetailPlus - Services Bundle',

  27500,

  '2026-09-30',

  'Services and enablement bundle for store support and procurement coordination.',

  'Align procurement scope and delivery schedule.',

  'Employee Referral',

  'a0c00000-0000-4000-8000-100000000005',

  '0998a900-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- Activity
-- ----------------------------------------------------------------------------


INSERT INTO crm.activities (
  id, subject, description, activity_date, due_date, is_closed, priority, status, type_id, account_id, contact_id, opportunity_id, lead_id
)
VALUES (
  'ac710007-0000-4000-8000-100000000001',

  'Discovery Call - Acme Dental',

  'Initial discovery call to understand requirements',

  '2026-05-01',

  '2026-05-01',

  true,

  'High',

  'Completed',

  'ac71ec00-0000-4000-8000-100000000002',

  'a0c00000-0000-4000-8000-100000000001',

  'c0c00000-0000-4000-8000-100000000001',

  '099c0000-0000-4000-8000-100000000001',

  NULL


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.activities (
  id, subject, description, activity_date, due_date, is_closed, priority, status, type_id, account_id, contact_id, opportunity_id, lead_id
)
VALUES (
  'ac710007-0000-4000-8000-100000000002',

  'Demo - TechBridge Platform',

  'Full product demonstration for expansion proposal',

  '2026-05-10',

  '2026-05-10',

  true,

  'High',

  'Completed',

  'ac71ec00-0000-4000-8000-100000000003',

  'a0c00000-0000-4000-8000-100000000002',

  'c0c00000-0000-4000-8000-100000000002',

  '099c0000-0000-4000-8000-100000000002',

  NULL


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.activities (
  id, subject, description, activity_date, due_date, is_closed, priority, status, type_id, account_id, contact_id, opportunity_id, lead_id
)
VALUES (
  'ac710007-0000-4000-8000-100000000003',

  'Follow-up Email - CapStone Analytics',

  'Sent ROI analysis and case studies',

  '2026-05-12',

  '2026-05-12',

  true,

  'Normal',

  'Completed',

  'ac71ec00-0000-4000-8000-100000000001',

  'a0c00000-0000-4000-8000-100000000003',

  'c0c00000-0000-4000-8000-100000000003',

  '099c0000-0000-4000-8000-100000000003',

  NULL


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.activities (
  id, subject, description, activity_date, due_date, is_closed, priority, status, type_id, account_id, contact_id, opportunity_id, lead_id
)
VALUES (
  'ac710007-0000-4000-8000-100000000004',

  'Intro Call - MediSystems',

  'First contact, qualify needs and budget',

  '2026-05-19',

  '2026-05-19',

  false,

  'Normal',

  'Planned',

  'ac71ec00-0000-4000-8000-100000000002',

  'a0c00000-0000-4000-8000-100000000004',

  'c0c00000-0000-4000-8000-100000000004',

  '099c0000-0000-4000-8000-100000000004',

  NULL


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.activities (
  id, subject, description, activity_date, due_date, is_closed, priority, status, type_id, account_id, contact_id, opportunity_id, lead_id
)
VALUES (
  'ac710007-0000-4000-8000-100000000005',

  'Proposal Review Meeting - RetailPlus',

  'Walk through the services bundle proposal',

  '2026-05-28',

  '2026-05-28',

  false,

  'Normal',

  'Planned',

  'ac71ec00-0000-4000-8000-100000000003',

  'a0c00000-0000-4000-8000-100000000005',

  'c0c00000-0000-4000-8000-100000000005',

  '099c0000-0000-4000-8000-100000000005',

  NULL


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- OpportunityContact
-- ----------------------------------------------------------------------------


INSERT INTO crm.opportunity_contacts (
  id, opportunity_id, contact_id
)
VALUES (
  '0c0c0000-0000-4000-8000-100000000001',

  '099c0000-0000-4000-8000-100000000001',

  'c0c00000-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunity_contacts (
  id, opportunity_id, contact_id
)
VALUES (
  '0c0c0000-0000-4000-8000-100000000002',

  '099c0000-0000-4000-8000-100000000002',

  'c0c00000-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunity_contacts (
  id, opportunity_id, contact_id
)
VALUES (
  '0c0c0000-0000-4000-8000-100000000003',

  '099c0000-0000-4000-8000-100000000003',

  'c0c00000-0000-4000-8000-100000000003'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunity_contacts (
  id, opportunity_id, contact_id
)
VALUES (
  '0c0c0000-0000-4000-8000-100000000004',

  '099c0000-0000-4000-8000-100000000004',

  'c0c00000-0000-4000-8000-100000000004'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.opportunity_contacts (
  id, opportunity_id, contact_id
)
VALUES (
  '0c0c0000-0000-4000-8000-100000000005',

  '099c0000-0000-4000-8000-100000000005',

  'c0c00000-0000-4000-8000-100000000005'


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- Quote
-- ----------------------------------------------------------------------------


INSERT INTO crm.quotes (
  id, name, quote_number, expiration_date, description, subtotal, discount, tax, total_price, opportunity_id, account_id, status_id
)
VALUES (
  '9407e000-0000-4000-8000-100000000001',

  'Q-2026-001 Acme Enterprise',

  'Q-2026-001',

  '2026-07-31',

  'Enterprise suite package with implementation and annual support.',

  97500,

  0,

  0,

  97500,

  '099c0000-0000-4000-8000-100000000001',

  'a0c00000-0000-4000-8000-100000000001',

  '9407ec00-0000-4000-8000-100000000003'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quotes (
  id, name, quote_number, expiration_date, description, subtotal, discount, tax, total_price, opportunity_id, account_id, status_id
)
VALUES (
  '9407e000-0000-4000-8000-100000000002',

  'Q-2026-002 TechBridge Platform',

  'Q-2026-002',

  '2026-08-31',

  'Multi-seat professional edition expansion and implementation package.',

  145000,

  0,

  0,

  145000,

  '099c0000-0000-4000-8000-100000000002',

  'a0c00000-0000-4000-8000-100000000002',

  '9407ec00-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quotes (
  id, name, quote_number, expiration_date, description, subtotal, discount, tax, total_price, opportunity_id, account_id, status_id
)
VALUES (
  '9407e000-0000-4000-8000-100000000003',

  'Q-2026-003 CapStone Analytics',

  'Q-2026-003',

  '2026-06-15',

  'Analytics module acceptance package with added training.',

  32500,

  0,

  0,

  32500,

  '099c0000-0000-4000-8000-100000000003',

  'a0c00000-0000-4000-8000-100000000003',

  '9407ec00-0000-4000-8000-100000000004'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quotes (
  id, name, quote_number, expiration_date, description, subtotal, discount, tax, total_price, opportunity_id, account_id, status_id
)
VALUES (
  '9407e000-0000-4000-8000-100000000004',

  'Q-2026-004 MediSystems Pro Edition',

  'Q-2026-004',

  '2026-09-30',

  'Professional edition, implementation, and annual support proposal.',

  47500,

  2500,

  0,

  45000,

  '099c0000-0000-4000-8000-100000000004',

  'a0c00000-0000-4000-8000-100000000004',

  '9407ec00-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quotes (
  id, name, quote_number, expiration_date, description, subtotal, discount, tax, total_price, opportunity_id, account_id, status_id
)
VALUES (
  '9407e000-0000-4000-8000-100000000005',

  'Q-2026-005 RetailPlus Services',

  'Q-2026-005',

  '2026-10-31',

  'Services bundle for procurement and store operations enablement.',

  27500,

  0,

  0,

  27500,

  '099c0000-0000-4000-8000-100000000005',

  'a0c00000-0000-4000-8000-100000000005',

  '9407ec00-0000-4000-8000-100000000003'


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- QuoteLineItem
-- ----------------------------------------------------------------------------


INSERT INTO crm.quote_line_items (
  id, quantity, unit_price, discount, total_price, description, sort_order, quote_id, product_id
)
VALUES (
  '9407e110-0000-4000-8000-100000000001',

  1,

  75000,

  0,

  75000,

  'Enterprise platform license.',

  1,

  '9407e000-0000-4000-8000-100000000001',

  '9700d000-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_line_items (
  id, quantity, unit_price, discount, total_price, description, sort_order, quote_id, product_id
)
VALUES (
  '9407e110-0000-4000-8000-100000000002',

  1,

  15000,

  0,

  15000,

  'Standard implementation services.',

  2,

  '9407e000-0000-4000-8000-100000000001',

  '9700d000-0000-4000-8000-100000000003'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_line_items (
  id, quantity, unit_price, discount, total_price, description, sort_order, quote_id, product_id
)
VALUES (
  '9407e110-0000-4000-8000-100000000003',

  1,

  7500,

  0,

  7500,

  'Annual support package.',

  3,

  '9407e000-0000-4000-8000-100000000001',

  '9700d000-0000-4000-8000-100000000004'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_line_items (
  id, quantity, unit_price, discount, total_price, description, sort_order, quote_id, product_id
)
VALUES (
  '9407e110-0000-4000-8000-100000000004',

  5,

  25000,

  0,

  125000,

  'Five professional edition licenses.',

  1,

  '9407e000-0000-4000-8000-100000000002',

  '9700d000-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_line_items (
  id, quantity, unit_price, discount, total_price, description, sort_order, quote_id, product_id
)
VALUES (
  '9407e110-0000-4000-8000-100000000005',

  1,

  20000,

  0,

  20000,

  'Expanded implementation package.',

  2,

  '9407e000-0000-4000-8000-100000000002',

  '9700d000-0000-4000-8000-100000000003'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_line_items (
  id, quantity, unit_price, discount, total_price, description, sort_order, quote_id, product_id
)
VALUES (
  '9407e110-0000-4000-8000-100000000006',

  1,

  25000,

  0,

  25000,

  'Professional edition analytics module.',

  1,

  '9407e000-0000-4000-8000-100000000003',

  '9700d000-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_line_items (
  id, quantity, unit_price, discount, total_price, description, sort_order, quote_id, product_id
)
VALUES (
  '9407e110-0000-4000-8000-100000000007',

  1,

  7500,

  0,

  7500,

  'Analytics support package.',

  2,

  '9407e000-0000-4000-8000-100000000003',

  '9700d000-0000-4000-8000-100000000004'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_line_items (
  id, quantity, unit_price, discount, total_price, description, sort_order, quote_id, product_id
)
VALUES (
  '9407e110-0000-4000-8000-100000000008',

  1,

  25000,

  0,

  25000,

  'Professional edition core license.',

  1,

  '9407e000-0000-4000-8000-100000000004',

  '9700d000-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_line_items (
  id, quantity, unit_price, discount, total_price, description, sort_order, quote_id, product_id
)
VALUES (
  '9407e110-0000-4000-8000-100000000009',

  1,

  15000,

  0,

  15000,

  'Implementation services for care workflows.',

  2,

  '9407e000-0000-4000-8000-100000000004',

  '9700d000-0000-4000-8000-100000000003'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_line_items (
  id, quantity, unit_price, discount, total_price, description, sort_order, quote_id, product_id
)
VALUES (
  '9407e110-0000-4000-8000-100000000010',

  1,

  7500,

  2500,

  5000,

  'Discounted annual support.',

  3,

  '9407e000-0000-4000-8000-100000000004',

  '9700d000-0000-4000-8000-100000000004'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_line_items (
  id, quantity, unit_price, discount, total_price, description, sort_order, quote_id, product_id
)
VALUES (
  '9407e110-0000-4000-8000-100000000011',

  1,

  15000,

  0,

  15000,

  'Procurement implementation services.',

  1,

  '9407e000-0000-4000-8000-100000000005',

  '9700d000-0000-4000-8000-100000000003'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_line_items (
  id, quantity, unit_price, discount, total_price, description, sort_order, quote_id, product_id
)
VALUES (
  '9407e110-0000-4000-8000-100000000012',

  1,

  5000,

  0,

  5000,

  'Store operations training package.',

  2,

  '9407e000-0000-4000-8000-100000000005',

  '9700d000-0000-4000-8000-100000000005'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.quote_line_items (
  id, quantity, unit_price, discount, total_price, description, sort_order, quote_id, product_id
)
VALUES (
  '9407e110-0000-4000-8000-100000000013',

  1,

  7500,

  0,

  7500,

  'Support for store rollout.',

  3,

  '9407e000-0000-4000-8000-100000000005',

  '9700d000-0000-4000-8000-100000000004'


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- BusinessUnit
-- ----------------------------------------------------------------------------


INSERT INTO crm.business_units (
  id, name, code, description, region, is_active
)
VALUES (
  'b0510000-0000-4000-8000-100000000001',

  'West Commercial',

  'WEST-COM',

  'Commercial sales and service for western regional accounts',

  'West',

  true


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.business_units (
  id, name, code, description, region, is_active
)
VALUES (
  'b0510000-0000-4000-8000-100000000002',

  'National Service',

  'NAT-SVC',

  'Shared service and knowledge operations',

  'National',

  true


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- Territory
-- ----------------------------------------------------------------------------


INSERT INTO crm.territories (
  id, name, code, region, country, state, is_active, business_unit_id
)
VALUES (
  '7e441000-0000-4000-8000-100000000001',

  'Pacific Northwest',

  'PNW',

  'West',

  'USA',

  'WA',

  true,

  'b0510000-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.territories (
  id, name, code, region, country, state, is_active, business_unit_id
)
VALUES (
  '7e441000-0000-4000-8000-100000000002',

  'California Enterprise',

  'CA-ENT',

  'West',

  'USA',

  'CA',

  true,

  'b0510000-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.territories (
  id, name, code, region, country, state, is_active, business_unit_id
)
VALUES (
  '7e441000-0000-4000-8000-100000000003',

  'Remote Service Desk',

  'RSD',

  'National',

  'USA',

  NULL,

  true,

  'b0510000-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- Queue
-- ----------------------------------------------------------------------------


INSERT INTO crm.queues (
  id, name, queue_type, description, email, is_active, business_unit_id
)
VALUES (
  '9e0e0000-0000-4000-8000-100000000001',

  'Enterprise Onboarding',

  'Sales',

  'High-touch queue for new enterprise opportunities',

  'enterprise-onboarding@example.com',

  true,

  'b0510000-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.queues (
  id, name, queue_type, description, email, is_active, business_unit_id
)
VALUES (
  '9e0e0000-0000-4000-8000-100000000002',

  'Knowledge Review',

  'Service',

  'Review queue for externally visible knowledge articles',

  'kb-review@example.com',

  true,

  'b0510000-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- Address
-- ----------------------------------------------------------------------------


INSERT INTO crm.addresses (
  id, name, address_type, street1, street2, city, state, postal_code, country, latitude, longitude, is_primary, account_id, contact_id
)
VALUES (
  'add00000-0000-4000-8000-100000000001',

  'Acme Dental Billing',

  'Billing',

  '415 Market St',

  'Suite 300',

  'San Francisco',

  'CA',

  '94105',

  'USA',

  37.7899,

  -122.3942,

  true,

  'a0c00000-0000-4000-8000-100000000001',

  NULL


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.addresses (
  id, name, address_type, street1, street2, city, state, postal_code, country, latitude, longitude, is_primary, account_id, contact_id
)
VALUES (
  'add00000-0000-4000-8000-100000000002',

  'Acme Dental Shipping',

  'Shipping',

  '220 Harbor Way',

  NULL,

  'Oakland',

  'CA',

  '94607',

  'USA',

  37.7955,

  -122.2791,

  false,

  'a0c00000-0000-4000-8000-100000000001',

  NULL


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.addresses (
  id, name, address_type, street1, street2, city, state, postal_code, country, latitude, longitude, is_primary, account_id, contact_id
)
VALUES (
  'add00000-0000-4000-8000-100000000003',

  'Maya Johnson Mailing',

  'Mailing',

  '18 Pine Ave',

  'Apt 6C',

  'Portland',

  'OR',

  '97205',

  'USA',

  45.5202,

  -122.6742,

  true,

  NULL,

  'c0c00000-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.addresses (
  id, name, address_type, street1, street2, city, state, postal_code, country, latitude, longitude, is_primary, account_id, contact_id
)
VALUES (
  'add00000-0000-4000-8000-100000000004',

  'Northstar Supply Billing',

  'Billing',

  '780 Lakeview Dr',

  NULL,

  'Minneapolis',

  'MN',

  '55402',

  'USA',

  44.9778,

  -93.265,

  true,

  'a0c00000-0000-4000-8000-100000000002',

  NULL


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.addresses (
  id, name, address_type, street1, street2, city, state, postal_code, country, latitude, longitude, is_primary, account_id, contact_id
)
VALUES (
  'add00000-0000-4000-8000-100000000005',

  'Redwood Logistics Dock',

  'Shipping',

  '1000 Portside Rd',

  'Dock 12',

  'Tacoma',

  'WA',

  '98421',

  'USA',

  47.2529,

  -122.4443,

  false,

  'a0c00000-0000-4000-8000-100000000003',

  NULL


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.addresses (
  id, name, address_type, street1, street2, city, state, postal_code, country, latitude, longitude, is_primary, account_id, contact_id
)
VALUES (
  'add00000-0000-4000-8000-100000000006',

  'Jordan Lee Mailing',

  'Mailing',

  '501 Innovation Pkwy',

  NULL,

  'Austin',

  'TX',

  '78701',

  'USA',

  30.2672,

  -97.7431,

  true,

  NULL,

  'c0c00000-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- ActivityParty
-- ----------------------------------------------------------------------------


INSERT INTO crm.activity_parties (
  id, role, party_type, party_id, display_name, email, is_required, responded_status, activity_id
)
VALUES (
  'ac71fa00-0000-4000-8000-100000000001',

  'Organizer',

  'User',

  'pdsh_admin',

  'Priya Admin',

  'priya.admin@example.com',

  true,

  'Accepted',

  'ac710007-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.activity_parties (
  id, role, party_type, party_id, display_name, email, is_required, responded_status, activity_id
)
VALUES (
  'ac71fa00-0000-4000-8000-100000000002',

  'Required Attendee',

  'Contact',

  'c0c00000-0000-4000-8000-100000000001',

  'Maya Johnson',

  'maya.johnson@example.com',

  true,

  'Accepted',

  'ac710007-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.activity_parties (
  id, role, party_type, party_id, display_name, email, is_required, responded_status, activity_id
)
VALUES (
  'ac71fa00-0000-4000-8000-100000000003',

  'Optional Attendee',

  'Account',

  'a0c00000-0000-4000-8000-100000000001',

  'Acme Dental',

  'info@acme-dental.example.com',

  false,

  'Tentative',

  'ac710007-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.activity_parties (
  id, role, party_type, party_id, display_name, email, is_required, responded_status, activity_id
)
VALUES (
  'ac71fa00-0000-4000-8000-100000000004',

  'Regarding',

  'Opportunity',

  '099c0000-0000-4000-8000-100000000002',

  'Northstar Renewal',

  NULL,

  false,

  'NotRequired',

  'ac710007-0000-4000-8000-100000000003'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.activity_parties (
  id, role, party_type, party_id, display_name, email, is_required, responded_status, activity_id
)
VALUES (
  'ac71fa00-0000-4000-8000-100000000005',

  'Sender',

  'User',

  'pdsh_ops',

  'Morgan Ops',

  'morgan.ops@example.com',

  true,

  'Sent',

  'ac710007-0000-4000-8000-100000000004'


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- KnowledgeArticle
-- ----------------------------------------------------------------------------


INSERT INTO crm.knowledge_articles (
  id, title, slug, summary, body, language, status, publish_date, view_count, is_public, tags
)
VALUES (
  'a471c1e0-0000-4000-8000-100000000001',

  'Enterprise Onboarding Checklist',

  'enterprise-onboarding-checklist',

  'Checklist used by implementation teams before go-live.',

  'Confirm stakeholders, environments, data load, access review, and support handoff.',

  'en-US',

  'Published',

  '2026-01-08',

  312,

  true,

  ARRAY['onboarding', 'enterprise', 'implementation']


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.knowledge_articles (
  id, title, slug, summary, body, language, status, publish_date, view_count, is_public, tags
)
VALUES (
  'a471c1e0-0000-4000-8000-100000000002',

  'Quote Discount Approval Guide',

  'quote-discount-approval-guide',

  'Internal guide for discount thresholds and finance approval.',

  'Discounts above standard guardrails require finance review and attached business justification.',

  'en-US',

  'Draft',

  NULL,

  47,

  false,

  ARRAY['quote', 'finance', 'approvals']


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.knowledge_articles (
  id, title, slug, summary, body, language, status, publish_date, view_count, is_public, tags
)
VALUES (
  'a471c1e0-0000-4000-8000-100000000003',

  'Data Import Troubleshooting',

  'data-import-troubleshooting',

  'Common validation and mapping fixes for imported CRM data.',

  'Review required fields, duplicate keys, invalid references, and provider-specific type mappings.',

  'en-US',

  'Published',

  '2026-02-14',

  1289,

  true,

  ARRAY['data-import', 'validation', 'support']


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- ArticleComment
-- ----------------------------------------------------------------------------


INSERT INTO crm.article_comments (
  id, subject, body, author_name, sentiment, is_internal, created_at, article_id
)
VALUES (
  'a471c0de-0000-4000-8000-100000000001',

  'Add security handoff step',

  'Include evidence that admin access was reviewed before production handoff.',

  'Priya Admin',

  'Positive',

  true,

  '2026-01-09T16:30:00Z',

  'a471c1e0-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.article_comments (
  id, subject, body, author_name, sentiment, is_internal, created_at, article_id
)
VALUES (
  'a471c0de-0000-4000-8000-100000000002',

  'Finance example needed',

  'Add one worked example for a multi-year discount approval.',

  'Iris Finance',

  'Neutral',

  true,

  '2026-01-12T19:10:00Z',

  'a471c1e0-0000-4000-8000-100000000002'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.article_comments (
  id, subject, body, author_name, sentiment, is_internal, created_at, article_id
)
VALUES (
  'a471c0de-0000-4000-8000-100000000003',

  'Helpful import notes',

  'The duplicate key guidance reduced support back-and-forth on the last migration.',

  'Morgan Ops',

  'Positive',

  false,

  '2026-02-17T11:45:00Z',

  'a471c1e0-0000-4000-8000-100000000003'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.article_comments (
  id, subject, body, author_name, sentiment, is_internal, created_at, article_id
)
VALUES (
  'a471c0de-0000-4000-8000-100000000004',

  'Clarify lookup failures',

  'We should distinguish missing foreign keys from invalid UUID syntax.',

  'Rowan Support',

  'Neutral',

  true,

  '2026-02-18T14:05:00Z',

  'a471c1e0-0000-4000-8000-100000000003'


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- QueueItem
-- ----------------------------------------------------------------------------


INSERT INTO crm.queue_items (
  id, title, item_type, object_id, status, priority, entered_at, due_at, queue_id, account_id, activity_id, knowledge_article_id
)
VALUES (
  '9e0e1700-0000-4000-8000-100000000001',

  'Prepare Acme onboarding workspace',

  'Account',

  'a0c00000-0000-4000-8000-100000000001',

  'Open',

  1,

  '2026-01-10T09:00:00Z',

  '2026-01-12T17:00:00Z',

  '9e0e0000-0000-4000-8000-100000000001',

  'a0c00000-0000-4000-8000-100000000001',

  NULL,

  NULL


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.queue_items (
  id, title, item_type, object_id, status, priority, entered_at, due_at, queue_id, account_id, activity_id, knowledge_article_id
)
VALUES (
  '9e0e1700-0000-4000-8000-100000000002',

  'Review onboarding checklist',

  'KnowledgeArticle',

  'a471c1e0-0000-4000-8000-100000000001',

  'InReview',

  2,

  '2026-01-11T15:20:00Z',

  '2026-01-15T17:00:00Z',

  '9e0e0000-0000-4000-8000-100000000002',

  NULL,

  NULL,

  'a471c1e0-0000-4000-8000-100000000001'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.queue_items (
  id, title, item_type, object_id, status, priority, entered_at, due_at, queue_id, account_id, activity_id, knowledge_article_id
)
VALUES (
  '9e0e1700-0000-4000-8000-100000000003',

  'Follow up on Northstar renewal',

  'Activity',

  'ac710007-0000-4000-8000-100000000003',

  'Open',

  2,

  '2026-01-12T18:00:00Z',

  '2026-01-13T22:00:00Z',

  '9e0e0000-0000-4000-8000-100000000001',

  'a0c00000-0000-4000-8000-100000000002',

  'ac710007-0000-4000-8000-100000000003',

  NULL


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO crm.queue_items (
  id, title, item_type, object_id, status, priority, entered_at, due_at, queue_id, account_id, activity_id, knowledge_article_id
)
VALUES (
  '9e0e1700-0000-4000-8000-100000000004',

  'Publish data import troubleshooting',

  'KnowledgeArticle',

  'a471c1e0-0000-4000-8000-100000000003',

  'Done',

  3,

  '2026-02-15T10:30:00Z',

  '2026-02-18T17:00:00Z',

  '9e0e0000-0000-4000-8000-100000000002',

  NULL,

  NULL,

  'a471c1e0-0000-4000-8000-100000000003'


)
ON CONFLICT (id) DO NOTHING;




END $$;
