#![allow(dead_code)]

//
// Backend nexus_ix: Generated Handler Defaults
//    Generated by app_gen.
//    Product-owned handler modules import these defaults and may override any
//    operation by defining a local function with the same name and signature.
//
pub(crate) mod ix_audit_fact {
    #[allow(unused_imports)]
    use std::sync::Arc;

    #[allow(unused_imports)]
    use crate::schemas::nexus_ix::*;

    #[allow(unused_imports)]
    use crate::{
        product_api::{DataAccess, EntityType, HandlerResult, JsonValue, UserAuth},
        schemas::common::AggregateResult,
        schemas::nexus_ix::{InputIxAuditFact, IxAuditFactProjection, IxAuditFactQueryResult},
    };
    pub(crate) async fn find_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        selections: JsonValue,
        id: String,
    ) -> HandlerResult<Option<IxAuditFactProjection>> {
        let res = data_access
            .find_item::<IxAuditFactProjection>(entity_type.clone(), selections, id, user)
            .await?;
        Ok(res)
    }

    pub(crate) async fn find_by_locator_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        selections: JsonValue,
        locator: String,
    ) -> HandlerResult<Option<IxAuditFactProjection>> {
        let res = data_access
            .find_item_by_locator::<IxAuditFactProjection>(
                entity_type.clone(),
                selections,
                locator,
                user,
            )
            .await?;
        Ok(res)
    }
    pub(crate) async fn get_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        selections: JsonValue,
    ) -> HandlerResult<Vec<IxAuditFactProjection>> {
        let res = data_access
            .get_items::<IxAuditFactProjection>(entity_type.clone(), selections, None, user)
            .await?;
        Ok(res)
    }
    pub(crate) async fn query_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        selections: JsonValue,
        filter: Option<JsonValue>,
        sort: Option<JsonValue>,
        skip: i32,
        limit: i32,
        after: Option<String>,
    ) -> HandlerResult<IxAuditFactQueryResult> {
        let res = data_access
            .query_items::<IxAuditFactProjection>(
                entity_type.clone(),
                selections,
                filter,
                sort,
                skip,
                limit,
                after,
                user,
            )
            .await?;
        let query_res = IxAuditFactQueryResult {
            date_time: res.date_time,
            request_duration: res.request_duration,
            skip: res.skip,
            limit: res.limit,
            page_count: res.page_count,
            page_index: res.page_index,
            query_count: res.query_count,
            next_cursor: res.next_cursor,
            previous_cursor: res.previous_cursor,
            items: res.items,
        };
        Ok(query_res)
    }

    pub(crate) async fn aggregate_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        filter: Option<JsonValue>,
        group_by: Option<JsonValue>,
        metrics: Option<JsonValue>,
        having: Option<JsonValue>,
        sort: Option<JsonValue>,
        skip: i32,
        limit: i32,
    ) -> HandlerResult<AggregateResult> {
        let res = data_access
            .aggregate_items(
                entity_type.clone(),
                filter,
                group_by,
                metrics,
                having,
                sort,
                skip,
                limit,
                user,
            )
            .await?;
        Ok(res)
    }
}
pub(crate) mod ix_commit_envelope {
    #[allow(unused_imports)]
    use std::sync::Arc;

    #[allow(unused_imports)]
    use crate::schemas::nexus_ix::*;

    #[allow(unused_imports)]
    use crate::{
        product_api::{DataAccess, EntityType, HandlerResult, JsonValue, UserAuth},
        schemas::common::AggregateResult,
        schemas::nexus_ix::{
            InputIxCommitEnvelope, IxCommitEnvelopeProjection, IxCommitEnvelopeQueryResult,
        },
    };
    pub(crate) async fn find_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        selections: JsonValue,
        id: String,
    ) -> HandlerResult<Option<IxCommitEnvelopeProjection>> {
        let res = data_access
            .find_item::<IxCommitEnvelopeProjection>(entity_type.clone(), selections, id, user)
            .await?;
        Ok(res)
    }

    pub(crate) async fn find_by_locator_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        selections: JsonValue,
        locator: String,
    ) -> HandlerResult<Option<IxCommitEnvelopeProjection>> {
        let res = data_access
            .find_item_by_locator::<IxCommitEnvelopeProjection>(
                entity_type.clone(),
                selections,
                locator,
                user,
            )
            .await?;
        Ok(res)
    }
    pub(crate) async fn get_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        selections: JsonValue,
    ) -> HandlerResult<Vec<IxCommitEnvelopeProjection>> {
        let res = data_access
            .get_items::<IxCommitEnvelopeProjection>(entity_type.clone(), selections, None, user)
            .await?;
        Ok(res)
    }
    pub(crate) async fn query_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        selections: JsonValue,
        filter: Option<JsonValue>,
        sort: Option<JsonValue>,
        skip: i32,
        limit: i32,
        after: Option<String>,
    ) -> HandlerResult<IxCommitEnvelopeQueryResult> {
        let res = data_access
            .query_items::<IxCommitEnvelopeProjection>(
                entity_type.clone(),
                selections,
                filter,
                sort,
                skip,
                limit,
                after,
                user,
            )
            .await?;
        let query_res = IxCommitEnvelopeQueryResult {
            date_time: res.date_time,
            request_duration: res.request_duration,
            skip: res.skip,
            limit: res.limit,
            page_count: res.page_count,
            page_index: res.page_index,
            query_count: res.query_count,
            next_cursor: res.next_cursor,
            previous_cursor: res.previous_cursor,
            items: res.items,
        };
        Ok(query_res)
    }

    pub(crate) async fn aggregate_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        filter: Option<JsonValue>,
        group_by: Option<JsonValue>,
        metrics: Option<JsonValue>,
        having: Option<JsonValue>,
        sort: Option<JsonValue>,
        skip: i32,
        limit: i32,
    ) -> HandlerResult<AggregateResult> {
        let res = data_access
            .aggregate_items(
                entity_type.clone(),
                filter,
                group_by,
                metrics,
                having,
                sort,
                skip,
                limit,
                user,
            )
            .await?;
        Ok(res)
    }
}
pub(crate) mod ix_context {
    #[allow(unused_imports)]
    use std::sync::Arc;

    #[allow(unused_imports)]
    use crate::schemas::nexus_ix::*;

    #[allow(unused_imports)]
    use crate::{
        product_api::{DataAccess, EntityType, HandlerResult, JsonValue, UserAuth},
        schemas::common::AggregateResult,
        schemas::nexus_ix::{InputIxContext, IxContextProjection, IxContextQueryResult},
    };
    pub(crate) async fn find_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        selections: JsonValue,
        id: String,
    ) -> HandlerResult<Option<IxContextProjection>> {
        let res = data_access
            .find_item::<IxContextProjection>(entity_type.clone(), selections, id, user)
            .await?;
        Ok(res)
    }

    pub(crate) async fn find_by_locator_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        selections: JsonValue,
        locator: String,
    ) -> HandlerResult<Option<IxContextProjection>> {
        let res = data_access
            .find_item_by_locator::<IxContextProjection>(
                entity_type.clone(),
                selections,
                locator,
                user,
            )
            .await?;
        Ok(res)
    }
    pub(crate) async fn get_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        selections: JsonValue,
    ) -> HandlerResult<Vec<IxContextProjection>> {
        let res = data_access
            .get_items::<IxContextProjection>(entity_type.clone(), selections, None, user)
            .await?;
        Ok(res)
    }
    pub(crate) async fn query_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        selections: JsonValue,
        filter: Option<JsonValue>,
        sort: Option<JsonValue>,
        skip: i32,
        limit: i32,
        after: Option<String>,
    ) -> HandlerResult<IxContextQueryResult> {
        let res = data_access
            .query_items::<IxContextProjection>(
                entity_type.clone(),
                selections,
                filter,
                sort,
                skip,
                limit,
                after,
                user,
            )
            .await?;
        let query_res = IxContextQueryResult {
            date_time: res.date_time,
            request_duration: res.request_duration,
            skip: res.skip,
            limit: res.limit,
            page_count: res.page_count,
            page_index: res.page_index,
            query_count: res.query_count,
            next_cursor: res.next_cursor,
            previous_cursor: res.previous_cursor,
            items: res.items,
        };
        Ok(query_res)
    }

    pub(crate) async fn aggregate_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        filter: Option<JsonValue>,
        group_by: Option<JsonValue>,
        metrics: Option<JsonValue>,
        having: Option<JsonValue>,
        sort: Option<JsonValue>,
        skip: i32,
        limit: i32,
    ) -> HandlerResult<AggregateResult> {
        let res = data_access
            .aggregate_items(
                entity_type.clone(),
                filter,
                group_by,
                metrics,
                having,
                sort,
                skip,
                limit,
                user,
            )
            .await?;
        Ok(res)
    }
}
pub(crate) mod ix_projection_cursor {
    #[allow(unused_imports)]
    use std::sync::Arc;

    #[allow(unused_imports)]
    use crate::schemas::nexus_ix::*;

    #[allow(unused_imports)]
    use crate::{
        product_api::{DataAccess, EntityType, HandlerResult, JsonValue, UserAuth},
        schemas::common::AggregateResult,
        schemas::nexus_ix::{
            InputIxProjectionCursor, IxProjectionCursorProjection, IxProjectionCursorQueryResult,
        },
    };
    pub(crate) async fn find_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        selections: JsonValue,
        id: String,
    ) -> HandlerResult<Option<IxProjectionCursorProjection>> {
        let res = data_access
            .find_item::<IxProjectionCursorProjection>(entity_type.clone(), selections, id, user)
            .await?;
        Ok(res)
    }

    pub(crate) async fn find_by_locator_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        selections: JsonValue,
        locator: String,
    ) -> HandlerResult<Option<IxProjectionCursorProjection>> {
        let res = data_access
            .find_item_by_locator::<IxProjectionCursorProjection>(
                entity_type.clone(),
                selections,
                locator,
                user,
            )
            .await?;
        Ok(res)
    }
    pub(crate) async fn get_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        selections: JsonValue,
    ) -> HandlerResult<Vec<IxProjectionCursorProjection>> {
        let res = data_access
            .get_items::<IxProjectionCursorProjection>(entity_type.clone(), selections, None, user)
            .await?;
        Ok(res)
    }
    pub(crate) async fn query_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        selections: JsonValue,
        filter: Option<JsonValue>,
        sort: Option<JsonValue>,
        skip: i32,
        limit: i32,
        after: Option<String>,
    ) -> HandlerResult<IxProjectionCursorQueryResult> {
        let res = data_access
            .query_items::<IxProjectionCursorProjection>(
                entity_type.clone(),
                selections,
                filter,
                sort,
                skip,
                limit,
                after,
                user,
            )
            .await?;
        let query_res = IxProjectionCursorQueryResult {
            date_time: res.date_time,
            request_duration: res.request_duration,
            skip: res.skip,
            limit: res.limit,
            page_count: res.page_count,
            page_index: res.page_index,
            query_count: res.query_count,
            next_cursor: res.next_cursor,
            previous_cursor: res.previous_cursor,
            items: res.items,
        };
        Ok(query_res)
    }

    pub(crate) async fn aggregate_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        filter: Option<JsonValue>,
        group_by: Option<JsonValue>,
        metrics: Option<JsonValue>,
        having: Option<JsonValue>,
        sort: Option<JsonValue>,
        skip: i32,
        limit: i32,
    ) -> HandlerResult<AggregateResult> {
        let res = data_access
            .aggregate_items(
                entity_type.clone(),
                filter,
                group_by,
                metrics,
                having,
                sort,
                skip,
                limit,
                user,
            )
            .await?;
        Ok(res)
    }
}
pub(crate) mod ix_run {
    #[allow(unused_imports)]
    use std::sync::Arc;

    #[allow(unused_imports)]
    use crate::schemas::nexus_ix::*;

    #[allow(unused_imports)]
    use crate::{
        product_api::{DataAccess, EntityType, HandlerResult, JsonValue, UserAuth},
        schemas::common::AggregateResult,
        schemas::nexus_ix::{InputIxRun, IxRunProjection, IxRunQueryResult},
    };
    pub(crate) async fn find_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        selections: JsonValue,
        id: String,
    ) -> HandlerResult<Option<IxRunProjection>> {
        let res = data_access
            .find_item::<IxRunProjection>(entity_type.clone(), selections, id, user)
            .await?;
        Ok(res)
    }

    pub(crate) async fn find_by_locator_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        selections: JsonValue,
        locator: String,
    ) -> HandlerResult<Option<IxRunProjection>> {
        let res = data_access
            .find_item_by_locator::<IxRunProjection>(entity_type.clone(), selections, locator, user)
            .await?;
        Ok(res)
    }
    pub(crate) async fn get_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        selections: JsonValue,
    ) -> HandlerResult<Vec<IxRunProjection>> {
        let res = data_access
            .get_items::<IxRunProjection>(entity_type.clone(), selections, None, user)
            .await?;
        Ok(res)
    }
    pub(crate) async fn query_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        selections: JsonValue,
        filter: Option<JsonValue>,
        sort: Option<JsonValue>,
        skip: i32,
        limit: i32,
        after: Option<String>,
    ) -> HandlerResult<IxRunQueryResult> {
        let res = data_access
            .query_items::<IxRunProjection>(
                entity_type.clone(),
                selections,
                filter,
                sort,
                skip,
                limit,
                after,
                user,
            )
            .await?;
        let query_res = IxRunQueryResult {
            date_time: res.date_time,
            request_duration: res.request_duration,
            skip: res.skip,
            limit: res.limit,
            page_count: res.page_count,
            page_index: res.page_index,
            query_count: res.query_count,
            next_cursor: res.next_cursor,
            previous_cursor: res.previous_cursor,
            items: res.items,
        };
        Ok(query_res)
    }

    pub(crate) async fn aggregate_impl(
        user: Option<UserAuth>,
        data_access: &Arc<DataAccess>,
        entity_type: &Arc<EntityType>,
        filter: Option<JsonValue>,
        group_by: Option<JsonValue>,
        metrics: Option<JsonValue>,
        having: Option<JsonValue>,
        sort: Option<JsonValue>,
        skip: i32,
        limit: i32,
    ) -> HandlerResult<AggregateResult> {
        let res = data_access
            .aggregate_items(
                entity_type.clone(),
                filter,
                group_by,
                metrics,
                having,
                sort,
                skip,
                limit,
                user,
            )
            .await?;
        Ok(res)
    }
}
