//
// /backend/src/schemas/denovo_workflow.rs
//    Defines structs and enums to serialize/deserialize denovo_workflow GQL objects
//    Generated by app_gen.
//
// Generated schema modules expose GraphQL DTOs that may be constructed only by
// async-graphql or downstream applications, not by backend unit tests.
#![allow(dead_code)]

#[allow(unused)]
use async_graphql::{Enum, InputObject, OneofObject, SimpleObject, Union};
use serde::{Deserialize, Serialize};

#[allow(unused)]
use super::system::*;

// DeNovoTask is_union: false ////////////////////////////////////////////////////////////

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct DeNovoTask {
    #[graphql(name = "id")]
    pub id: String,
    #[graphql(name = "tenant")]
    pub tenant: String,
    #[graphql(name = "task_name")]
    pub task_name: String,
    #[graphql(name = "workstream_id")]
    pub workstream_id: String,
    #[graphql(name = "team_id")]
    pub team_id: String,
    #[graphql(name = "owner_team")]
    pub owner_team: String,
    #[graphql(name = "phase")]
    pub phase: String,
    #[graphql(name = "risk")]
    pub risk: String,
    #[graphql(name = "days_stalled")]
    pub days_stalled: i32,
    #[graphql(name = "freshness_watermark")]
    pub freshness_watermark: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct DeNovoTaskProjection {
    #[serde(default)]
    pub record_locator: Option<String>,
    #[graphql(name = "id")]
    pub id: Option<String>,
    #[graphql(name = "tenant")]
    pub tenant: Option<String>,
    #[graphql(name = "task_name")]
    pub task_name: Option<String>,
    #[graphql(name = "workstream_id")]
    pub workstream_id: Option<String>,
    #[graphql(name = "team_id")]
    pub team_id: Option<String>,
    #[graphql(name = "owner_team")]
    pub owner_team: Option<String>,
    #[graphql(name = "phase")]
    pub phase: Option<String>,
    #[graphql(name = "risk")]
    pub risk: Option<String>,
    #[graphql(name = "days_stalled")]
    pub days_stalled: Option<i32>,
    #[graphql(name = "freshness_watermark")]
    pub freshness_watermark: Option<chrono::DateTime<chrono::Utc>>,
    #[graphql(name = "workstream")]
    pub workstream: Option<Box<WorkstreamProjection>>,
    #[graphql(name = "team")]
    pub team: Option<Box<TeamProjection>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, InputObject)]
#[graphql(rename_fields = "snake_case")]
pub struct InputDeNovoTask {
    #[graphql(name = "id")]
    pub id: Option<String>,
    #[graphql(name = "tenant")]
    pub tenant: Option<String>,
    #[graphql(name = "task_name")]
    pub task_name: Option<String>,
    #[graphql(name = "workstream_id")]
    pub workstream_id: Option<String>,
    #[graphql(name = "team_id")]
    pub team_id: Option<String>,
    #[graphql(name = "owner_team")]
    pub owner_team: Option<String>,
    #[graphql(name = "phase")]
    pub phase: Option<String>,
    #[graphql(name = "risk")]
    pub risk: Option<String>,
    #[graphql(name = "days_stalled")]
    pub days_stalled: Option<i32>,
    #[graphql(name = "freshness_watermark")]
    pub freshness_watermark: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct DeNovoTaskQueryResult {
    pub date_time: String,
    pub request_duration: f64,
    pub skip: i32,
    pub limit: i32,
    pub page_count: i32,
    pub page_index: i32,
    pub query_count: i64,
    pub next_cursor: Option<String>,
    pub previous_cursor: Option<String>,
    pub items: Vec<DeNovoTaskProjection>,
}

// Team is_union: false ////////////////////////////////////////////////////////////

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct Team {
    #[graphql(name = "id")]
    pub id: String,
    #[graphql(name = "tenant")]
    pub tenant: String,
    #[graphql(name = "name")]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct TeamProjection {
    #[serde(default)]
    pub record_locator: Option<String>,
    #[graphql(name = "id")]
    pub id: Option<String>,
    #[graphql(name = "tenant")]
    pub tenant: Option<String>,
    #[graphql(name = "name")]
    pub name: Option<String>,
    #[graphql(name = "tasks")]
    pub tasks: Option<Vec<DeNovoTaskProjection>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, InputObject)]
#[graphql(rename_fields = "snake_case")]
pub struct InputTeam {
    #[graphql(name = "id")]
    pub id: Option<String>,
    #[graphql(name = "tenant")]
    pub tenant: Option<String>,
    #[graphql(name = "name")]
    pub name: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct TeamQueryResult {
    pub date_time: String,
    pub request_duration: f64,
    pub skip: i32,
    pub limit: i32,
    pub page_count: i32,
    pub page_index: i32,
    pub query_count: i64,
    pub next_cursor: Option<String>,
    pub previous_cursor: Option<String>,
    pub items: Vec<TeamProjection>,
}

// Workstream is_union: false ////////////////////////////////////////////////////////////

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct Workstream {
    #[graphql(name = "id")]
    pub id: String,
    #[graphql(name = "tenant")]
    pub tenant: String,
    #[graphql(name = "name")]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct WorkstreamProjection {
    #[serde(default)]
    pub record_locator: Option<String>,
    #[graphql(name = "id")]
    pub id: Option<String>,
    #[graphql(name = "tenant")]
    pub tenant: Option<String>,
    #[graphql(name = "name")]
    pub name: Option<String>,
    #[graphql(name = "tasks")]
    pub tasks: Option<Vec<DeNovoTaskProjection>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, InputObject)]
#[graphql(rename_fields = "snake_case")]
pub struct InputWorkstream {
    #[graphql(name = "id")]
    pub id: Option<String>,
    #[graphql(name = "tenant")]
    pub tenant: Option<String>,
    #[graphql(name = "name")]
    pub name: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct WorkstreamQueryResult {
    pub date_time: String,
    pub request_duration: f64,
    pub skip: i32,
    pub limit: i32,
    pub page_count: i32,
    pub page_index: i32,
    pub query_count: i64,
    pub next_cursor: Option<String>,
    pub previous_cursor: Option<String>,
    pub items: Vec<WorkstreamProjection>,
}
