//
// /backend/src/schemas/nexus_ix.rs
//    Defines structs and enums to serialize/deserialize nexus_ix GQL objects
//    Generated by app_gen.
//
// Generated schema modules expose GraphQL DTOs that may be constructed only by
// async-graphql or downstream applications, not by backend unit tests.
#![allow(dead_code)]

#[allow(unused)]
use async_graphql::{Enum, InputObject, OneofObject, SimpleObject, Union};
use serde::{Deserialize, Serialize};

#[allow(unused)]
use super::system::*;

// IxAuditFact is_union: false ////////////////////////////////////////////////////////////

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct IxAuditFact {
    #[graphql(name = "id")]
    pub id: String,
    #[graphql(name = "tenant")]
    pub tenant: String,
    #[graphql(name = "run_id")]
    pub run_id: String,
    #[graphql(name = "event_kind")]
    pub event_kind: String,
    #[graphql(name = "disposition")]
    pub disposition: Option<String>,
    #[graphql(name = "fact")]
    pub fact: serde_json::Value,
    #[graphql(name = "recorded_at")]
    pub recorded_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct IxAuditFactProjection {
    #[serde(default)]
    pub record_locator: Option<String>,
    #[graphql(name = "id")]
    pub id: Option<String>,
    #[graphql(name = "tenant")]
    pub tenant: Option<String>,
    #[graphql(name = "run_id")]
    pub run_id: Option<String>,
    #[graphql(name = "event_kind")]
    pub event_kind: Option<String>,
    #[graphql(name = "disposition")]
    pub disposition: Option<String>,
    #[graphql(name = "fact")]
    pub fact: Option<serde_json::Value>,
    #[graphql(name = "recorded_at")]
    pub recorded_at: Option<chrono::DateTime<chrono::Utc>>,
    #[graphql(name = "run")]
    pub run: Option<Box<IxRunProjection>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, InputObject)]
#[graphql(rename_fields = "snake_case")]
pub struct InputIxAuditFact {
    #[graphql(name = "id")]
    pub id: Option<String>,
    #[graphql(name = "tenant")]
    pub tenant: Option<String>,
    #[graphql(name = "run_id")]
    pub run_id: Option<String>,
    #[graphql(name = "event_kind")]
    pub event_kind: Option<String>,
    #[graphql(name = "disposition")]
    pub disposition: Option<String>,
    #[graphql(name = "fact")]
    pub fact: serde_json::Value,
    #[graphql(name = "recorded_at")]
    pub recorded_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct IxAuditFactQueryResult {
    pub date_time: String,
    pub request_duration: f64,
    pub skip: i32,
    pub limit: i32,
    pub page_count: i32,
    pub page_index: i32,
    pub query_count: i64,
    pub next_cursor: Option<String>,
    pub previous_cursor: Option<String>,
    pub items: Vec<IxAuditFactProjection>,
}

// IxCommitEnvelope is_union: false ////////////////////////////////////////////////////////////

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct IxCommitEnvelope {
    #[graphql(name = "id")]
    pub id: String,
    #[graphql(name = "run_id")]
    pub run_id: String,
    #[graphql(name = "sequence")]
    pub sequence: i64,
    #[graphql(name = "event_kind")]
    pub event_kind: String,
    #[graphql(name = "envelope")]
    pub envelope: serde_json::Value,
    #[graphql(name = "committed_at")]
    pub committed_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct IxCommitEnvelopeProjection {
    #[serde(default)]
    pub record_locator: Option<String>,
    #[graphql(name = "id")]
    pub id: Option<String>,
    #[graphql(name = "run_id")]
    pub run_id: Option<String>,
    #[graphql(name = "sequence")]
    pub sequence: Option<i64>,
    #[graphql(name = "event_kind")]
    pub event_kind: Option<String>,
    #[graphql(name = "envelope")]
    pub envelope: Option<serde_json::Value>,
    #[graphql(name = "committed_at")]
    pub committed_at: Option<chrono::DateTime<chrono::Utc>>,
    #[graphql(name = "run")]
    pub run: Option<Box<IxRunProjection>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, InputObject)]
#[graphql(rename_fields = "snake_case")]
pub struct InputIxCommitEnvelope {
    #[graphql(name = "id")]
    pub id: Option<String>,
    #[graphql(name = "run_id")]
    pub run_id: Option<String>,
    #[graphql(name = "sequence")]
    pub sequence: Option<i64>,
    #[graphql(name = "event_kind")]
    pub event_kind: Option<String>,
    #[graphql(name = "envelope")]
    pub envelope: serde_json::Value,
    #[graphql(name = "committed_at")]
    pub committed_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct IxCommitEnvelopeQueryResult {
    pub date_time: String,
    pub request_duration: f64,
    pub skip: i32,
    pub limit: i32,
    pub page_count: i32,
    pub page_index: i32,
    pub query_count: i64,
    pub next_cursor: Option<String>,
    pub previous_cursor: Option<String>,
    pub items: Vec<IxCommitEnvelopeProjection>,
}

// IxContext is_union: false ////////////////////////////////////////////////////////////

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct IxContext {
    #[graphql(name = "id")]
    pub id: String,
    #[graphql(name = "tenant")]
    pub tenant: String,
    #[graphql(name = "subject")]
    pub subject: String,
    #[graphql(name = "context_kind")]
    pub context_kind: String,
    #[graphql(name = "focus_label")]
    pub focus_label: String,
    #[graphql(name = "detail")]
    pub detail: String,
    #[graphql(name = "freshness")]
    pub freshness: String,
    #[graphql(name = "evaluated_at")]
    pub evaluated_at: chrono::DateTime<chrono::Utc>,
    #[graphql(name = "revision")]
    pub revision: i64,
    #[graphql(name = "payload")]
    pub payload: serde_json::Value,
    #[graphql(name = "created_at")]
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[graphql(name = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct IxContextProjection {
    #[serde(default)]
    pub record_locator: Option<String>,
    #[graphql(name = "id")]
    pub id: Option<String>,
    #[graphql(name = "tenant")]
    pub tenant: Option<String>,
    #[graphql(name = "subject")]
    pub subject: Option<String>,
    #[graphql(name = "context_kind")]
    pub context_kind: Option<String>,
    #[graphql(name = "focus_label")]
    pub focus_label: Option<String>,
    #[graphql(name = "detail")]
    pub detail: Option<String>,
    #[graphql(name = "freshness")]
    pub freshness: Option<String>,
    #[graphql(name = "evaluated_at")]
    pub evaluated_at: Option<chrono::DateTime<chrono::Utc>>,
    #[graphql(name = "revision")]
    pub revision: Option<i64>,
    #[graphql(name = "payload")]
    pub payload: Option<serde_json::Value>,
    #[graphql(name = "created_at")]
    pub created_at: Option<chrono::DateTime<chrono::Utc>>,
    #[graphql(name = "updated_at")]
    pub updated_at: Option<chrono::DateTime<chrono::Utc>>,
    #[graphql(name = "runs")]
    pub runs: Option<Vec<IxRunProjection>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, InputObject)]
#[graphql(rename_fields = "snake_case")]
pub struct InputIxContext {
    #[graphql(name = "id")]
    pub id: Option<String>,
    #[graphql(name = "tenant")]
    pub tenant: Option<String>,
    #[graphql(name = "subject")]
    pub subject: Option<String>,
    #[graphql(name = "context_kind")]
    pub context_kind: Option<String>,
    #[graphql(name = "focus_label")]
    pub focus_label: String,
    #[graphql(name = "detail")]
    pub detail: String,
    #[graphql(name = "freshness")]
    pub freshness: String,
    #[graphql(name = "evaluated_at")]
    pub evaluated_at: chrono::DateTime<chrono::Utc>,
    #[graphql(name = "revision")]
    pub revision: Option<i64>,
    #[graphql(name = "payload")]
    pub payload: serde_json::Value,
    #[graphql(name = "created_at")]
    pub created_at: Option<chrono::DateTime<chrono::Utc>>,
    #[graphql(name = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct IxContextQueryResult {
    pub date_time: String,
    pub request_duration: f64,
    pub skip: i32,
    pub limit: i32,
    pub page_count: i32,
    pub page_index: i32,
    pub query_count: i64,
    pub next_cursor: Option<String>,
    pub previous_cursor: Option<String>,
    pub items: Vec<IxContextProjection>,
}

// IxProjectionCursor is_union: false ////////////////////////////////////////////////////////////

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct IxProjectionCursor {
    #[graphql(name = "id")]
    pub id: String,
    #[graphql(name = "tenant")]
    pub tenant: String,
    #[graphql(name = "run_id")]
    pub run_id: String,
    #[graphql(name = "command_id")]
    pub command_id: String,
    #[graphql(name = "cursor")]
    pub cursor: String,
    #[graphql(name = "projection_state")]
    pub projection_state: String,
    #[graphql(name = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct IxProjectionCursorProjection {
    #[serde(default)]
    pub record_locator: Option<String>,
    #[graphql(name = "id")]
    pub id: Option<String>,
    #[graphql(name = "tenant")]
    pub tenant: Option<String>,
    #[graphql(name = "run_id")]
    pub run_id: Option<String>,
    #[graphql(name = "command_id")]
    pub command_id: Option<String>,
    #[graphql(name = "cursor")]
    pub cursor: Option<String>,
    #[graphql(name = "projection_state")]
    pub projection_state: Option<String>,
    #[graphql(name = "updated_at")]
    pub updated_at: Option<chrono::DateTime<chrono::Utc>>,
    #[graphql(name = "run")]
    pub run: Option<Box<IxRunProjection>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, InputObject)]
#[graphql(rename_fields = "snake_case")]
pub struct InputIxProjectionCursor {
    #[graphql(name = "id")]
    pub id: Option<String>,
    #[graphql(name = "tenant")]
    pub tenant: Option<String>,
    #[graphql(name = "run_id")]
    pub run_id: Option<String>,
    #[graphql(name = "command_id")]
    pub command_id: Option<String>,
    #[graphql(name = "cursor")]
    pub cursor: String,
    #[graphql(name = "projection_state")]
    pub projection_state: String,
    #[graphql(name = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct IxProjectionCursorQueryResult {
    pub date_time: String,
    pub request_duration: f64,
    pub skip: i32,
    pub limit: i32,
    pub page_count: i32,
    pub page_index: i32,
    pub query_count: i64,
    pub next_cursor: Option<String>,
    pub previous_cursor: Option<String>,
    pub items: Vec<IxProjectionCursorProjection>,
}

// IxRun is_union: false ////////////////////////////////////////////////////////////

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct IxRun {
    #[graphql(name = "id")]
    pub id: String,
    #[graphql(name = "tenant")]
    pub tenant: String,
    #[graphql(name = "subject")]
    pub subject: String,
    #[graphql(name = "intent_key")]
    pub intent_key: String,
    #[graphql(name = "run_state")]
    pub run_state: String,
    #[graphql(name = "phase")]
    pub phase: Option<String>,
    #[graphql(name = "context_id")]
    pub context_id: String,
    #[graphql(name = "repository_version")]
    pub repository_version: i64,
    #[graphql(name = "last_sequence")]
    pub last_sequence: i64,
    #[graphql(name = "cursor")]
    pub cursor: String,
    #[graphql(name = "start_idempotency_key")]
    pub start_idempotency_key: String,
    #[graphql(name = "runtime_seal_key_id")]
    pub runtime_seal_key_id: String,
    #[graphql(name = "stored_run")]
    pub stored_run: serde_json::Value,
    #[graphql(name = "created_at")]
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[graphql(name = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct IxRunProjection {
    #[serde(default)]
    pub record_locator: Option<String>,
    #[graphql(name = "id")]
    pub id: Option<String>,
    #[graphql(name = "tenant")]
    pub tenant: Option<String>,
    #[graphql(name = "subject")]
    pub subject: Option<String>,
    #[graphql(name = "intent_key")]
    pub intent_key: Option<String>,
    #[graphql(name = "run_state")]
    pub run_state: Option<String>,
    #[graphql(name = "phase")]
    pub phase: Option<String>,
    #[graphql(name = "context_id")]
    pub context_id: Option<String>,
    #[graphql(name = "repository_version")]
    pub repository_version: Option<i64>,
    #[graphql(name = "last_sequence")]
    pub last_sequence: Option<i64>,
    #[graphql(name = "cursor")]
    pub cursor: Option<String>,
    #[graphql(name = "start_idempotency_key")]
    pub start_idempotency_key: Option<String>,
    #[graphql(name = "runtime_seal_key_id")]
    pub runtime_seal_key_id: Option<String>,
    #[graphql(name = "stored_run")]
    pub stored_run: Option<serde_json::Value>,
    #[graphql(name = "created_at")]
    pub created_at: Option<chrono::DateTime<chrono::Utc>>,
    #[graphql(name = "updated_at")]
    pub updated_at: Option<chrono::DateTime<chrono::Utc>>,
    #[graphql(name = "context")]
    pub context: Option<Box<IxContextProjection>>,
    #[graphql(name = "envelopes")]
    pub envelopes: Option<Vec<IxCommitEnvelopeProjection>>,
    #[graphql(name = "audit_facts")]
    pub audit_facts: Option<Vec<IxAuditFactProjection>>,
    #[graphql(name = "projection_cursors")]
    pub projection_cursors: Option<Vec<IxProjectionCursorProjection>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, InputObject)]
#[graphql(rename_fields = "snake_case")]
pub struct InputIxRun {
    #[graphql(name = "id")]
    pub id: Option<String>,
    #[graphql(name = "tenant")]
    pub tenant: Option<String>,
    #[graphql(name = "subject")]
    pub subject: Option<String>,
    #[graphql(name = "intent_key")]
    pub intent_key: Option<String>,
    #[graphql(name = "run_state")]
    pub run_state: String,
    #[graphql(name = "phase")]
    pub phase: Option<String>,
    #[graphql(name = "context_id")]
    pub context_id: Option<String>,
    #[graphql(name = "repository_version")]
    pub repository_version: Option<i64>,
    #[graphql(name = "last_sequence")]
    pub last_sequence: i64,
    #[graphql(name = "cursor")]
    pub cursor: String,
    #[graphql(name = "start_idempotency_key")]
    pub start_idempotency_key: Option<String>,
    #[graphql(name = "runtime_seal_key_id")]
    pub runtime_seal_key_id: Option<String>,
    #[graphql(name = "stored_run")]
    pub stored_run: serde_json::Value,
    #[graphql(name = "created_at")]
    pub created_at: Option<chrono::DateTime<chrono::Utc>>,
    #[graphql(name = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
#[graphql(rename_fields = "snake_case")]
pub struct IxRunQueryResult {
    pub date_time: String,
    pub request_duration: f64,
    pub skip: i32,
    pub limit: i32,
    pub page_count: i32,
    pub page_index: i32,
    pub query_count: i64,
    pub next_cursor: Option<String>,
    pub previous_cursor: Option<String>,
    pub items: Vec<IxRunProjection>,
}
