//
// /backend/src/routes/mod.rs
//    Generated by app_gen.
//
pub(crate) mod app_error;

#[cfg(feature = "http")]
pub(crate) mod info;

#[cfg(feature = "http")]
pub(crate) mod system;

#[cfg(feature = "http")]
pub(crate) mod tax_routing;

#[cfg(feature = "http")]
use appfw_runtime::{
    ingress::{assemble_runtime_router_for_mode, RuntimeRouteSet},
    observability::MetricsRegistry,
    provider_keys::FrameworkProvider,
    security::SecurityConfig,
    RuntimeAuthState, RuntimeMode, RuntimeProviderRegistry,
};
#[cfg(feature = "http")]
use axum::Router;
#[cfg(feature = "http")]
use std::{collections::HashMap, sync::Arc};
#[cfg(feature = "http")]
use tower_http::cors::CorsLayer;

#[cfg(feature = "http")]
use crate::admin_ui;
#[cfg(feature = "http")]
use crate::data::clients::database_client::DatabaseClientBox;
#[cfg(all(feature = "http", feature = "mcp"))]
use crate::mcp;
#[cfg(feature = "http")]
use crate::{
    config::app_config::AppConfig, data::data_access::DataAccess, product_api::runtime_provider,
};

#[cfg(all(feature = "http", feature = "provider-postgres"))]
use crate::data::clients::postgres::postgres_client::PostgresClient;

#[cfg(feature = "http")]
use app_error::AppError;

#[cfg(feature = "http")]
pub async fn get_routes(
    cors: CorsLayer,
    app_config: Arc<AppConfig>,
    app_state: RuntimeAuthState,
    security: SecurityConfig,
    runtime_mode: RuntimeMode,
) -> Result<Router, AppError> {
    // Axum docs - merging routes:
    // https://github.com/tokio-rs/axum/blob/main/axum/src/docs/routing/merge.md

    let metrics = MetricsRegistry::from_env();

    let tax_routing_data_access =
        create_data_access_for_schema(app_config.clone(), "tax_routing", metrics.clone()).await?;

    let readiness = info::ReadinessState::new(vec![
        info::HealthCheck::pass("configuration", "loaded"),
        info::HealthCheck::pass("auth", "configured"),
        info::HealthCheck::pass("data_access", "initialized"),
    ])
    .with_provider_check("tax_routing", tax_routing_data_access.clone());

    let info_router = info::nest_routes(Router::new(), metrics.clone(), readiness).await;

    let tax_routing_router = tax_routing::get_routes(
        tax_routing_data_access.clone(),
        app_state.clone(),
        security.clone(),
    )
    .await;

    let mut data_access_by_schema = HashMap::new();

    data_access_by_schema.insert("tax_routing".to_string(), tax_routing_data_access.clone());

    let admin_router = admin_ui::get_routes(
        app_config.clone(),
        app_state.clone(),
        security.clone(),
        data_access_by_schema.clone(),
    );
    #[cfg(all(feature = "http", feature = "mcp"))]
    let mcp_router = mcp::get_routes(
        app_config.clone(),
        app_state.clone(),
        security.clone(),
        data_access_by_schema.clone(),
    );

    let mut route_set = RuntimeRouteSet::new()
        .with_info(info_router)
        .with_admin(admin_router)
        .with_schema(tax_routing_router);

    if security.product_ui_enabled {
        if let Some(product_ui_router) = appfw_runtime::product_ui::product_ui_routes_if_present(
            env!("CARGO_MANIFEST_DIR"),
            ["/system", "/tax_routing"],
        ) {
            route_set = route_set.with_product_ui(product_ui_router);
        }
    }

    #[cfg(all(feature = "http", feature = "mcp"))]
    let route_set = route_set.with_mcp(mcp_router);

    Ok(assemble_runtime_router_for_mode(
        route_set,
        cors,
        metrics,
        &security,
        &runtime_mode,
    ))
}

#[cfg(feature = "http")]
async fn create_data_access_for_schema(
    app_config: Arc<AppConfig>,
    schema_name: &str,
    metrics: MetricsRegistry,
) -> Result<Arc<DataAccess>, AppError> {
    let data_source_name = app_config.get_schema_data_source_name(schema_name)?;
    let client = create_database_client(app_config.clone(), data_source_name).await?;
    Ok(Arc::new(DataAccess::init(app_config, client, metrics)))
}

#[cfg(feature = "http")]
async fn create_database_client(
    app_config: Arc<AppConfig>,
    data_source_name: String,
) -> Result<DatabaseClientBox, AppError> {
    let provider = runtime_provider(app_config.get_data_source_type(&data_source_name)?);
    database_client_registry(app_config)
        .create(provider, data_source_name)
        .await
}

#[cfg(feature = "http")]
fn database_client_registry(
    app_config: Arc<AppConfig>,
) -> RuntimeProviderRegistry<DatabaseClientBox, AppError> {
    let registry = RuntimeProviderRegistry::new();

    #[cfg(feature = "provider-postgres")]
    let registry = registry.register(FrameworkProvider::Postgres, {
        let app_config = app_config.clone();
        move |data_source_name| {
            let app_config = app_config.clone();
            async move {
                Ok(
                    Box::new(PostgresClient::init(app_config, data_source_name).await?)
                        as DatabaseClientBox,
                )
            }
        }
    });

    registry
}
