//
// Generated by app_gen for crm.
//   - From tests yaml
//

#[cfg(test)]
mod tests {

    use anyhow::Result;
    use serde_json::json;

    use crate::harness::TestContext;

    #[tokio::test]
    async fn test_activity_parties_scenario() -> Result<()> {
        let mut ctx = TestContext::from_env()?;

        step_find_activity_party(&mut ctx).await?;

        Ok(())
    }

    async fn step_find_activity_party(ctx: &mut TestContext) -> Result<()> {
        // Description: find seeded activity party with NavToOne activity
        println!("*** Test description: find seeded activity party with NavToOne activity ***");

        let req = r#"
      query($id: String!){
        findActivityParty(id: $id){
            id,role,party_type,display_name,is_required,responded_status,activity { id,subject }

        }
      }
    "#;

        let variables = Some(json!({
        "id": "ac71fa00-0000-4000-8000-100000000002"
        }));

        let gql_result = ctx
            .execute_graphql("pdsh_admin", "crm", req, variables)
            .await?;
        println!("find_activity_party GraphQL result: {:?}", gql_result);

        ctx.expect_data(
      "find_activity_party",
      &gql_result,
      "findActivityParty",
      json!({"id":"ac71fa00-0000-4000-8000-100000000002","role":"Required Attendee","party_type":"Contact","display_name":"Maya Johnson","is_required":true,"responded_status":"Accepted"}),
      None,
    )?;

        Ok(())
    }
}
