//
// Generated by app_gen for crm.
//   - From tests yaml
//

#[cfg(test)]
mod tests {

    use anyhow::Result;
    use serde_json::json;

    use crate::harness::TestContext;

    #[tokio::test]
    async fn test_activities_scenario() -> Result<()> {
        let mut ctx = TestContext::from_env()?;

        step_find_activity(&mut ctx).await?;

        Ok(())
    }

    async fn step_find_activity(ctx: &mut TestContext) -> Result<()> {
        // Description: find seeded activity by id as admin
        println!("*** Test description: find seeded activity by id as admin ***");

        let req = r#"
      query($id: String!){
        findActivity(id: $id){
            id,subject,status,type_id,account_id,contact_id,opportunity_id,activity_type { id,name },account { id,name },contact { id,first_name,last_name },opportunity { id,name }

        }
      }
    "#;

        let variables = Some(json!({
        "id": "ac710007-0000-4000-8000-100000000001"
        }));

        let gql_result = ctx
            .execute_graphql("pdsh_admin", "crm", req, variables)
            .await?;
        println!("find_activity GraphQL result: {:?}", gql_result);

        ctx.expect_data(
      "find_activity",
      &gql_result,
      "findActivity",
      json!({"id":"ac710007-0000-4000-8000-100000000001","subject":"Discovery Call - Acme Dental","status":"Completed","type_id":"ac71ec00-0000-4000-8000-100000000002","account_id":"a0c00000-0000-4000-8000-100000000001","contact_id":"c0c00000-0000-4000-8000-100000000001","opportunity_id":"099c0000-0000-4000-8000-100000000001"}),
      None,
    )?;

        Ok(())
    }
}
