//
// Generated by app_gen for crm.
//   - From tests yaml
//

#[cfg(test)]
mod tests {

    use anyhow::Result;
    use serde_json::json;

    use crate::harness::TestContext;

    #[tokio::test]
    async fn test_article_comments_scenario() -> Result<()> {
        let mut ctx = TestContext::from_env()?;

        step_find_article_comment(&mut ctx).await?;

        Ok(())
    }

    async fn step_find_article_comment(ctx: &mut TestContext) -> Result<()> {
        // Description: find seeded article comment with NavToOne article
        println!("*** Test description: find seeded article comment with NavToOne article ***");

        let req = r#"
      query($id: String!){
        findArticleComment(id: $id){
            id,subject,author_name,sentiment,is_internal,article { id,title }

        }
      }
    "#;

        let variables = Some(json!({
        "id": "a471c0de-0000-4000-8000-100000000003"
        }));

        let gql_result = ctx
            .execute_graphql("pdsh_admin", "crm", req, variables)
            .await?;
        println!("find_article_comment GraphQL result: {:?}", gql_result);

        ctx.expect_data(
      "find_article_comment",
      &gql_result,
      "findArticleComment",
      json!({"id":"a471c0de-0000-4000-8000-100000000003","subject":"Helpful import notes","author_name":"Morgan Ops","sentiment":"Positive","is_internal":false}),
      None,
    )?;

        Ok(())
    }
}
