//
// Generated by app_gen for crm.
//   - From tests yaml
//

#[cfg(test)]
mod tests {

    use anyhow::Result;
    use serde_json::json;

    use crate::harness::TestContext;

    #[tokio::test]
    async fn test_opportunity_stages_scenario() -> Result<()> {
        let mut ctx = TestContext::from_env()?;

        step_find_opportunity_stage(&mut ctx).await?;

        Ok(())
    }

    async fn step_find_opportunity_stage(ctx: &mut TestContext) -> Result<()> {
        // Description: find seeded opportunity stage by id as admin
        println!("*** Test description: find seeded opportunity stage by id as admin ***");

        let req = r#"
      query($id: String!){
        findOpportunityStage(id: $id){
            id,name,is_closed,is_won,sort_order

        }
      }
    "#;

        let variables = Some(json!({
        "id": "0998a900-0000-4000-8000-100000000003"
        }));

        let gql_result = ctx
            .execute_graphql("pdsh_admin", "crm", req, variables)
            .await?;
        println!("find_opportunity_stage GraphQL result: {:?}", gql_result);

        ctx.expect_data(
      "find_opportunity_stage",
      &gql_result,
      "findOpportunityStage",
      json!({"id":"0998a900-0000-4000-8000-100000000003","name":"Proposal","is_closed":false,"is_won":false,"sort_order":30}),
      None,
    )?;

        Ok(())
    }
}
