//
// Generated by app_gen for crm.
//   - From tests yaml
//

#[cfg(test)]
mod tests {

    use anyhow::Result;
    use serde_json::json;

    use crate::harness::TestContext;

    #[tokio::test]
    async fn test_queues_scenario() -> Result<()> {
        let mut ctx = TestContext::from_env()?;

        step_find_queue(&mut ctx).await?;

        Ok(())
    }

    async fn step_find_queue(ctx: &mut TestContext) -> Result<()> {
        // Description: find seeded queue with business unit and queue items
        println!("*** Test description: find seeded queue with business unit and queue items ***");

        let req = r#"
      query($id: String!){
        findQueue(id: $id){
            id,name,queue_type,is_active,business_unit { id,name },queue_items { id,title,status }

        }
      }
    "#;

        let variables = Some(json!({
        "id": "9e0e0000-0000-4000-8000-100000000001"
        }));

        let gql_result = ctx
            .execute_graphql("pdsh_admin", "crm", req, variables)
            .await?;
        println!("find_queue GraphQL result: {:?}", gql_result);

        ctx.expect_data(
      "find_queue",
      &gql_result,
      "findQueue",
      json!({"id":"9e0e0000-0000-4000-8000-100000000001","name":"Enterprise Onboarding","queue_type":"Sales","is_active":true}),
      None,
    )?;

        Ok(())
    }
}
