//
// Backend system: Handlers
//    Defines Query and Mutation objects for system GQL entity_types
//    Generated by app_gen.
//
#![allow(dead_code)]

//
// Mod crates

pub(crate) mod entity_type;
pub(crate) mod generated;
pub(crate) mod schema;

//
// Wireups
#[cfg(feature = "http")]
use anyhow::Result;
#[cfg(feature = "http")]
use async_graphql::{Context, FieldResult, Object};

#[cfg(feature = "http")]
use super::selections::get_query_selections;
#[cfg(feature = "http")]
use crate::schemas::common::AggregateResult;
#[cfg(feature = "http")]
#[allow(unused)]
use crate::{
    data::query_ir::PaginationPolicy,
    product_api::{
        data_access_from_context, entity_type_for_handler, user_from_context, EntityType,
        HandlerContext, JsonValue,
    },
    routes::app_error::AppError,
    schemas::system::{
        ArrayLengthValidator, ConcatenateComputed, CustomMethod, DataAccessExecution, DataSource,
        DataSourceEnvironment, EntityTypeProjection, ForeignKey, FormatComputed, FunctionValidator,
        InflectionComputed, InputEntityType, InputSchema, ManyToManyProperty, NavByFkProperty,
        NestedEntityType, PropertyType, SchemaProjection, SchemaQueryResult, StringLengthValidator,
        StringPatternValidator, TypeMethodArg, UniquenessValidator, ValueRangeValidator,
        WordComputed,
    },
};

#[cfg(feature = "http")]
#[derive(Default)]
pub struct SystemQuery;

#[cfg(feature = "http")]
#[Object(extends)]
impl SystemQuery {
    async fn user_info(&self, ctx: &Context<'_>) -> Result<JsonValue> {
        // Convenience handler to return user info.
        // If user is not None, then they are authenticated.
        if let Some(user) = user_from_context(ctx) {
            Ok(serde_json::to_value(user)?)
        } else {
            Ok(serde_json::json!({ "error": true }))
        }
    }

    async fn find_schema(
        &self,
        ctx: &Context<'_>,
        id: String,
    ) -> FieldResult<Option<SchemaProjection>> {
        let handler_context = from_context(ctx, "system", "Schema")?;
        let (user, data_access, entity_type, selections) = handler_context.into_handler_parts();

        let res = schema::find_impl(user, &data_access, &entity_type, selections, id).await;

        match res {
            Ok(res) => Ok(res),
            Err(e) => Err(e.into()),
        }
    }

    async fn find_schema_by_locator(
        &self,
        ctx: &Context<'_>,
        locator: String,
    ) -> FieldResult<Option<SchemaProjection>> {
        let handler_context = from_context(ctx, "system", "Schema")?;
        let (user, data_access, entity_type, selections) = handler_context.into_handler_parts();

        let res =
            schema::find_by_locator_impl(user, &data_access, &entity_type, selections, locator)
                .await;

        match res {
            Ok(res) => Ok(res),
            Err(e) => Err(e.into()),
        }
    }

    async fn get_schemas(&self, ctx: &Context<'_>) -> FieldResult<Vec<SchemaProjection>> {
        let handler_context = from_context(ctx, "system", "Schema")?;
        let (user, data_access, entity_type, selections) = handler_context.into_handler_parts();

        let res = schema::get_impl(user, &data_access, &entity_type, selections).await;

        match res {
            Ok(res) => Ok(res),
            Err(e) => Err(e.into()),
        }
    }

    async fn query_schemas(
        &self,
        ctx: &Context<'_>,
        filter: Option<JsonValue>,
        sort: Option<JsonValue>,
        skip: Option<i32>,
        limit: Option<i32>,
        after: Option<String>,
    ) -> FieldResult<SchemaQueryResult> {
        let handler_context = from_context(ctx, "system", "Schema")?;
        let (user, data_access, entity_type, selections) = handler_context.into_handler_parts();
        let (skip, limit) = pagination_args(skip, limit)?;

        let res = schema::query_impl(
            user,
            &data_access,
            &entity_type,
            selections,
            filter,
            sort,
            skip,
            limit,
            after,
        )
        .await;

        match res {
            Ok(res) => Ok(SchemaQueryResult {
                date_time: res.date_time,
                request_duration: res.request_duration,
                skip: res.skip,
                limit: res.limit,
                page_count: res.page_count,
                page_index: res.page_index,
                query_count: res.query_count,
                next_cursor: res.next_cursor,
                previous_cursor: res.previous_cursor,
                items: res.items,
            }),
            Err(e) => Err(e.into()),
        }
    }
    async fn aggregate_schemas(
        &self,
        ctx: &Context<'_>,
        filter: Option<JsonValue>,
        group_by: Option<JsonValue>,
        metrics: Option<JsonValue>,
        having: Option<JsonValue>,
        sort: Option<JsonValue>,
        skip: Option<i32>,
        limit: Option<i32>,
    ) -> FieldResult<AggregateResult> {
        let handler_context = from_context_without_selections(ctx, "system", "Schema")?;
        let (user, data_access, entity_type, _) = handler_context.into_handler_parts();
        let (skip, limit) = pagination_args(skip, limit)?;

        let res = data_access
            .aggregate_items(
                entity_type,
                filter,
                group_by,
                metrics,
                having,
                sort,
                skip,
                limit,
                user,
            )
            .await;

        match res {
            Ok(res) => Ok(res),
            Err(e) => Err(e.into()),
        }
    }

    async fn get_schema_types(
        &self,
        ctx: &Context<'_>,
        schema_name: String,
    ) -> FieldResult<Vec<EntityType>> {
        // Custom-method context: do NOT parse selections against the calling entity's props,
        // because the return type is `Vec<EntityType>` whose fields generally do not
        // exist on `EntityType`. Resolver receives Null selections.
        let handler_context = from_context_without_selections(ctx, "system", "EntityType")?;
        let (user, data_access, entity_type, selections) = handler_context.into_handler_parts();

        let res = entity_type::get_schema_types_impl(
            user,
            &data_access,
            &entity_type,
            selections,
            schema_name,
        )
        .await;

        match res {
            Ok(res) => Ok(res),
            Err(e) => Err(e.into()),
        }
    }
}

#[cfg(feature = "http")]
#[derive(Default)]
pub struct SystemMutation;

#[cfg(feature = "http")]
#[Object]
impl SystemMutation {
    #[graphql(visible = false)]
    async fn appfw_mutation_root(&self) -> bool {
        true
    }

    async fn create_schema(
        &self,
        ctx: &Context<'_>,
        input: InputSchema,
    ) -> FieldResult<SchemaProjection> {
        let handler_context = from_context(ctx, "system", "Schema")?;
        let (user, data_access, entity_type, selections) = handler_context.into_handler_parts();

        let res = schema::create_impl(user, &data_access, &entity_type, selections, input).await;

        match res {
            Ok(res) => Ok(res),
            Err(e) => Err(e.into()),
        }
    }

    async fn update_schema(
        &self,
        ctx: &Context<'_>,
        input: InputSchema,
    ) -> FieldResult<SchemaProjection> {
        let handler_context = from_context(ctx, "system", "Schema")?;
        let (user, data_access, entity_type, selections) = handler_context.into_handler_parts();

        let res = schema::update_impl(user, &data_access, &entity_type, selections, input).await;

        match res {
            Ok(res) => Ok(res),
            Err(e) => Err(e.into()),
        }
    }

    pub async fn delete_schema(&self, ctx: &Context<'_>, input: InputSchema) -> FieldResult<i64> {
        let handler_context = from_context_without_selections(ctx, "system", "Schema")?;
        let (user, data_access, entity_type, _) = handler_context.into_handler_parts();

        let res = schema::delete_impl(user, &data_access, &entity_type, input).await;

        match res {
            Ok(res) => Ok(res),
            Err(e) => Err(e.into()),
        }
    }
}

#[cfg(feature = "http")]
fn from_context(
    ctx: &Context<'_>,
    schema_name: &'static str,
    type_name: &'static str,
) -> std::result::Result<HandlerContext, AppError> {
    let user = user_from_context(ctx);
    let data_access = data_access_from_context(ctx);
    let entity_type = entity_type_for_handler(&data_access, schema_name, type_name)?;
    let selections = get_query_selections(
        data_access.app_config.clone(),
        entity_type.clone(),
        ctx.field(),
    )?;
    Ok(HandlerContext::new(
        user,
        data_access,
        entity_type,
        selections,
    ))
}

#[cfg(feature = "http")]
fn from_context_without_selections(
    ctx: &Context<'_>,
    schema_name: &'static str,
    type_name: &'static str,
) -> std::result::Result<HandlerContext, AppError> {
    let user = user_from_context(ctx);
    let data_access = data_access_from_context(ctx);
    let entity_type = entity_type_for_handler(&data_access, schema_name, type_name)?;
    Ok(HandlerContext::new(
        user,
        data_access,
        entity_type,
        JsonValue::Null,
    ))
}

#[cfg(feature = "http")]
fn pagination_args(
    skip: Option<i32>,
    limit: Option<i32>,
) -> std::result::Result<(i32, i32), AppError> {
    Ok(PaginationPolicy::from_env().normalize(skip, limit)?)
}
